### ISSUE TITLE
Fqn class based in a interface

### ISSUE THREAD

**Issue by placetopay** [cloudcreativity/laravel-json-api#100]
It will be great if the class CloudCreativity\JsonApi\Utils\Str\Fqn use a interface implementation when resolving Adapters, Authorizers, Hydrators, etc, because the way my project is structured don't fit with the by-resource option when setting resources in config file. For example:

The options this library presents:

by-resource : true

\App\JsonApi\Posts\{Schema, Hydrator}

by-resource : false

\App\JsonApi\Schemas\{User, Post, Comment}
\App\JsonApi\Hydrators\{User, Post, Comment}

What I need

\App\JsonApi\Schemas\{UserSchema, PostSchema, CommentSchema}
\App\JsonApi\Hydrators\{UserHydrator, PostHydrator, CommentHydrator}

This to avoid conflict when I search between the schema file and the Entity class because the project is very big

**Comment by lindyhopchris** [comment]
Great idea, this would be a good addition.

**Comment by lindyhopchris** [comment]
This has been implemented on the `1.x-dev` branch, but I need to document how you would override it. Marking this issue as a docs update.

**Comment by lindyhopchris** [comment]
Closing this as the default behaviour on the `develop` branch is now to append the type when using *not-by-resource* resolution, i.e:

`App\JsonApi\Adapters\PostAdapter`

This will be released as `1.0.0-alpha.3`
