### ISSUE TITLE
How to do Route::group in routes/api.php

### ISSUE THREAD

**Issue by horsebuzz** [cloudcreativity/laravel-json-api#101]
I am trying to implement Laravel Passport using this [link](http://itsolutionstuff.com/post/laravel-5-how-to-create-api-authentication-using-passport-example.html) and i am stuck at the Step 5: Create API Route.

I could not figure out how to give the routes for `login` and `register` .

I added the routes like following

    Route::post('login', 'Api\UserController@login');
    Route::post('register', 'Api\UserController@register');

    JsonApi::register('v1', ['namespace' => 'Api','middleware' => 'auth:api'], function (Api $api) {

        $api->resource('comments');
        $api->resource('people');
        $api->resource('posts', ['has-one' => 'author', 'has-many' => ['comments', 'tags']]);
        $api->resource('sites');
    });

But it throw me error of `Route [login] not found.`

Could not find anything of how to implement `Aunthentication` in the docs.

Appreciate any help.

Thank you

**Comment by lindyhopchris** [comment]
Calling `Route` methods in your `api.php` should work fine (I use it all the time). If you use the `php artisan route:list` command, you can see what the route is being registered as.

There's some notes on authorizers in this issue:
https://github.com/cloudcreativity/laravel-json-api/issues/98

**Comment by lindyhopchris** [comment]
Closing this as authorization is now extensively covered in the docs.
