### ISSUE TITLE
Is it possible to set a models relationship before saving to database?

### ISSUE THREAD

**Issue by moneal** [cloudcreativity/laravel-json-api#102]
I have a model that is related to a team. When submitting a new create request for a model with a relationship it initially saves the record without the team_id being set. My database structure does not allow the field to be null and this causes a error.

**Comment by moneal** [comment]
Never mind. It looks like I forgot to set the relationship on my hydrator.

**Comment by lindyhopchris** [comment]
No problem glad you figured it out. Sorry the documentation isn't complete at the moment.

**Comment by moneal** [comment]
No problem on the documentation. The package is great so far and saved me tons of work.
