### ISSUE TITLE
Route Model Binding is broken

### ISSUE THREAD

**Issue by tooshay** [cloudcreativity/laravel-json-api#115]
Having created a fresh Laravel project with a simple model (`Post`, for this purpose) and corresponding controllers, resources, tables, endpoints etc, as per the documentation, trying to update a record throws the following exception:

```
Id member is not a string. at .../Projects/jsonapi/vendor/cloudcreativity/json-api/src/Object/IdentifiableTrait.php:74
```

My `PATCH` to /api/v1/posts/2 looks like this:

```
{
  "data": {
	"id": 2,
    "type": "posts",
    "attributes": {
      "body": "patch"
    },
    "relationships": {

    }
  }
}
```

Having drilled down a bit, it seems as though although we are now "substituting bindings so that the `$record` variable passed to controller actions is the actual record (object), rather than the id" (as per the docs), in fact it still behaves as though an ID is being passed in and not an object (dumping the `$id` variable passed in to `IdentifiableTrait` shows as much.)

Am I missing something obvious? Or is this actually broken?

**Comment by tooshay** [comment]
My temporary fix for the time being happens in `RequestInterpreter`:

```
    /**
     * @inheritDoc
     */
    public function getResourceId()
    {
        $record  = $this->request->route(ResourceRegistrar::PARAM_RESOURCE_ID);

        return (string) $record->id;
    }
```

...As `Request::route('record')` seems to be returning an array, and not just an ID.

**Comment by lindyhopchris** [comment]
Hi! All the tests would be failing if this wasn't working, so I think it's something specific about your implementation. It's tested here:
https://github.com/cloudcreativity/laravel-json-api/blob/master/tests/Http/Controllers/SitesController.php#L62

I'm not sure why you're having to change the request interpreter, as that is used before the binding is substituted.

Is this an Eloquent controller? If so, are you not extending the `EloquentController`? I think to track this down I'm going to see what you're doing in the controller.

**Comment by lindyhopchris** [comment]
Actually, the original thing you posted:

```
Id member is not a string. at .../Projects/jsonapi/vendor/cloudcreativity/json-api/src/Object/IdentifiableTrait.php:74
```

`id` is a reference to the `id` in the data payload you posted:

```
{
  "data": {
	"id": 2,
    "type": "posts",
    "attributes": {
      "body": "patch"
    },
    "relationships": {

    }
  }
}
```

Should be:

```
{
  "data": {
	"id": "2",
    "type": "posts",
    "attributes": {
      "body": "patch"
    },
    "relationships": {

    }
  }
}
```

**Comment by tooshay** [comment]
Thanks very much, @lindyhopchris. I wasn't using the `EloquentController`, I extended the regular one and implemented it like outlined in the docs, which was the mistake. Extending the `EloquentController` has fixed everything.

**Comment by lindyhopchris** [comment]
np - hopefully i'm going to have more time to spend on working towards 1.0 later this month, and as part of working towards that I'll be filling out the documentation to hopefully avoid some of these issues!
