### ISSUE TITLE
getHydratorForRelation / getHydratorForModel

### ISSUE THREAD

**Issue by theTechGuyy** [cloudcreativity/laravel-json-api#116]
Hi,

I'm currently working on a generalized way to "sidepost" relations over the included key,
meaning creating a relation while creating a record.
As this is not covered in the json api 1.0 I'm working on a custom solution for this.

To achieve a generalized solution and avoid linking specific relation hydrators manually into the controller, I'm looking for a way to resolve a resource, model class or relation name to the respective hydrator.
Is there any way to get a hydrator / resolve to the hydrator class, based on a resource, model or relation name? e.g. `getHydratorForResource/Relation/Model`

Couldn't find something with some code digging.

Thanks in advance for the help.

**Comment by lindyhopchris** [comment]
Hi. There isn't at the moment, but this is something that might be introduced quite soon. I'm currently working on the v1.0 stuff around relationships, and I think I might have to introduce something like this in the process.

I leave this issue open and let you know how I get on once I've settled how I'm going to sort out what I'm currently working on.

**Comment by theTechGuyy** [comment]
Thanks for the response. For anybody facing this issue until then, here my hacky fix that works, when standards are used throughout:

    $api = json_api(); // enter api name if needed
    $apiResources = $api->getResources();
    $relatedClass = $apiResources->get($modelData->type)->getRecordFqns()[0]; // $modelData->type = resourcename ex. `posts`
    $shortClassName = (new \ReflectionClass($relatedClass))->getShortName();
    $relatedHydratorClass = '\\App\\JsonApi\\'.str_plural($shortClassName).'\\Hydrator';
    $relationName = Str::camelize($key);

obv one should use `$apiResources->has()` and `class_exists` on the $relatedHydratorClass to avoid any fails.

**Comment by lindyhopchris** [comment]
Closing this as it is now possible to do this on the 1.x-dev branch.

Hydrators have been merged into adapters and it is possible to get the adapter for a specific resource type using the `StoreInterface::adapterFor($resourceType)` method.
