### ISSUE TITLE
Get EloquentController working with Patch, Post on Relationships

### ISSUE THREAD

**Issue by leonardfactory** [cloudcreativity/laravel-json-api#124]
Hi guys! I've started using this wonderful library, however I got stuck trying to implement `PATCH` and `POST` for *relationships*, i.e. `POST /post/1/relationship/tags`, in order to **link** a tag to another post (many-to-many relation). I'm using the `EloquentController` base class.

However, when I try to send POST request, Controller is throwing the following Exception:

```
Method [addToRelationship] does not exist
```

I've seen that the `addToRelationship` method in the `EloquentController` is not defined (even if it's there a stub in the `JsonApiController`.)

So, I'd want to ask: is this a feature that missing (Road to 1.0, yeah!) or am I doing something wrong?

Thanks!

**Comment by lindyhopchris** [comment]
Hi! Glad you like the package, sorry it's taking a while to get to 1.0

Full support for all the relationship methods is being worked on at the moment (it's on a branch at the moment but I wouldn't recommend using it as it is still being iterated on). The plan is that the next release (v0.12) will add in full relationship support.

In the meantime, I'd recommend implementing an `addToRelationship` method on whichever controllers you need it for the moment. If you get stuck doing that just let me know and I can help point you in the right direction.

**Comment by leonardfactory** [comment]
Hi @lindyhopchris! Actually I'm going in this direction, so I digged inside source code and implemented a solution like this:

```php
    /**
     * Handles resource linkage for a To-Many relationship.
     *
     * @param RequestInterface $request
     * @return mixed
     */
    public function addToRelationship(RequestInterface $request)
    {
        $model = $this->getRecord($request);
        $key   = $this->keyForRelationship($request->getRelationshipName());

        $links = $request->getDocument()->getResources()->getAll();

        $ids = array_map(function(ResourceObjectInterface $link) {
            return $link->getId();
        }, $links);

        $model->{$key}()->syncWithoutDetaching($ids);

        return $this
            ->reply()
            ->relationship($model->{$key});
    }
``` 

However I'm posting it here, and I'd be glad to know if you find this solution viable.

Anyway, I'm actually developing a Laravel Admin Panel based on Json Api and it is at first stage, so I'll follow this package releases in order to keep it updated; I'll link it here when I've got to release it OSS 🎉 .

Thanks again.

**Comment by lindyhopchris** [comment]
@leonardfactory interesting, what are you using for the frontend in this admin panel? The reason we use JSON API is because we use Laravel + Ember.js

**Comment by leonardfactory** [comment]
I'm developing a solution based on React.js since we've hade a very good experience with it. However this is just about the view layer; the data handling is a custom middleware built on top of the JSON API spec, since I've not found many libraries working seamlessly in JS

**Comment by leonardfactory** [comment]
After some tries with other relationship types, I've changed the method to the following implementation. Posting it here in case someone may find it useful!

```php
    /**
     * Handles resource linkage for a To-Many relationship.
     *
     * @param RequestInterface $request
     * @return mixed
     */
    public function addToRelationship(RequestInterface $request)
    {
        $record = $this->getRecord($request);
        $key    = $this->keyForRelationship($request->getRelationshipName());

        $links = $request->getDocument()->getResources()->getAll();

        $ids = array_map(function(ResourceObjectInterface $link) {
            return $link->getId();
        }, $links);

        /**
         * Handles different relationship types (many-to-many and one-to-many)
         *
         * TODO: Implement HasManyThrough
         */
        $relationship = $record->{$key}();

        if (
            $relationship instanceof HasMany ||
            $relationship instanceof MorphMany
        ) {
            $related = $relationship->getRelated();
            $related
                ->getModel()
                ->whereIn($related->getKeyName(), $ids)
                ->update([
                    $relationship->getForeignKeyName() => $record->getKey()
                ]);
        }
        else if (
            $relationship instanceof BelongsToMany ||
            $relationship instanceof MorphToMany
        ) {
            $relationship->syncWithoutDetaching($ids);
        }

        return $this
            ->reply()
            ->relationship($record->{$key});
    }
```

@lindyhopchris I'm going to work on these methods since I need them in the following days. Would you like a PR or are you working on these right now? In case you're interested, just ping me

**Comment by lindyhopchris** [comment]
@leonardfactory thanks for the offer of a PR. Normally I'd take you up on the offer, but I'm actually working on this at the moment so there's no need to submit a PR. I'm moving all the logic to the hydrator, as that's responsible for modifying resources, but approach is very similar to what you're doing.

**Comment by leonardfactory** [comment]
Awesome, I was asking exactly for this reason. Looking forward to it, thank you!

**Comment by lindyhopchris** [comment]
Closing this as modifying relationships is now implemented on the `1.x-dev` branch.
