### ISSUE TITLE
Is there any chances to change the attribute name in response?

### ISSUE THREAD

**Issue by ericgaonz** [cloudcreativity/laravel-json-api#127]
my field name is "house_number", but I hope it shows as "Hourse No." in response, is it possible?

protected $attributes = [
        ...
        '**house_number**',
        ...
    ];

{
    "data": {
        "type": "customers",
        "id": "19446",
        "attributes": {
            "created-at": null,
            "updated-at": null,
            ...
            "**house-number**": "17a",
            ...
        },
        "links": {
            "self": "http://llp.app/api/v1/customers/19446"
        }
    }
}

**Comment by lindyhopchris** [comment]
Yes, it's possible:

```php
protected $attributes = [
   'foo',
  'bar',
  'house_number' => 'house-no'
]
```

**Comment by ericgaonz** [comment]
Thank you, it was fixed.
