### ISSUE TITLE
Default pagination parameters do not seem to be respected

### ISSUE THREAD

**Issue by dimitvassilev** [cloudcreativity/laravel-json-api#131]
Hi,
I have provided a resource adapter with the following default pagination parameters:

`protected $defaultPagination = [
    'size' => 5,
    'number' => 2
    ];`,
however I still got the default laravel "current-page": 1,"per-page": 15 pagination (with no explicitely requested pagination parameters in the URI), so I delved a bit into the code and it seems that the defaultPagination is disregarded in the last line of the EloquentAdapter's query() method
`return $pagination->isEmpty() ? $this->all($query) : $this->paginate($query, $parameters);`

$pagination gets either the parameters provided in the query string, or (if none are provided) the $defaultPagination, however after it is checked for being empty, the paginate() method still receives the query string $parameters instead of the $pagination.
I guess the easiest and backward-compatible fix would be to create a new instance of EncodingParameters where $pagination is passed for pagination parameters and the rest params are copied from the original $parameters (rather than modifying the paginate() methods of the EloquentAdapter and the PagingStrategyInterface to receive an array as a second parameter). I am not sure for the case where for example only page[size] has been specified - if $pagination['number'] should not be taken as a default. If so, some more checks have to be added as well in the query() or extractPagination() method.

**Comment by dimitvassilev** [comment]
I have overriden the extractPagination() method from the EloquentAdapter in this way:

```php
 protected function extractPagination(EncodingParametersInterface $parameters)
    {
        $pagination = (array) $parameters->getPaginationParameters();
        return new Collection(array_merge((array) $this->defaultPagination(),$pagination));
    }
```

so as to take any of the parameters from the defaults if they have not been specified in the url, while the query() method looks like:

```php
 public function query(EncodingParametersInterface $parameters)
    {
        $pagination = $this->extractPagination($parameters)->toArray();
        $parameters = new EncodingParameters(
            $parameters->getIncludePaths(),
            $parameters->getFieldSets(),
            $parameters->getSortParameters(),
            $pagination,
            $parameters->getFilteringParameters(),
            $parameters->getUnrecognizedParameters()
            );
        return parent::query($parameters);
    }
```

This works nice for the page size - whenever it is not specified in the url, it is taken and applied from the defaults, however I still had a problem that whatever the $defaultPagination[ 'number'] value is set, the result is still paginated with  "current-page": 1. 

As far as I gathered where the problem is, I had to extend StandardStrategy with

 ```php
    protected function getPage(Collection $collection)
    {
        return (int) $collection->get($this->getPageKey());
    }
```

and override its query() method:

 ```php
    protected function query($query, Collection $pagingParameters)
    {
        $pageName = $this->getPageKey();
        $size = $this->getPerPage($pagingParameters) ?: $this->getDefaultPerPage($query);
        $number = $this->getPage($pagingParameters);
        $cols = $this->getColumns();

        return ($this->isSimplePagination() && method_exists($query, 'simplePaginate')) ?
            $query->simplePaginate($size, $cols, $pageName, $number) :
            $query->paginate($size, $cols, $pageName, $number);
    }
```
to pass the page number as a forth parameter in the return $query->paginate() and ->simplePaginate() statements. This seems to work for both default and provided-in-url page number parameter, however, I am not sure if this is the right solution, namely how is it that, if provided in the url, the page number had been correctly applied regardless of this modification. Could you please look into it and tell if I am missing some point or if indeed there was a bug, include a fix in some next release?

**Comment by dimitvassilev** [comment]
One more question - is there a way provisioned to paginate the related resources linkages under the 'relationships' key and accordingly include only resources within the current pagination when requested for inclusion?
Thanks!

**Comment by lindyhopchris** [comment]
@dimitvassilev apologies for slow reply, I've been on holiday and only back at work today.

Thanks for reporting this as it is definitely a bug. I'll see when I have time to fix it this week.
