### ISSUE TITLE
Invalid Relationship: Don't know what to do

### ISSUE THREAD

**Issue by dennismende** [cloudcreativity/laravel-json-api#132]
Hi,

I have a resource type called 'questionnaire-templates'.

I get the error 'Resource type 'questionnaire-templates' is not recognised.' when it's in the relationships. 

I have absolutely no idea what I need to do to fix this issue. Where do I define resource types?

**Comment by dimitvassilev** [comment]
You have to register all the resource types as keys with their corresponding class(es) as values in an array under the 'resources' key in the config file (e.g. json-api-default.php or json-api-v1.php, see [http://laravel-json-api.readthedocs.io/en/latest/api/#defining-resources](url)).

**Comment by dennismende** [comment]
Thanks
