### ISSUE TITLE
Question: Where is the fields parameter applied?

### ISSUE THREAD

**Issue by peripteraptos** [cloudcreativity/laravel-json-api#136]
Heyhey,
i have an eloquent accessor for one of my models, which does a lot of stuff.
it is like this in MyModel.php
`public function getCustomAttribute(){
#do a lot of stuff
}`

when i request /api/v1/my-model, i dont want the custom attribute to be included. That's why i make the request like this, using the fields paramenter: 
`get /api/v1/my-model?fields[my-model]=name,status,text`
it works somehow, but i figured out, that even if i don't include my time consuming custom attribute there, it seems to query it, because it takes the same amount of time.
On the other hand, it is much faster when i completly remove it from my `$attributes` but than i can't get it at the points where i need it.

Does anyone has an idea?

**Comment by dimitvassilev** [comment]
Hi,
If 'custom_attribute' has been added to the $appends array in MyModel, it is probably calculated because of that.

**Comment by lindyhopchris** [comment]
The fields parameter will be applied by the underlying `neomerx/json-api` package, that does the encoding. Unfortunately I think it will be calling `getAttributes()` on the schema and then only including the array keys that are specified by the fields param - but that means your custom attribute will always be calculated.

I'll create an issue in the neomerx package.

**Comment by lindyhopchris** [comment]
Just looking at this again.

In theory this would have been solved by upgrading to v2 of the neomerx package, but v3 (the current version) seems to have removed the solution in the above linked issue.

For the moment I'll add this issue to the `2.0` milestone of this package, and I'll review again when I get to that milestone (because at that milestone I'll have to make a call as to whether we update to neomerx v2 or v3).

**Comment by lindyhopchris** [comment]
Closing this as conditional attributes in the new package `laravel-json-api/laravel` solve this problem. See https://laraveljsonapi.io/docs/1.0/resources/attributes.html#conditional-attributes
