### ISSUE TITLE
getFillable() in EloquentHydrator is not reliable

### ISSUE THREAD

**Issue by dimitvassilev** [cloudcreativity/laravel-json-api#137]
Hi,
If I may make a suggestion for enhancement: in
[this line](https://github.com/cloudcreativity/laravel-json-api/blob/145fcb2511dc820c13b28e9024b4f1814632693c/src/Hydrator/EloquentHydrator.php#L181) in the EloquentHydrator the getFillable() may return an empty array in case the 'fillability' of attributes has been specified in the model via the $guarded instead of the $fillable attribute. It might be better to consider 'fillability' from both $fillable and $guarded, e.g. filter through all model attributes with the model's isFillable($key) method.
BR!

**Comment by lindyhopchris** [comment]
Hi! Thanks for this. Makes sense, but I'll have to look into it further. Definitely something to sort out before v1.

**Comment by lindyhopchris** [comment]
The 1.0 branch (develop) is now using `isFillable`.
