### ISSUE TITLE
Question: How to register adapter?

### ISSUE THREAD

**Issue by earllapura** [cloudcreativity/laravel-json-api#139]
I have the following configuration:
```
    'resources' => [
        //...
        'plantillas' => 'App\Plantilla',
        'salary-grades' => 'App\SalaryGrade',
    ],
```
and a snippet of the route:
```
        $api->resource('plantillas', [
            'controller' => '\App\Http\Controllers\Api\PlantillaController',
            'only'       => ['index', 'create'],
            'has-one'    => 'salary-grade',
        ]);
```
I included the relationship in Plantillas\Hydrator
```
    protected $relationships = [
        'salary-grade',
    ];
```

And the relationship in Plantillas\Schema
```
    public function getRelationships($resource, $isPrimary, array $includeRelationships)
    {
        if (!$resource instanceof Plantilla) {
            throw new RuntimeException('Expecting a plantilla model.');
        }

        return [
            'salary-grade' => [
                self::SHOW_SELF => true,
                self::SHOW_RELATED => true,
                self::DATA => isset($includeRelationships['salary-grade']) ?
                    $resource->salaryGrade : $this->createBelongsToIdentity($resource, 'salaryGrade'),
            ],
        ];
    }
```
However, when I send a POST to plantilla route (using Behat) with the data as follows:
```
      {
          "data":
          {
              "type": "plantilla",
              "attributes": {
                  "code": "CMP Tech 1"
              },
              "relationships": {
                  "salary-grade": {
                      "data": {
                          "type": "salary-grade",
                          "id": "1"
                      }
                  }
              }
          }
      }
```
I get the error that says: `CloudCreativity\JsonApi\Exceptions\RuntimeException: No adapter for resource type: salary-grade in file C:\xampp\htdocs\path-to-project\vendor\cloudcreativity\json-api\src\Store\Store.php on line 137`

Do I have to register the adaptors manually? I already have the Adapter, Schema and Hydrator for SalaryGrades:
```
//App\JsonApi\Session\SalaryGrades
    /**
     * @var array
     */
    protected $attributes = ['level', 'amount'];

    /**
     * @var array
     */
    protected $relationships = [
        'plantillas',
    ];
```
```
//App\JsonApi\Session\SalaryGrades\Adapter
    /**
     * Adapter constructor.
     *
     * @param StandardStrategy $paging
     */
    public function __construct(StandardStrategy $paging)
    {
        parent::__construct(new SalaryGrade(), $paging);
    }

    /**
     * @inheritdoc
     */
    protected function filter(Builder $builder, Collection $filters)
    {
        //
    }

    /**
     * @inheritdoc
     */
    protected function isSearchOne(Collection $filters)
    {
        return $filters->has('code');
    }
```

**Comment by lindyhopchris** [comment]
What's the value of the `namespace` and `by-resource` settings in your API config?

**Comment by earllapura** [comment]
My settings for `namespace` and `by-resource` are:
```
    'namespace' => 'App\JsonApi\Session',
    'by-resource' => true,
```

**Comment by lindyhopchris** [comment]
Ah, just spotted there's a problem with your request:

```json
                  "salary-grade": {
                      "data": {
                          "type": "salary-grade",
                          "id": "1"
                      }
                  }
```json

The `type` should be `salary-grades` as that's the resource type name. Saying that though you should be getting a 4xx response for that.

What happens if you change that in the request?

**Comment by earllapura** [comment]
Thanks! It passed. It seems that I have been inconsistent with the naming of the resource type, as I got used to the plural-singular "resolution" in Laravel in `belongsTo` relationships. JSON API says otherwise:

> Note: This spec is agnostic about inflection rules, so the value of type can be either plural or singular. However, the same value should be used consistently throughout an implementation.

Thanks for the help!

**Comment by earllapura** [comment]
IMHO, when you follow best practices for URL design, you will tend to use plural names of resource type if you use the package.

**Comment by lindyhopchris** [comment]
Yeah I'd agree plural makes more sense. The reason it mattered though in your case is because in the API config you register the resource type as `salary-grades` in the `resources` config, which is why it doesn't recognise the singular in the `type` key.

I'm reopening this because I need to add a test to ensure the API returns a `4xx` response in this scenario - you should have got one with a JSON API error object that had a source pointer to `/data/relationships/salary-grade/data/type` which would have made this a lot easier to track down what the problem was.

**Comment by lindyhopchris** [comment]
@earllapura I added a test for this and it seems to be working absolutely fine.

I think what might have happened in your scenario is if you hadn't created a `Validators` class for your `plantillas` resources then the inbound JSON API data would not have been validated. So it's worth generating one of those to ensure validation occurs.
