### ISSUE TITLE
Filtering, paging, etc.

### ISSUE THREAD

**Issue by dimitvassilev** [cloudcreativity/laravel-json-api#140]
Hi,
I have stumbled accross some packages, based on laravel, that implement the json api specification regarding query parameters. I haven't played with them, so I can't really say to what extent they do that and if the usage is compatible with this package, and it probably is undesirable to bring additional dependencies to the library anyway, but I thought that they at least could give some implementation ideas and save you some time, knowing that these are features currently on your to-do list:
- [spatie/laravel-query-builder](https://github.com/spatie/laravel-query-builder);
- [spatie/laravel-json-api-paginate](https://github.com/spatie/laravel-json-api-paginate).

Best regards!

**Comment by lindyhopchris** [comment]
Thanks! Will take a look at those.

We do know what our implementation is going to be, it's just having the time to complete it all that is holding me back at the moment... difficult to make the time when you've got pressing deadlines on projects. I have however allocated some time towards the end of next week to push things along a bit.

**Comment by dimitvassilev** [comment]
No, thank You! I never doubted you do, it is a truly amazing job you are doing - it's just that I impulsively thought 'hey, this might be relevant!' and brought it to your attention without stopping to think attention needs precious time. Thanks again!

**Comment by lindyhopchris** [comment]
Closing this as I've taken a look at the linked packages. Look interesting but think where I'm heading with this package covers all of this off.
