### ISSUE TITLE
Question: Is there a way to put limit includes to single resource requests

### ISSUE THREAD

**Issue by spawnia** [cloudcreativity/laravel-json-api#141]
What i would like to achieve is that i do not get all the includes when calling the endpoint for the collection of resources, but include more detailed information when accessing a single resource. For example:

### /posts

````json
{  
   "data":[  
      {  
         "type":"posts",
         "id":"1",
         "attributes":{  
            "name":"My Post"
         },
         "relationships":{  
            "author":{  
               "data":{  
                  "type":"authors",
                  "id":"1"
               },
               "links":{  
                  "related":"http://blog.com/api/v1/posts/1/author"
               }
            }
         },
         "links":{  
            "self":"http://blog.com/api/v1/posts/1"
         }
      }
   ]
}
````
### /posts/1
````json
{  
   "data":{  
      "type":"posts",
      "id":"1",
      "attributes":{  
         "name":"My Post"
      },
      "relationships":{  
         "author":{  
            "data":{  
               "type":"authors",
               "id":"1"
            },
            "links":{  
               "related":"http://blog.com/api/v1/posts/1/author"
            }
         }
      },
      "links":{  
         "self":"http://blog.com/api/v1/posts/1"
      }
   },
   "included":[  
      {  
         "type":"authors",
         "id":"1",
         "attributes":{  
            "name":"My Author"
         }
      }
   ]
}
````

I would like to avoid using the include parameters. I tried getting the information about what kind of call was made in my `getRelationships()` method, but did not get anything.

If it is not easily possible, i can use include for that and you can simply close the issue! Thanks

**Comment by lindyhopchris** [comment]
Hi!

On your `posts` schema:

```php
public function getIncludePaths()
{
    if (!$request = json_api_request()) {
        return []; // no JSON API request, serializing the resource outside of an HTTP request.
    }

    return $request->getResourceId() ? ['author'] : [];
}
```

The `getIncludePaths` method on the schema returns the default include paths to use if the client has not provided any. (It will be ignored if the client has specified the include paths.)

The above code gets the JSON API request (if there is one) and detects if a resource id is in the request. Note that there would not be a request if the schema is being used outside of an HTTP request, e.g. serializing a resource for a queued broadcasting job.

I haven't tested the above code but believe it will work.

I think this answers your question - let me know!

**Comment by spawnia** [comment]
Hey, just got back to the project and tested your code - it works beautifully, thank you.

Having the `json_api_request()` helper available opens up so much more possibilities, great to know!
