### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by ehsan5** [cloudcreativity/laravel-json-api#145]
Hi everyone,
I want to write login and register based on jsonapi.
Anyone can help me by example?

**Comment by SirLamer** [comment]
I assume that you are talking about performing login and register actions to access your web app in the browser, not just authentication to query the API itself.

You probably shouldn't do that, authentication is special stuff and deserves separate consideration. "Separation of concerns" also applies here, where you don't want to mix these things up.

If you want, look up "OAuth2" and use that to do your login, which also allows you to integrate with Facebook and other platforms easily.

**Comment by lindyhopchris** [comment]
Our approach is not to put the sign-in to an API into the JSON API format, because an API token is not really a "resource" so doesn't fit well in the pattern.

In terms of registering a user, we just use a create `users` JSON API request, i.e. `POST /users`. We set it up so a create request for the user is expecting a `password` attribute, that obviously we do not show when encoding the user (i.e. it is not included in the Schema for the user model).

In another application the `users` resource is a *public* view of the user model. So we use a `user-accounts` resource which the signed in user can only access their own resource and we use create (POST) to register a new user and update (PATCH) requests to modify the user's account e.g. change a password.

**Comment by ehsan5** [comment]
thank you for replay,
this is my login controller,Maybe useful for others,
`public function login(Request $request)
    {
        try {
        	// Validation Data
        	$validData = $this->validate($request, [
        			'email' => 'required|email|max:255|exists:users',
        			'password' => 'required|min:6'
        	]);
        }catch (\Exception $e)
        {
            if($e instanceof ValidationException)
            {
                foreach ($e->errors() as $source => $error)
                {
                    foreach ($error as $errorDetail)
                    {
                        $errorObj = new \stdClass();
                        $errorObj->status = 400;
                        $errorObj->code = 400;
                        $errorObj->title= "error";
                        $errorObj->detail= $errorDetail;
                        $errorObj->source=new \stdClass();
                        $errorObj->source->parameter= $source;
                        $errors[] = $errorObj;
                    }
                }
                return response()
                ->json([
                    "errors" => $errors
                ],400,["Content-Type"=> "application/vnd.api+json"]);
            }
            
           throw new \Exception(); 
        }
        $result = auth()->attempt($validData);
        if(!$result)
        {
            $errorObj = new \stdClass();
            $errorObj->status = 400;
            $errorObj->code = 400;
            $errorObj->title= "error";
            $errorObj->detail= "login failer";
            $errors[] = $errorObj;
            return response()
            ->json([
                "errors" => $errors
            ],400,["Content-Type"=> "application/vnd.api+json"]);
        }
            //throw new AuthFailedException();
             $token = auth()->user()->createToken('Token')->accessToken;
           
            return response()->json(
            		[
            				'token' =>$token
            		]
            		);
            //return new AuthResource(auth()->user(),$token);
            
            
    }

**Comment by lindyhopchris** [comment]
I think probably what would help here is if I add authentication (using Laravel Passport) to the demo app, plus user registration. I'll close this issue here and create an issue in the demo app to add that.
