### ISSUE TITLE
Question: Best method for binding relationship data in Schema?

### ISSUE THREAD

**Issue by SirLamer** [cloudcreativity/laravel-json-api#149]
In the demo program, there are three different methods used for binding relationships. A good example is here: 
https://github.com/cloudcreativity/demo-laravel-json-api/blob/5.5/app/JsonApi/Posts/Schema.php

```php
    public function getRelationships($resource, $isPrimary, array $includeRelationships)
    {
        if (!$resource instanceof Post) {
            throw new RuntimeException('Expecting a post model.');
        }
        return [
            'author' => [
                self::SHOW_SELF => true,
                self::SHOW_RELATED => true,
                self::DATA => isset($includeRelationships['author']) ?
                    $resource->author : $this->createBelongsToIdentity($resource, 'author'),
            ],
            'comments' => [
                self::SHOW_SELF => true,
                self::SHOW_RELATED => true,
                self::DATA => $resource->comments,
            ],
            'tags' => [
                self::SHOW_SELF => true,
                self::SHOW_RELATED => true,
                self::DATA => function () use ($resource) {
                    return $resource->tags;
                },
            ],
        ];
    }
```

I understand that the "createBelongsToIdentity" method is a performance optimization for when the relationship data record is not being included, and that it can only be used with a "belongsTo" Laravel relationship.

For other cases, is there a material difference between binding the relationship via a function return, vs. just a direct-reference to the Laravel relationship pointer? I prefer the brevity of no function return unless there is some reason for it.

**Comment by lindyhopchris** [comment]
Yes the reason for the function return is that it is *lazy*. The function is only invoked if the data is definitely going to be included in the encoded response. In the example above if the client is using sparse fieldsets and does not include `tags` in the listed fieldsets it wants, the tags relationship data will not be included, and as the return is wrapped in a function the database query won't be executed.

So it's more verbose but if you're worried about performance and you expect your clients to use sparse fieldsets, it's worth the extra code.

**Comment by lindyhopchris** [comment]
Closing this but feel free to re-open if you've got any other questions!
