### ISSUE TITLE
EloquentController read method not being called

### ISSUE THREAD

**Issue by wtmenten** [cloudcreativity/laravel-json-api#151]
First, the obligatory thank you for developing this package. I've been using it at work for the past few months and it has made API dev such a breeze. However I have encountered some odd behavior between index and read calls which requires some assistance.

Currently, I am using version 0.11 of the package. So perhaps this was fixed in v0.12 or in the upcoming v1.0 release. If this is the case just let me know and I will work on upgrading.

We have a multi database design and use Auth to switch the database configs at run-time. As such, I need the auth middleware to run prior to jsonapi booting the adapter & etc. This is the case when making calls to the index endpoints, however, in the case of read endpoint requests the package uses the adapter directly to fetch the record while booting up the jsonAPI and then fires off the controller's 'read' method.

This should be observable with a breakpoint in the EloquentController.

Let me know if you need more clarity.

**Comment by wtmenten** [comment]
Upon more inspection I found that my setup for guest Auth was causing the api to boot before auth. You can disregard this ticket.

**Comment by lindyhopchris** [comment]
No problem, glad you found the solution. I'm hoping to put in more control over where middleware executes in the stack in the future but haven't totally formulated a plan on how to do this yet!
