### ISSUE TITLE
what is the best practice for change create action for EloquentController

### ISSUE THREAD

**Issue by ngkarkeong** [cloudcreativity/laravel-json-api#152]
The situation is Eloquent need to have custom code in create action,
what if the best way to do override the base code for create action?
Base on the demo/PostsController(eloquent), is there a way to code it without breaking the ecapsulation?
The example using in demo/SitesController(non-eloquent). Easy to customize, but lost all others works.

Thanks for taking to help.

**Comment by lindyhopchris** [comment]
Hi! You should just be able to overload the `create()` method as long as you keep the signature the same. If that doesn't answer your question, maybe you could provide a bit more details as to what you're trying to do in the create method (i.e. what your custom code would be) and then I can provide a more specific answer!

**Comment by ngkarkeong** [comment]
My situation will be Let say send an email to user .after he signed up to become a member. Right after the model persistent in to data I send an email. How to make that happen?

**Comment by lindyhopchris** [comment]
The Eloquent controller calls the `created` method on the controller if it is implemented, so just add that to your controller. It will receive the model as the first argument.

**Comment by ngkarkeong** [comment]
yes, that is the idea in my my mind. however i tired.

public function created($resource, array $links = [], $meta = null, array $headers = [])
    {
        //custom code
        return $this->getCreatedResponse($resource, $links, $meta, $headers);
    }

and this

public function created($resource, array $links = [], $meta = null, array $headers = [])
    {
        //custom code
    }

they both give me error
{
    "errors": [
        {
            "status": "500",
            "title": "Internal Server Error"
        }
    ]
}

**Comment by lindyhopchris** [comment]
So the `created` method is just a hook for you to do things like dispatching events, jobs etc or in your case sending an email. You don't need to return anything from it, and the error you're getting is because you're type-hinting arguments that don't get passed in.

If all you want to do is send an email, it would look like this:

```php
protected function created($model)
{
  \Mail::send(new WelcomeUserMail($model));
}
```

**Comment by ngkarkeong** [comment]
Thanks, that solve the problem.
how about at the situation you have to add custom code before create the record.
for example, if it is a payment.
you have to verify is that a valid token before you create the record.
where should i hook the code?

beside, i would love to contribute into this project( on demo, doc ), i have never work on github nor opensource, how can i start?

**Comment by lindyhopchris** [comment]
So the Eloquent controller has `creating`, `created`, `updating`, `updated`, `saving`,`saved`, `deleting` and `deleted` hooks. I.e. just implement any of those methods that you need and they will be invoked.

In terms of helping, at the moment we're doing development on the `develop` branch and trying to get everything done that needs to be done to get to `1.0.0`. If you wanted to help you'd need to choose one of the issues on the 1.0 milestone and have a go at submitting a PR that solves it. This might not be straightforward so if you are thinking of taking one of the issues, comment on that issue and I can give you some suggestions as to how to approach it.

**Comment by ngkarkeong** [comment]
In this example, i tried couples of way to catch the error. however, i still cant figure any way to return to error.

`use ErrorsAwareTrait;

    public function creating($booking)
    {
        try{
            \Stripe\Stripe::setApiKey(env('STRIPE_SECRET_KEY'));

            $customer = \Stripe\Customer::create(array(
                'email' => $booking->email,
                'source'  => $booking->token
            ));

            $charge = \Stripe\Charge::create(array(
                'customer' => $customer->id,
                'amount'   => 3500,
                'currency' => 'usd'
            ));
        } catch(Card $e)
        {
            $this->reply()->errors(Error::create([
                'status' => 422,
                'title' => 'Payment Error',
                'detail' => 'somthing is wrong',
            ]));
        }

    }`

**Comment by lindyhopchris** [comment]
@ngkarkeong just throw a JSON API exception - `Neomerx\JsonApi\Exceptions\JsonApiException`.

So in your catch block, do:

```php
catch(Card $e) {
    throw new JsonApiException(Error::create([
        'status' => 422
        // ...
    ]);
}
``
