### ISSUE TITLE
Counting relationships?

### ISSUE THREAD

**Issue by fisharebest** [cloudcreativity/laravel-json-api#166]
Laravel provides support to add [counts of relations](https://laravel.com/docs/5.6/eloquent-relationships#counting-related-models) to a model.  e.g.

```php
$posts = App\Post::withCount('comments')->get();

foreach ($posts as $post) {
    echo $post->comments_count;
}
```

Is there a way to incorporate `$model->withCount(...)` into a laravel-json-api request?

**Comment by lindyhopchris** [comment]
Hi! The `include` parameter is for inclusion of related resources, which a count is not. I.e. it's for including the related comments themselves, not the count.

It might be best including this in relationship meta? Or just including it as an attribute? Do you have a preference?

**Comment by fisharebest** [comment]
For my application, it would be simplest just to have it as an extra attribute.

But it's only needed on a few requests, so it needs to be selectable in the request.

**Comment by fisharebest** [comment]
FYI, I've got this working by extending `EloquentAdapter` and adding the following method:

```php
    protected function with(Builder $query, Collection $includePaths): void
    {
        foreach ($includePaths->toArray() as $include_path) {
            if (ends_with($include_path, '_count')) {
                // Count
                $query->withCount(str_replace_last('_count', '', $include_path));
            } else {
                // Eager load
                $query->with($include_path);
            }
        }

        parent::with($query, $includePaths);
    }
```

I can now use `api/foo?include=bar_count` to give me a count of `bar` linked to `foo`.

(I think eager loading is automatic in 1.x, but I'm still using 0.x).

I fully appreciate your comment that I am abusing the `include` parameter, but I can't find a cleaner way to do this.

The only 'gotcha' I found was that `EloquentSchema::attributeKeys()` gets a list of attributes from `Model::getFillable()`, and so I needed to add `xxx_count` to the model's `$fillable` attribute - even though this attribute isn't actually fillable.

**Comment by dimitvassilev** [comment]
Hi, @fisharebest, 
You might want to use the sparse fieldsets specification [http://jsonapi.org/format/#fetching-sparse-fieldsets](url), i.e. sth like api/foo?include=bar&fields[bar]=bar_count to make bar_count visible in the bar relation.

**Comment by fisharebest** [comment]
> And use a custom parameter to allow it to be included.

I guess there could be other meta data to include.  With a post, you may want both the number of comments and the date of the most recent.  So perhaps a more flexible parameter name along the lines of `includeMeta[comments.count,comments.latest]`

**Comment by lindyhopchris** [comment]
@fisharebest yes, definitely a good suggestion.

I've added this to the `1.1.0` milestone as it can be worked on post the `1.0.0` release.

**Comment by JeanLucEsser** [comment]
If I'm not mistaken, by the spec, query params must be camel cased, or prefixed by - or _.
http://jsonapi.org/format/#query-parameters

So includeMeta would work but count= would not.

Also, can I suggest using the same approach as with fields?
That is the type and then the attributes: 
`includeMeta[comments]=count,latest` (or just _meta[comments])

Another thing, I use the meta node in each included relationship to put the pivot table attributes.
Something akin to comments->meta->attributes->is-private if my Post-Comment pivot table has such an attribute.

Would be nice to use something similar for that:
`includePivotFields[comments]=is-private`  (or just _pivot-fields[comments])

What do you think?

-- JL

**Comment by dimitvassilev** [comment]
@JeanLucEsser I think you are mistaken about the spec - it only says that camel-casing is one of the recommended ways to specify multi-word parameters, the other (still only recommended) being by use of the - and _ characters. Neither prefix is required, nor the use of single-word parameters prohibitted.

**Comment by lindyhopchris** [comment]
Laravel 5.7.10 added a `loadCount` feature for Eloquent models:
https://laravel-news.com/laravel-5-7-10

When adding a count feature, would be good to also support this eager loading.

**Comment by webdobe** [comment]
So how do we do this?  Using sparse fields seem to do the count queries regardless if you include them in the fields query params.  Also, this was said to be added to the v1.1.0 milestone, but we are way past that.  Would be good to document this somewhere if we are able to do it.  Any info regarding this is appreciated!

**Comment by lindyhopchris** [comment]
@webdobe thanks for your comment. this is going to have to wait until the revamp, as I need to sort out the revamp first. Sorry, but maintaining an open source project I have to prioritise, and at the moment the revamp is needed to open the pathway to closing off a lot of these issues.

**Comment by lindyhopchris** [comment]
Closing in favour of implementing in the new package - `laravel-json-api/laravel`. See the issue linked above to track progress in that package.
