### ISSUE TITLE
Remote API client resource deserialisation

### ISSUE THREAD

**Issue by Robindfuller** [cloudcreativity/laravel-json-api#170]
How do I deserialise the response from 

    $client->read('posts', '1')->getDocument()->getResource();

...in to a Plain Old PHP Object including included relationships? 

Same with 

    $client->index('posts');

I have my Entity classes and Hydrators for my entities but no idea how to implement it. Without the ability to deserialise, I might just as well use json_decode() on my guzzle client response.

**Comment by lindyhopchris** [comment]
Closing this because as per #388 there is a JSON API client package out there that looks good. Our package will just focus on doing the *server* rather than *client* side.
