### ISSUE TITLE
Cache API config

### ISSUE THREAD

**Issue by lindyhopchris** [cloudcreativity/laravel-json-api#171]
Need to investigate whether caching API config, especially the resolver resolutions of class names, would give better performance.

If it does, adding `json-api:cache` and `json-api:clear` Artisan commands would allow this to be done on deployment in the same way as `config:cache`.

**Comment by Wizofgoz** [comment]
@lindyhopchris The stock Laravel `php artisan route:cache` command seems to work for caching the route definitions. Is there something else you are looking at tackling with this?

**Comment by lindyhopchris** [comment]
the idea is to investigate whether creating a cached version of the API config along with the resolution of namespaces/class names brings any performance improvement. not sure if it will but think it's worth investigating at some point!

**Comment by lindyhopchris** [comment]
Moving this to the 2.0 milestone as we're going to sort out the handling of API config for that. Not sure there will be any need to cache an API anymore, but will revisit once the config is refactored and decide then.

**Comment by lindyhopchris** [comment]
Not required in the new package, so closing this.
