### ISSUE TITLE
Extending relation classes

### ISSUE THREAD

**Issue by flofloflo** [cloudcreativity/laravel-json-api#172]
I'm currently trying to extend the `CloudCreativity\LaravelJsonApi\Eloquent\HasMany` class because I want to add some functionality to the `update`-method.

My problem is that the used methods `findRelated`, `sync` and `getWritableRelation` are scoped `private` and so they can't be called from a derived class.

Is there a special reason you used `private` instead of `protected` as visibility for your methods?

**Comment by lindyhopchris** [comment]
Hi! The main use for `private` is just to keep the API surface as low as possible. I'm happy to make them `protected` if they definitely need to be overridden.

It would be good to know what you're trying to do because if it is a common use case I'd prefer to add in support for your use rather than making them `protected`. Can you explain what you're trying to do? If it isn't something that I'd put into the package by default then I'll be happy to make the methods `protected`.

**Comment by flofloflo** [comment]
I'm trying to add some stuff to audit the changes to BelongsToMany relationships. 
So basically this is my overwritten `update` method:
```php
public function update($record, RelationshipInterface $relationship, EncodingParametersInterface $parameters)
    {
        $related = $this->findRelated($record, $relationship);
        $relation = $this->getWritableRelation($record);

        if ($relation instanceof Relations\BelongsToMany) {
            // capture old state of the relationship
            $oldValues = $relation->get();
            // sync the changes
            $relation->sync($related);
            // capture new state of the n:m relationship
            $newValues = $relation->get();
            // if the model is auditable...
            if (method_exists($record, 'saveSyncAudit')) {
                // ... save the changes in the audit table
                $record->saveSyncAudit($this->field, $relation, $oldValues, $newValues);
            }
            return;
        } else {
            $this->sync($relation, $record->{$this->key}, $related);
        }
    }
```
The problem is that I can't call the `private` methods from my `update` method (unless I copy them into my class -> ugly).

**Comment by lindyhopchris** [comment]
Ah, ok yes can see this would be useful. I'm working on this package at some point over the weekend, so I'll make the methods protected then.

**Comment by flofloflo** [comment]
Very cool, thank you!

**Comment by flofloflo** [comment]
No problem!
I could also send a pull request for this, if it helps you.

**Comment by lindyhopchris** [comment]
Would normally say a PR would be good, but there's a todo in that class about splitting out the `has-many-through` into its own relation, so I'm going to do that at the same time as that might affect some of the current private methods on the class.

**Comment by lindyhopchris** [comment]
@flofloflo I've pushed this to `develop`. I'm not sure when I'm going to do the next tag, but you can use it in the meantime by doing `composer require cloudcreativity/laravel-json-api:dev-develop`.

I'll close this issue but feel free to re-open if you encounter any problems.

**Comment by Nizari** [comment]
Awesome, how hard you're going at it this past time. Can't wait for the finished 1.0.0 version! Thank you!
