### ISSUE TITLE
Unrecognised relationship name: 

### ISSUE THREAD

**Issue by Robindfuller** [cloudcreativity/laravel-json-api#177]
Hi

I've just upgraded from 0.12 to 1.0.0-alpha.1 and when attempting to retrieve a relationship

    http://localhost:8000/api/v1/posts/1/user

I get the following runtime exception

   "Unrecognised relationship name: "

Visiting http://localhost:8000/api/v1/posts/1 and http://localhost:8000/api/v1/posts gives me the correct json output including a list of the relationships available. However, visiting any of their urls just fails with the same exception.

Any ideas?

Here is the first part of the stack trace

    CloudCreativity\LaravelJsonApi\Exceptions\RuntimeException: Unrecognised relationship name:  in file /Users/bob/Documents/Projects/my-app/backend/vendor/cloudcreativity/laravel-json-api/src/Adapter/AbstractResourceAdapter.php on line 134
    Stack trace:
    1. CloudCreativity\LaravelJsonApi\Exceptions\RuntimeException-&gt;() /Users/bob/Documents/Projects/my-app/backend/vendor/cloudcreativity/laravel-json-api/src/Adapter/AbstractResourceAdapter.php:134
    2. CloudCreativity\LaravelJsonApi\Adapter\AbstractResourceAdapter-&gt;related() /Users/bob/Documents/Projects/my-app/backend/vendor/cloudcreativity/laravel-json-api/src/Store/Store.php:144
    3. CloudCreativity\LaravelJsonApi\Store\Store-&gt;queryRelated() /Users/bob/Documents/Projects/my-app/backend/vendor/cloudcreativity/laravel-json-api/src/Http/Controllers/JsonApiController.php:166
    4. CloudCreativity\LaravelJsonApi\Http\Controllers\JsonApiController-&gt;readRelatedResource() /Users/bob/Documents/Projects/my-app/backend/vendor/laravel/framework/src/Illuminate/Routing/Controller.php:54
    5. call_user_func_array() /Users/bob/Documents/Projects/my-app/backend/vendor/laravel/framework/src/Illuminate/Routing/Controller.php:54

    ...

**Comment by lindyhopchris** [comment]
Have you implemented a `user()` method on your adapter as per this:
http://laravel-json-api.readthedocs.io/en/latest/basics/adapters/#relationships

**Comment by Robindfuller** [comment]
Nope. I have now and it works.

Thanks!
