### ISSUE TITLE
Return value from hydrate not used in EloquentController

### ISSUE THREAD

**Issue by stfnndrsn** [cloudcreativity/laravel-json-api#18]
Is it supposed that the return value isn't used in EloquentController->hydrate()?

See: https://github.com/cloudcreativity/laravel-json-api/blob/master/src/Http/Controllers/EloquentController.php#L233

**Comment by lindyhopchris** [comment]
Good spot! The hydrator interface specifies that the object should be returned, so the Eloquent controller should be using the return value.

Thanks for the PR - I'll be able to merge and tag it later this evening (UK time)
