### ISSUE TITLE
Default controller doesn't work

### ISSUE THREAD

**Issue by Naxon** [cloudcreativity/laravel-json-api#180]
Hi,

I installed the package, followed the installation instructions, but for some reason the default controller isn't being resolved.

my `RouteServiceProvider::mapApiRoutes()` looks like this:
```
protected $apiNamespace = 'App\Api';
```
```
    protected function mapApiRoutes()
    {
        Route::middleware('api')
             ->namespace($this->apiNamespace)
             ->group(base_path('routes/api.php'));
    } 
```
routes/api.php:
```
JsonApi::register('v1', ['namespace' => 'V1'], function(ApiGroup $Api, Registrar $Router) {
    $Api->resource('teams');
});
```

I created a new `teams` resource and registered it in the config file `json-api-v1.php`:
```
    'resources' => [
        'teams' => Team::class,
    ],
```

And I still get this error:

> Class App\Api\V1\TeamsController does not exist

Any idea why?

**Comment by lindyhopchris** [comment]
Are you definitely on the latest release? If you do `composer show cloudcreativity/laravel-json-api` it will give you the version information for the version you have installed.

**Comment by lindyhopchris** [comment]
I suspect (but you might need to confirm) that `composer require cloudcreativity/laravel-json-api` will install `0.12` instead of the `1.0.0-alpha.2` release. In which case I need to update the installation docs to specify the alpha release.
