### ISSUE TITLE
Question: Inverse keyword in route registration

### ISSUE THREAD

**Issue by dimitvassilev** [cloudcreativity/laravel-json-api#190]
Hi Chris,
Would you please explain the use of 'inverse' as a parameter key for route registration?
Is it to specify that the respective resource called via the route should use the schema/adapter classes for the resource type provided as its value?
I found it used here https://github.com/cloudcreativity/laravel-json-api/blob/0a98b07adb7aa243b23460d9676c6c63861eec77/tests/dummy/routes/json-api.php#L39 and, since I could really use such a feature, was wondering if I might be misenterpreting the purpose of the keyword (couldn't find anything about it in the docs).

**Comment by lindyhopchris** [comment]
Ah looks like I haven't documented that.

It needs to know the inverse resource type for the relationship as it has to use the validators for the inverse resource type to validate the query parameters on a relationship request.

**Comment by lindyhopchris** [comment]
It is currently explained in the doc block where it is used:
https://github.com/cloudcreativity/laravel-json-api/blob/master/src/Http/Requests/ValidatedRequest.php#L210-L233

**Comment by dimitvassilev** [comment]
Thank you!
