### ISSUE TITLE
change post parameters

### ISSUE THREAD

**Issue by ehsan5** [cloudcreativity/laravel-json-api#197]
Hello, in create method of controllers I want change posted parameter.how I can change?
I mean I want change attributes of $request before hydrate

    public function create(RequestInterface $request)
    {
//change 
    }

this code do not work
$request->getDocument()->getResource()->getAttributes()->set("local_random_payment",strtoupper(str_random(15)));

**Comment by lindyhopchris** [comment]
It's an abstract method in the abstract adapter class.

**Comment by lindyhopchris** [comment]
Closing this as I think I've answered the question! Feel free to re-open if needed.
