### ISSUE TITLE
ValidatedRequest acquires first Request object which makes impossible to perform multiple different GET queries in Tests

### ISSUE THREAD

**Issue by tekord** [cloudcreativity/laravel-json-api#206]
Test method:

```
	public function testAvailability() {
		$response1 = $this->get('/api/v1/users');
		$response1->assertStatus(Response::HTTP_OK);

		$response2 = $this->get('/api/v1/candidates');
		$response2->assertStatus(Response::HTTP_OK);
	}
```

Both response1 and response2 returns user list which is not expected. Response2 must return candidate list.

I walked by stack trace. For `response1` the `$router` parameter in `ControllerDispatcher::dispatch` method has `uri = "api/v1/users"`. For `response2` it has `uri = "api/v1/candidates"`. But when program goes to `JsonApiController::index`, the `$request` parameter contains nested request object with `$request->request->request->requestUri = "/api/v1/users"`.

**Comment by tekord** [comment]
Found the reason in `\CloudCreativity\LaravelJsonApi\ServiceProvider::bindInboundRequest` method:

```
   protected function bindInboundRequest()
    {
        $this->app->singleton(RequestInterface::class, IlluminateRequest::class); // IT IS SINGLETON
        $this->app->alias(RequestInterface::class, 'json-api.request');
```

Changed to 'bind' and it solved my problem.

**Comment by tekord** [comment]
Hm, seems like singleton is used for performance reason. Without singleton the IlluminateRequest object instantiated 5 times to 1 request

**Comment by tekord** [comment]
Workaround is rebind classes in startUp method

```
$this->app->bind(RequestInterface::class, IlluminateRequest::class);
```

**Comment by X-Coder264** [comment]
The framework boots only once per test so you should make only one request per test. This is not a bug or issue of this package nor it's an issue of the framework itself. See https://github.com/laravel/framework/issues/23996 and https://github.com/laravel/framework/issues/24155 etc.

**Comment by tekord** [comment]
Thanks! This issue can be closed.

**Comment by lindyhopchris** [comment]
Yes, this is a problem with your test rather than a bug in this package. In a *real* HTTP request, the application is booted and torn down in the one request. Therefore tests that run multiple requests in one test are not realistic and risk state bleeding from one request to the next, which would not be the case for real HTTP requests.
