### ISSUE TITLE
Binding generic adapter isn't working

### ISSUE THREAD

**Issue by TomBrouwer** [cloudcreativity/laravel-json-api#207]
**EDIT:** I wanted to adjust it myself and make a pull request. But now I see that it is fixed in the aplha 4 release from yesterday. This issue can be closed.

Hi I try to bind a generic adapter, but it isn't work. It will tell me: "...\JsonApi\v1\Users\Adapter] is not a resource adapter". 

The code I use to bind (The '...' are replacing the App name in the begin of the namespace):
```
$this->app->bind('...\JsonApi\v1\Users\Adapter', function () {
     return new Adapter(new \...\Models\User(), null);
});
```

But it will not pass the create function in de src/Container.php
```
protected function create($className)
    {
        if (!class_exists($className)) {
            return null;
        }

        return $this->container->make($className);
}
```

It doesn't pass the class_exists function and return NULL. If I test to make the class, it will make the class. Maybe it can be checked with:
`$this->container->bound($className)`
instead of class_exists?

```
if (!class_exists($className) && !$this->container->bound($className)) {
     return null;
}
```

**Comment by lindyhopchris** [comment]
Hi @TomBrouwer - yes, this is exactly the change we released yesterday. Hope `1.0.0-alpha.4` solves your problem.
