### ISSUE TITLE
Class 'App\\Providers\\GenericAdapter' not found

### ISSUE THREAD

**Issue by abosami2000** [cloudcreativity/laravel-json-api#208]
Hi there,

I follow the documentation and I use the package version 1.0.0-alpha.3

but when I make a api request this error
```


{
    "message": "Class 'App\\Providers\\GenericAdapter' not found",
    "status_code": 500
}
```

also I want to ask if the package is ready to use in a production app?

**Comment by lindyhopchris** [comment]
Hi. That's just an example in the documentation, the generic adapter doesn't actually exist. You can read all about adapters here:
http://laravel-json-api.readthedocs.io/en/latest/basics/adapters/

We're using this package in three production apps.
