### ISSUE TITLE
Error on PATCH with fields with validation rule required

### ISSUE THREAD

**Issue by CrazyDevil** [cloudcreativity/laravel-json-api#209]
I have the following problem: If I want to update a resource via PATCH and do not specify a field set as required in validation rules, I get the following response:

```
{
    "errors": [
        {
            "status": "422",
            "title": "Invalid Attribute",
            "detail": "The name field is required.",
            "source": {
                "pointer": "/data/attributes/name"
            }
        }
    ]
}
```

One problem is that according to the JSON specification I don't have to specify the name field, because I don't want to change it.

Under Updating a Resource's Attributes you can read the the following sentence:

If a request does not include all of the attributes for a resource, the server MUST interpret the missing attributes as if they were included with their current values. The server MUST NOT interpret missing attributes as null values.

Is this an error, or do I have to pass required fields with their current values?

**Comment by lindyhopchris** [comment]
Hi!

The answer to this question is in the `Attributes > Rules` section of the docs here:
http://laravel-json-api.readthedocs.io/en/latest/basics/validators/
