### ISSUE TITLE
Eloquent model having 2 relations to another eloquent model

### ISSUE THREAD

**Issue by stefanws0** [cloudcreativity/laravel-json-api#213]
Hi I was wondering how you could implement 2 relations to the same model,

as an example take a package that's being send to and from a location. your package will have 2 properties (foreign_keys) named send_to_location_id and send_from_location_id. Is there any way how you can define this inside the routes and resource (Adapter, Schema & Validator)?

**Comment by lindyhopchris** [comment]
Hi. Yes, you would just represent it as two relations on your JSON API resource. E.g. your `packages` resource would have `send-to` and `send-from` relations (just as your Eloquent model would have two relations, one for each foreign key).

So in the routes and the adapter you would need to define two resource relationships. The docs have all the information on how to define relationships in routes, adapter etc.

**Comment by lindyhopchris** [comment]
Closing this as I think I've answered the question. Feel free to re-open if you're still stuck.
