### ISSUE TITLE
Question: use MongoDB

### ISSUE THREAD

**Issue by dklesev** [cloudcreativity/laravel-json-api#217]
I use this package within laravel: https://github.com/jenssegers/laravel-mongodb/

MongoDB uses `_id` (ObjectId). 

Index returns a valid response, like:

```json
{
    "data": [
        {
            "type": "users",
            "id": "5b6daa82714f8401613bce42",
            "attributes": {
                "created-at": "2018-08-10T15:08:50+00:00",
                "updated-at": "2018-08-10T15:08:50+00:00",
                "name": "Miss Cleora Mayert"
            },
            "links": {
                "self": "http://localhost/api/v1/users/5b6daa82714f8401613bce42"
            }
        },
...
```

Trying to set the `primaryKey` to `_id` in the corresponding model adapter seems not to work to get a valid read (resource object by id):

```json
{
    "errors": [
        {
            "status": "404",
            "title": "Not Found"
        }
    ]
}
```

<strike>Is it somehow possible to get it work with NoSQL/MongoDB?</strike>

**UPDATE:**

Solved this by overriding the getQualifiedKeyName method.

```php
protected $primaryKey = '_id';

    protected function getQualifiedKeyName()
    {
        return $this->getKeyName();
    }
```

**Comment by lindyhopchris** [comment]
Great, glad to hear you got it sorted!
