### ISSUE TITLE
Pagination in readRelatedResource

### ISSUE THREAD

**Issue by stfnndrsn** [cloudcreativity/laravel-json-api#22]
I can't figure out an way of doing pagination of a related resource.

``` php
EloquentController#readRelatedResource

        return $this
            ->reply()
            ->content($model->{$key});
```

**Comment by stfnndrsn** [comment]
I would gladly help out and update the functionality

**Comment by lindyhopchris** [comment]
Hi! Yes, I need to do some work on the related resources stuff so it is all taken care off out of the box, but haven't got round to that yet.

In the meantime the following should work if you're on the `0.5.x-dev` branch:

``` php
$paging = app(CloudCreativity\JsonApi\Contracts\Pagination\PaginatorInterface::class);
$page = app(CloudCreativity\LaravelJsonApi\Pagination\Page::class);

/** If the client has requested a page... */
if ($paging->getCurrentPage()) {
	$data = $model->{$key}()->paginate($paging->getPerPage());
} /** Client has not request a page */
else {
	$data = $model->{$key};
}

$page->setData($data);

return $this->reply()->content($page);
```

Let me know how you get on and obviously I can help more if you're still stuck. I'll probably be able to land proper related resource handling in `0.6` as I'm going to be tagging `0.5` very soon.

**Comment by lindyhopchris** [comment]
Actually, slight correction. The page object will only accept a Laravel paginator in its `setData` method, so it should be this:

``` php
$paging = app(CloudCreativity\JsonApi\Contracts\Pagination\PaginatorInterface::class);
$page = app(CloudCreativity\LaravelJsonApi\Pagination\Page::class);

/** If the client has requested a page... */
if ($paging->getCurrentPage()) {
	$data = $model->{$key}()->paginate($paging->getPerPage());
	$data = $page->setData($data);
} /** Client has not request a page */
else {
	$data = $model->{$key};
}

return $this->reply()->content($data);
```

**Comment by lindyhopchris** [comment]
On the 1.0 dev branch you can now paginate related resources.
