### ISSUE TITLE
Attempt to add existing resource to 'hasMany' relationship via POST method attempts database re-insertion, contrary to spec

### ISSUE THREAD

**Issue by SirLamer** [cloudcreativity/laravel-json-api#222]
Testing with laravel-json-api v1.0.0-beta.2 and Laravel v5.5

From JSON API spec here:
http://jsonapi.org/format/#crud-updating-to-many-relationships
```
If a client makes a POST request to a URL from a relationship link, the server MUST add the specified members to the relationship unless they are already present. If a given type and id is already in the relationship, the server MUST NOT add it again.

Note: This matches the semantics of databases that use foreign keys for has-many relationships. Document-based storage should check the has-many relationship before appending to avoid duplicates.

If all of the specified resources can be added to, or are already present in, the relationship then the server MUST return a successful response.

Note: This approach ensures that a request is successful if the server’s state matches the requested state, and helps avoid pointless race conditions caused by multiple clients making the same changes to a relationship.
```

When trying to add a child model to a 'hasMany' relationship where that child is already a member of the relationship, the API should return a "SUCCESS" response and behave as though the relationship addition was successful. This implies that the API software must first perform a check to see if that child is already a relationship member. This appears to not be happening, and as a result the item is added to the relationship again. A well-designed database should be enforcing a 'UNIQUE' requirement on the database-level, which would generate an error and return a 500 Internal Server Error response. Absent of that, the item would be added to the database again and report success but will have corrupted the relationship with duplicate membership records for one item.

**Comment by lindyhopchris** [comment]
Will add some test scenarios for this. Internally I'm just using the Laravel methods on the relationship to update it, so it's probable that those don't work in the way that the JSON API spec envisages... so will have to write something to make sure only new ids are pushed into the relationship.

Thanks for reporting.

**Comment by SirLamer** [comment]
Yeah, unfortunately Laravel does not perform this check. If you try to bind a model to a relationship in Laravel a second time, it will attempt it and it relies on database foreign keys to prevent it when not desired.

**Comment by lindyhopchris** [comment]
@SirLamer fix is on `develop`, will be in `1.0.0-beta.3`.

**Comment by Ciaro** [comment]
@lindyhopchris

Actually, duplicate entries were still added for me. 

![afbeelding](https://user-images.githubusercontent.com/891736/56583866-d73ebe00-65da-11e9-8dec-123a02b560d6.png)

The relation had the join fields as well, so the ID of the pivot table was being used (which is incorrect, as the diff function uses these ids to compare).

@see https://github.com/Ciaro/laravel-json-api/commit/37e9a4eb47f63ef62f4619cf53b06117e3c9bdd4 with possible fix. 

Still have to add an integration test.

**Comment by lindyhopchris** [comment]
@Ciaro what version are you on? The fix i pushed had a test that showed it was solved.

**Comment by lindyhopchris** [comment]
Ok. Could you push a PR with a failing test that replicates the issue you're having?

There's this test that is passing:
https://github.com/cloudcreativity/laravel-json-api/blob/develop/tests/lib/Integration/Eloquent/MorphToManyTest.php#L342

It was failing before the fix for this issue and is currently passing. I'd take a PR for a test added after it that reproduces the problem you're having.
