### ISSUE TITLE
Question: Is there a standard way to limit the number of related resources on POST/PATCH requests?

### ISSUE THREAD

**Issue by dimitvassilev** [cloudcreativity/laravel-json-api#226]
Hi Chris,
I am wondering if the package has a built-in way to configure a maximum number of related resource identifiers on a has-many relationship and if not - if you would consider adding such a feature. I may be too paranoid, but it seems to me I need some way to restrict that number globally or at least for some relationships where the operation is computationally intensive (with events triggerred, etc.).
If this is not present or going to be included (maybe with the validation changes you are working on), would you recommend a way to tackle this? I am thinking about doing checks within the creating/updating controller hooks.

Thanks a lot for any suggestions and overall for the great work with the package!

**Comment by lindyhopchris** [comment]
I'm going to close this because there's several issues open about validation at the moment. But when I put out the new validation, if you can't do what you want to do with it make sure you either open a new issue or re-open this one.
