### ISSUE TITLE
Include related resources

### ISSUE THREAD

**Issue by stfnndrsn** [cloudcreativity/laravel-json-api#23]
Our app have a fair amount of hasMany relationsships - and we are including them in our json-api responses - resulting eg. 5 queries pr. entity; and with 200 entities we have a bottleneck.

I were thinking about overwrite the EloquentAdapter#find method and do my own service-provide to register with my own class. 

But is it the best way to handle it? It seems as a generic problem, and a standardized way of handling relationships.

**Comment by lindyhopchris** [comment]
Hi! Where are you getting the bottleneck problem... when encoding the model to JSON API (i.e. via the schema) or when processing something a client has sent you? The `EloquentAdapter` is only used to process incoming relationships from clients.

If you can give me some more information I can definitely help find a better solution.

**Comment by stfnndrsn** [comment]
My problem is the number of SQL queries  (and time spent on doing them)

```php
'transactions' => [
    self::DATA => $resource->transactions,
],
```

![image](https://cloud.githubusercontent.com/assets/28970/19468847/e7f3aae8-9518-11e6-8ccd-5a9edb50cbe7.png)

**Comment by lindyhopchris** [comment]
Hi! 

So writing your own `EloquentAdapter` won't fix this. The EloquentAdapter is only used to resolve JSON API resource identifiers that are incoming.

What you want to do is use eager loading, which is an Eloquent feature:
https://laravel.com/docs/5.3/eloquent-relationships#eager-loading

E.g. in the search class for your search class for that model:

``` php
protected function filter(Builder $builder, Collection $filters)
{
  $builder->with('transactions');
}
```

You should see that `240x` stat change to `1x`

**Comment by stfnndrsn** [comment]
:+1:  I missed that feature :) Thanks!

**Comment by lindyhopchris** [comment]
No problem.

**Comment by stfnndrsn** [comment]
Hi!

Sorry to disturb you again.

Next issue I have here - what about related resources? We having a pattern here with `posts/10/comments` and having the hasMany relation on the 'comments' resource.

**Comment by lindyhopchris** [comment]
I haven't implemented full related resources support yet - it'll come in a future version.

However, you can do this for the moment. In your `PostsController` overload the `readRelatedResource` method with the following:

``` php
$model = $this->getRecord($request);
$key = $this->keyForRelationship($request->getRelationshipName());

if ('comments' === $key) {
	$content = $model->comments()->with('...')->get();
} else {
	$content = $model->{$key};
}

return $this
	->reply()
	->content($content);
```

I think you might already be overloading this method according to this issue:
https://github.com/cloudcreativity/laravel-json-api/issues/22

So you just need to add the `with()` call to what was written in that issue.

**Comment by lindyhopchris** [comment]
Leave this issue open as I've tagged it with `0.6.0` milestone so improvements to this get sorted in that release - though the solution mentioned above will work in the meantime.

**Comment by lindyhopchris** [comment]
Relationships are now better supported on the `1.x-dev` branch, but need to add support for `with` when querying has-many relationships.

**Comment by lindyhopchris** [comment]
With is now fully supported, including on relationships, in the 1.0 branch
