### ISSUE TITLE
v0.13.0 with Laravel 5.7 support

### ISSUE THREAD

**Issue by X-Coder264** [cloudcreativity/laravel-json-api#232]
First of all thank you @lindyhopchris for a great package.

My question is if there is any plan to tag 0.13.0 with Laravel 5.7 support? I'm asking because this is the only reason why some of our applications are still on Laravel 5.6. A v1 stable release (which has 5.7 support) hasn't been tagged yet and even if it does soon there is a lot of stuff that has changed between 0.12 and 1.0 and some of that stuff is (probably) a breaking change which means that upgrading isn't as easy as just bumping the constraint in composer.json.

**Comment by lindyhopchris** [comment]
Hi! So there wasn't a plan to tag a 0.13, but if this is straightforward then I can do it. Will have time to look at it later this week.

The only thing I'd say is that I can't forever support the 0.x series, because it's time consuming enough  trying to get things stable for 1.0. So if I do tag a 0.13 this week, it'll probably be the last one of that series.

**Comment by X-Coder264** [comment]
Thank you for considering to tag 0.13. Of course we don't expect that you support the 0.x series forever. This was just a question/suggestion so that we can upgrade our apps to L5.7 (as this is our only blocker atm) and then when 1.0 stable gets tagged we plan to upgrade to that ASAP.

**Comment by lindyhopchris** [comment]
Ah great, yes I see your point - makes sense to have a 0.13 while we don't have a stable 1.0.0. Will look at this today.

**Comment by lindyhopchris** [comment]
@X-Coder264 I've pushed a `0.x` branch. Can you give it a go before I tag it? I don't have any applications on `0.12` anymore and the test coverage isn't as good on that branch. Saying that though there weren't any major changes updating to Laravel 5.7 for `1.0.0-beta` so in theory this should work fine.

**Comment by X-Coder264** [comment]
@lindyhopchris, sure. I'll test it later today.

**Comment by X-Coder264** [comment]
@lindyhopchris All tests in my app are passing and everything seems to work. Looks like you can tag 0.13 now - thank you for your time.

**Comment by lindyhopchris** [comment]
Thanks! Tagged `v0.13.0`
