### ISSUE TITLE
Questions on ResourceProviders

### ISSUE THREAD

**Issue by jannis-a** [cloudcreativity/laravel-json-api#233]
Hi again @lindyhopchris,
as you stated in https://github.com/cloudcreativity/laravel-json-api/issues/223#issuecomment-423231762 there is the possibility to hook in API resources from libraries. I implemented that approach for my "auth" module which gives permissions, roles and users. I'm using a `ResourceProvider` in my unit tests which work just fine.

As far as I understand the routes defined inside the `mount()` method will get the middlewares applied from the call to `JsonApi::register('bla', [...])` inside a routes file or wherever it got called. Can you give more details on this please? 

Another question raised. What if I want to add additional relationship routes for the `users` resource, which is defined in a `ResourceProvider`, in on of my projects using this provider? Or maybe even add relationship routes from another library (which has a dependency on the "auth" library)? Assuming the `ResourceProvider` contains something like this:

```php
public function mount(ApiGroup $api, Registrar $router) {
	// roles and permissions resources

	$api->resource('users', [
		'has-many' => ['permissions', 'roles'],
	]);
}
```

Best regards :smile:

**Comment by lindyhopchris** [comment]
Hi! The `mount` method occurs *within* the JSON API route definitions - i.e. you are adding to the API. E.g. in the consuming application:

```php
JsonApi::register('v1', ['middleware' => 'foo'], function ($api) {
  $api->resource('posts');
  // resource provider mounting occurs here
});
```

There's no support for routes that your package would want to add outside the `JsonApi::register` grouping, as that's outside of the scope of this package. Your installation instructions for your package would need to provide additional information on how to register those additional routes outside of JSON API.
