### ISSUE TITLE
Exceptions with headers are converted to errors without those headers

### ISSUE THREAD

**Issue by sg3s** [cloudcreativity/laravel-json-api#234]
When using middleware that rejects a request by throwing an exception it is eventually passed off to JsonApi handler to create a valid jsonapi error object.

However for some errors that add headers to the response, and those headers are lost. Most notably, and easily reproducible, it happens when you configure a `throttle` middleware and hit the rate limit. This generates a `ThrottleRequestsException` and it includes some headers that should be added to the response that inform the user-agent when it is allowed to make requests again. 

JsonApi should probably include headers from exceptions that have them.

It seems like some thought was already put into it, as there is a function to do just that, but it doesn't do anything currently.

[ExceptionParser.php:231](https://github.com/cloudcreativity/laravel-json-api/blob/develop/src/Exceptions/ExceptionParser.php#L231)

    /**
     * @param Exception $e
     * @return array
     */
    protected function getHeaders(Exception $e)
    {
        return [];
    }

Shouldn't this just do the following:

    /**
     * @param Exception $e
     * @return array
     */
    protected function getHeaders(Exception $e)
    {
        return method_exists($e, 'getHeaders') ? $e->getHeaders() : [];
    }

Or am I missing something?

I can imagine how you could have cases where exception generate undesirable headers or conflicts, but for me it feels like it might be better to handle those cases as they popup/are found, there shouldn't be too many.

**Comment by lindyhopchris** [comment]
Thanks for pointing this out - think when I wrote `ExceptionParser::getHeaders` (a long time ago) there weren't Laravel exceptions with `getHeaders` methods... or at least I wasn't aware of any!

**Comment by sg3s** [comment]
The `ThrottleRequestsException` extends `Symfony\Component\HttpKernel\Exception\HttpException` where the headers are added as an option. 

This class is used as a prototype for pretty much all HTTP type exceptions I could find, and I think it is safe to assume that any exceptions extending this class have a http-safe headers object. Checking for that would be stricter / less prone to errors.

So maybe this is enough/cleaner

    return ($e instanceof HttpException ? $e->getHeaders() : []);

You already also check for this class in the `getErrors` method too, so maybe more consideration for this type could clean things up even more. 

Maybe there is a case to be made to allow adding extra headers to the `Error` object so that Exception -> Error conversions are a more direct mapping of attributes. Rendering a response that combines the headers if there are multiple errors with extra headers somehow. Maybe not, also seems kinda messy 😛 

Looking forward to the 1.0.0 release. Thank you for the effort!

**Comment by lindyhopchris** [comment]
@sg3s thanks for pointing this out, it's a neat addition!
