### ISSUE TITLE
Post request response code 500

### ISSUE THREAD

**Issue by wv989898** [cloudcreativity/laravel-json-api#236]
Hi, i am trying to make a post request via the createRecord() method in the adapter, but i keep getting a response code 500.
this is my model:
class Employee extends Model
{
    protected $table = 'Employees';
    public $timestamps = false;

    protected $fillable = [
        'firstName',
        'lastName',
        'company_id',
    ];

    public function companies()
    {
        return $this->hasOne(Company::class);
    }
}
This is my adapter:
class Adapter extends AbstractAdapter
{
    /**
     * Mapping of JSON API attribute field names to model keys.
     *
     * @var array
     */
    protected $attributes = [];

    /**
     * Adapter constructor.
     *
     * @param StandardStrategy $paging
     */
    public function __construct(StandardStrategy $paging)
    {
        parent::__construct(new Employee(), $paging);
    }

    protected function createRecord(ResourceObjectInterface $resource)
    {
        $record = new Employee();
        return $record;
    }

    protected function employees()
    {
        return $this->hasOne('companies');
    }
    
    /**
     * @param Builder $query
     * @param Collection $filters
     * @return void
     */
    protected function filter($query, Collection $filters)
    {
        // TODO
    }
}
This is the response i am trying to post(via my test classes):
'data' => [
                'type' => 'Employees',
                'attributes' => [
                    "company_id" => "1",
                    "firstName" => "test",
                    "lastName" => "test",
                ],
            ]

**Comment by wv989898** [comment]
This is the response from Postman:
CloudCreativity\LaravelJsonApi\Exceptions\DocumentRequiredException: JSON API error in file /vendor/cloudcreativity/laravel-json-api/src/Http/Requests/ValidatedRequest.php on line 270

**Comment by lindyhopchris** [comment]
Have you followed the installation instructions on how to modify your Exception handler? The `DocumentRequiredException` should be converted to a `400 Bad Request` response by the exception handler if you've updated your exception handler as per the installation instructions.

**Comment by lindyhopchris** [comment]
It's possibly to do with your headers. As per this:
https://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html#sec4.3

> The presence of a message-body in a request is signaled by the inclusion of a Content-Length or Transfer-Encoding header field in the request's message-headers.

**Comment by wv989898** [comment]
I have been working on it for some time now, i still get an error 400, but when i write my tests i get this response,
"errors": [
        {
            "status": "400",
            "title": "Required Member",
            "detail": "The member 'data' is required.",
            "source": {
                "pointer": "/"
            }
        }
    ]

Do you still think it has to do with my headers?

**Comment by wv989898** [comment]
Hi, thanks i get status 201 created now in postman with the added headers, now i will add the headers in my laravel project.
