### ISSUE TITLE
Create Schema instence 

### ISSUE THREAD

**Issue by baderAmmoun** [cloudcreativity/laravel-json-api#238]
Iam trying to create Schema that allow me to include the require relations for a specific model dynamically inside json respond ,so I create class which extend from the SchemaProvider and try to create an instance from it inside   schema class  contractor for that model .but I got this fault "Schema is not registered for a resource at path ''. any suggestion to solve this problem I will be great full

**Comment by lindyhopchris** [comment]
Closing this as I believe my comment above is the solution and haven't heard anything since!
