### ISSUE TITLE
Index and Create Authorization

### ISSUE THREAD

**Issue by dimitvassilev** [cloudcreativity/laravel-json-api#240]
Hi Chris,

I have just upgraded to the beta 4 version and re-run my tests and the search_resource() and search_resource_by_id() tests failed. I did some digging and found that with the removal of the HandlesAuthorizers trait, what is passed to the index($type, $request) and create($type, $request) authorizer methods as $type parameter has changed: instead of the model class name, it is now the resource name. Eloquent policies require the class, however, and the Security section of the documentation still says that the class is provided, so I guess this is a bug? I might be missing the point of it, would you please look into it?

Thanks,
Dimitar

Edit: I think the problem is [here](https://github.com/cloudcreativity/laravel-json-api/blob/ea62935faaf5b8d1e199def2a02159aa830ced23/src/Http/Requests/FetchResources.php#L39) and the first argument should be `$this->getType()`, instead of `$this->getResourceType()`, so as to match what is in the middleware.

**Comment by lindyhopchris** [comment]
Yes definitely a bug. I'll look at this now.

**Comment by lindyhopchris** [comment]
@dimitvassilev can you give this a go:

```
composer require cloudcreativity/laravel-json-api:1.x-dev
```

That will pull in the `develop` branch which should fix the problem - let me know if it does.

**Comment by dimitvassilev** [comment]
It certainly does, thanks a lot for the immediate response!

Cheers!

**Comment by lindyhopchris** [comment]
Ah you caught me at a good time - saw your issue when I had 15 minutes to spare! I'll release `beta.5` now with the fix in it.
