### ISSUE TITLE
register default controller for all routes?

### ISSUE THREAD

**Issue by edeis53** [cloudcreativity/laravel-json-api#242]
I read in the docs that you can configure a specific controller on a per resource basis:
```
JsonApi::register('default', ['namespace' => 'Api'], function ($api, $router) {
    $api->resource('posts', ['controller' => 'PostsController']);
});
```

Is it possible to register a controller for an entire group? eg. set a default controller other than `CloudCreativity\LaravelJsonApi\Http\Controllers\JsonApiController` ?
eg.
```
JsonApi::register('default', ['controller' => 'CustomJsonApiController', 'namespace' => 'Api'], function ($api, $router) {
    $api->resource('posts');
});
```

Or perhaps just configure in `/config/json-api.php`?

**Comment by lindyhopchris** [comment]
I don't remember putting in the ability to override the default controller, but would make sense for this to be added.

It won't be until `1.1` though because I'm desperately trying to get `1.0` done and adding more issues to the `1.0` milestone at this point isn't really feasible.
