### ISSUE TITLE
Question: Modular Application

### ISSUE THREAD

**Issue by plunkettscott** [cloudcreativity/laravel-json-api#252]
I am working on a modular application and am looking for a way to load JsonApi resources in each module. What would I need to load in the module's service provider or what would I need to adjust to make it work? All modules are loaded in the Apps\domain namespace. Is there an easy way to autoload the API from a JsonApi namespace within the Apps\domain namespace?

Scott

**Comment by lindyhopchris** [comment]
Hi,

Without fully understanding what you're trying to do, I suspect you probably want to use the `ResourceProvider` feature that already exists. Unfortunately there's not docs for it yet as I haven't had time to write any, but we use it for loading resources from composer packages.

There's an example one in the tests directory here:
https://github.com/cloudcreativity/laravel-json-api/tree/develop/tests/package/src

The key class is the `ResourceProvider` as that is the class that loads the package's resources into an API.

The API then needs to add the resource provider to its config, as shown here:
https://github.com/cloudcreativity/laravel-json-api/blob/develop/tests/dummy/config/json-api-v1.php#L138-L154

**Comment by lindyhopchris** [comment]
Closing this as the questions is related to a really old version. Feel free to open a new issue if there's still a problem.
