### ISSUE TITLE
How to modify related objects before 'replace' when send as PATCH

### ISSUE THREAD

**Issue by mk-conn** [cloudcreativity/laravel-json-api#264]
Hi,

when I try to use replacing<RelationName> hook I only get the record and not the related objects, I just wanna add some default data (e.g. the logged in user as created_by, updated_by properties...). Is there another way - maybe overwriting the Adapter 'replace' methods, but would be the controller hooks not the place to do so?

**Comment by lindyhopchris** [comment]
Hi! What do you mean by the 'replacing' hook?

Personally I put stuff like this in the adapter, as the adapter is the thing that fills the model with values from the JSON API resource, so it makes sense to do any other fill logic there.

Maybe use the `persist` method like this:

```php
protected function persist($record)
{
  if ($record->exists) {
    $record->updatedBy()->associate(Auth::user());
  } else {
    $record->createdBy()->associate(Auth::user());
  }
}
```

**Comment by mk-conn** [comment]
I mean the Relationship Hooks in the controller as documented here:  https://laravel-json-api.readthedocs.io/en/latest/basics/controllers/ , escpecially the replacing{Field} Hook.

**Comment by mk-conn** [comment]
Great :) Thx!

**Comment by lindyhopchris** [comment]
As this is quite old, I'm closing in favour of the issue in the new package (`laravel-json-api/laravel`), where this will be straight-forward to implement.
