### ISSUE TITLE
Creating resources with included relationship of any type

### ISSUE THREAD

**Issue by tembra** [cloudcreativity/laravel-json-api#266]
Hello guys!

I would like to know if this awesome package supports a **single** POST request that:

1. Create a new resource
2. Create a new related one-to-many resource
3. Create a new independent resource
4. Create a new related many-to-many resource
5. Create a new nested related one-to-many resource

This can be imagine in the following *crazy* scenario:

- An user fills a single form where he signed up (email/pwd), writes his first post (title/body), selects multiples tags (id of each) previously added in the app but also types new tags (name) not founded in the select list, and finally write a first comment on his post.

So I make a `POST /api/users` request with all data, then:

1. A new *user* is created
2. A new *post* is created and the *user* `id` from item 1 is assigned to it
3. A new *tag* is created
4. The `id` of each selected *tag* and the `id` of tag from item 3, all them paired with the *post* `id` from item 2 is attached/synced in the `post_tag` pivot table.
5. A new *comment* is created and the *post* `id` from item 2 is assigned to it

If this package supports this entire operation in a **single request**, *how would be the posted data?*
I also extend my question to the PATCH and DELETE requests.

Thanks in advance!

**Comment by dimitvassilev** [comment]
The json-api specification itself requires that related resources be represented by an identifier object (see https://jsonapi.org/format/#document-compound-documents) which means that you cannot sent an unexisting nested resource, unless maybe if ids are generated on the client side. You can also implement custom logic to parse the meta attribute using the hooks before and after creation that the library provides, but it would be much easier to just sent sequential requests instead of trying to force all actions into a single one.

**Comment by tembra** [comment]
Thanks for you answer @dimitvassilev but I think you missed my point here.

> The json-api specification itself requires that related resources be represented by an identifier object (see https://jsonapi.org/format/#document-compound-documents) which means that you cannot sent an unexisting nested resource, unless maybe if ids are generated on the client side.

Sure. Fortunately I know that. Indeed that's why I posted this question: to know if/how this implementation was made, because it will maybe use `meta` key and I do not find any documentation about this.

> You can also implement custom logic to parse the meta attribute using the hooks before and after creation that the library provides, but it would be much easier to just sent sequential requests instead of trying to force all actions into a single one.

Yeah. I can use hooks to process the `meta` key for after creation, but if anything fails can I rollback the entire transaction? This is the same problem for sequential requests. If the second or later request fails (e.g. wrong data given and did not pass the validations) can I rollback the previously requested?

I know that I can implement on my own all these features. I can even implement that on front-end. But the goal here is to know if this package has something like this already implemented.

**Comment by lindyhopchris** [comment]
@tembra there is nothing in the spec at the moment on how to support multiple operations in a single HTTP request. However, it's looking like the spec will add this in the near future - you can see the discussion on it here:
https://github.com/json-api/json-api/pull/1254

If and when that gets merged, then I'll also add support for operations to this package.

**Comment by tembra** [comment]
@lindyhopchris thanks! also for the discussion link.

I know that the spec does not have support for multiple operations in a single request. I was just guessing if you would added this support for your own purposes as this package was developed to be applied at Cloud Creativity.

In some projects I need this approach and I think that possibles solution (in a tens of I thought) could be:

1. Have a non-resource endpoint that receives all this information through `meta` key with my own defined structure that apply everything in a single request.

2. Have a non-resource endpoint that return a transaction id (e.g. `GET /api/misc/transaction`):
    - Then send all POST requests for the operations including the transaction id in the `meta` key.
    - When these requests are processed they are not applied but just saved in a temporary transaction table with that id, so returning a `202 Accepted` status code as defined [here](https://jsonapi.org/format/#crud-creating-responses-202), but with a temporary id for that resource in `meta` key.
    - This temporary id would be used for relationship purposes in the subsequent requests.
    - Once all requests has been sent you must send to the API the _commit_ command (e.g. `POST /api/misc/transaction` sending the transaction id).
    - Then all transaction will be executed in the order that has been sent inside a single database transaction. This way if anyone fails the entire transaction could be rolled back.
    - If the transaction id was not commited in a window of time it is automatically rolled back (i.e. deleted from temporary table).

What do you think? Do you have another idea or just prefer to control this over front-end while waiting for new specification of JSON API ?

**Comment by lindyhopchris** [comment]
We deal with it on the client side. We exclusively use Ember JS, and it's really simple to compose multiple async operations using Ember Concurrency.

We definitely plan to support JSON API operations when they are introduced as they will be awesome for exactly this kind of use case.

For the meantime you'll need to implement your own solution... the ideas you've posted definitely sound viable and it'll be down to you to decide which one works best for you.

What might help is we've introduced on the `develop` branch support for the JSON API recommendation for asynchronous processing. This is documented here:
https://github.com/cloudcreativity/laravel-json-api/blob/develop/docs/features/async.md

You'd need to install the `develop` branch though to get this - it will be included in the next tag but I haven't got to the point of tagging stuff yet (might do that this week).

**Comment by lindyhopchris** [comment]
I'm going to close this issue for now - we will add the JSON API operations feature when it is added to the spec.

The async processing stuff is now available to use as of `1.0.0-beta.6`.

**Comment by tembra** [comment]
@lindyhopchris not trying to reopening the issue, but just to clarify for myself. You said this:

> We deal with it on the client side. We exclusively use Ember JS, and it's really simple to compose multiple async operations using Ember Concurrency.

In this scenario that you have to add a new `users` resource and a new `posts` resource for this user, but the new `posts` request fails: how Ember Concurrency will deal with it rolling back? I mean it will delete the user? Or you will need to specific create a delete request for the recently created user?

**Comment by lindyhopchris** [comment]
@tembra 

it's totally up to the use case as to how to deal with it... either delete or keep the ones that haven't failed and retry (after new user input) the ones that haven't. no one way to approach it.

it's not ideal but it works at the moment... I'm definitely looking forward to the introduction of JSON API operations.
