### ISSUE TITLE
modify laravel model before save

### ISSUE THREAD

**Issue by Robindfuller** [cloudcreativity/laravel-json-api#267]
Hi

Is there a convenient way to modify a record during a patch request? I need to set a user_id and date when an update is submitted.

Thanks

**Comment by Robindfuller** [comment]
I thought it might be in an 'updating' method but it has no affect.

**Comment by lindyhopchris** [comment]
There's an `updating` hook on the controller, though I think based on some of the comments I've had I need to add hooks to the adapters as well.

This would mean that the controller hooks can be used for things like dispatching events, jobs etc, whereas the adapter hooks could be used for any additional fill operations, such as recording the user if there was an `updated_at` column. As the adapters do the filling of models, I think it's starting to make sense to have hooks there too.
