### ISSUE TITLE
getting request in filter

### ISSUE THREAD

**Issue by fibis** [cloudcreativity/laravel-json-api#269]
We have the following situation:
several users are allocated to one company. When requesting, for example, the index action to get the customers, we only want to display customers that are assigned to this company. We can get the company over the authenticated user with the request (`$user = $request->user()`).
 Is there any way to get the request or the authenticated users in the filter function of the Adapter to modify the queries?

**Comment by kapokyue** [comment]
I think you can use [Laravel's facades](https://laravel.com/docs/5.7/facades) to get the request user, i.e. `Request::user()` or `Auth::user()`.

**Comment by lindyhopchris** [comment]
Hi! Yes as @kapokyue says, you want to use any of the Laravel helpers to get the current user. Either the facade or the use the helper: `request()->user()`.

If you prefer dependency injection, the adapter is constructed via the Laravel container. So you can type hint the Guard contract in your adapter's constructor, via which you can get the authenticated user.
