### ISSUE TITLE
JSON API Spec: 1.1 - Profiles

### ISSUE THREAD

**Issue by plunkettscott** [cloudcreativity/laravel-json-api#270]
Are Profiles going to be supported by this package? They are being released in JSON API Spec 1.1.

**Comment by lindyhopchris** [comment]
Hi! Yes, the aim of this package is to support the spec as a whole. So when profiles get added we will aim to support them at some point. The only thing I'm not sure about is when that will be, as we get sudden bursts of activity on this package and there's already a to-do list! We are making progress though so hopefully profiles will be supported sometime soon.

We'd need to upgrade the underlying `neomerx/json-api` package, which would be a breaking change. So profiles will probably land in `2.0` of this package.

**Comment by plunkettscott** [comment]
@lindyhopchris thanks for your work on this package!

I would be happy to help develop on the package as I get time. We have been using this package for every API we write since I found it. Super handy to not have to do all the repetitive endpoint logic.

Scott

**Comment by lindyhopchris** [comment]
@plunkettscott glad to hear you're using the package on multiple APIs and it's useful. Sorry for the code churn but it's definitely settling down and we should hit `1.0` once we merge #254 

Any help you could give in the future would be great - just let me know if you get any time.

**Comment by lindyhopchris** [comment]
Going to close this as JSON:API still haven't officially released profiles. Definitely something to support when they do but for the moment I don't see the point in leaving the issue open after 2 years!
