### ISSUE TITLE
Delete validator rules or some callback

### ISSUE THREAD

**Issue by riboflan** [cloudcreativity/laravel-json-api#271]
There are rules for create and update requests. Is there some possibility to implement rules that will be validated before delete action is accessed on model?

For example:

If I define model with foreign key in database that will restrict deleting of parent model, This will end with exception because system access database with delete request. It will be wery handy to have some option tu validate suspect of delete action and create something like status code and message in response for API.

For example 409 Conflict or 405 Method Not Allowed.

Or please give me some idea how to implement this type of validation in clear way with laravel json API resources.

Thanks.

**Comment by lindyhopchris** [comment]
This is a great idea and should definitely be supported. Thanks for suggesting.

For the moment you'd have to use the `deleting` controller hook to run whatever validation you want and return JSON API errors from the hook. That's documented here:
https://laravel-json-api.readthedocs.io/en/latest/features/errors/

**Comment by lindyhopchris** [comment]
Adding to the 1.0 milestone because this will involve a breaking change to the validators interface.

**Comment by lindyhopchris** [comment]
This will be in `1.0.0-rc.1`
