### ISSUE TITLE
the place for save the query in cache

### ISSUE THREAD

**Issue by baderAmmoun** [cloudcreativity/laravel-json-api#272]
Im trying to save the result of any query inside the key in the cache and add middle ware where I can check if
the key already exist inside the cache and if it is return it otherwise go further to the api

**Comment by lindyhopchris** [comment]
Hi! This kind of caching approach is best done in middleware. you want to save the HTML response against a key in the cache that is generated from the HTML request.

Adding your own middleware is documented here:
https://laravel-json-api.readthedocs.io/en/latest/basics/routing/

**Comment by baderAmmoun** [comment]
thank you for you answer .I need to caching the respond for jsonapi inside the key  for example if I have post model and the user send the request for the end point for that model .if it is the  first time I need  after the result come form database  save it  inside the key because I use the laravel just as a back-end 
I'm not sure where I Have to do that but most likely inside the adapter  for that model?

**Comment by lindyhopchris** [comment]
Yes the adapter does all the loading. You'll need to look at the code and overload methods to add in the caching.

**Comment by lindyhopchris** [comment]
Closing this as the questions is related to a really old version. Feel free to open a new issue if there's still a problem.
