### ISSUE TITLE
Different filter syntax on URL and Validator

### ISSUE THREAD

**Issue by tembra** [cloudcreativity/laravel-json-api#275]
Hello guys!

I'm allowing a filter on a relationship field. So on URL I'm using dot syntax `filter[relationship.field]=value`, but on my resource `Validator` I need to write on `$allowedFilteringParameters` and also on `queryRules()` using arrow syntax: `relationship->field` and `filter.relationship->field` respectively.

This is weird and also confuses the mind of developer.

**The question is:** This is a issue or you intended to do that?

I did not go deeper for this issue, but I think we can easily change to use dot syntax in all.

BTW in the [docs](https://laravel-json-api.readthedocs.io/en/latest/fetching/filtering/#disallowing-filtering) you give an example of `queryRules()` using dot syntax for `filter.author.*` what makes me guess that it is really an issue.

Thanks!

**Comment by lindyhopchris** [comment]
I'd recommend not using a *period* in the filter key name - it is not an allowed character for a member name according to the JSON API spec. Version 1.1 of the spec (upcoming, not yet official released) makes it clear that query parameters should only contain valid member names:

> A “query parameter family” is the set of all query parameters whose name starts with a “base name”, followed by zero or more instances of empty square brackets (i.e. []) or square-bracketed legal member names. The family is referred to by its base name.

The `filter` param is a query parameter family. As periods are not allowed in member names, this is not valid:

`filter[relationship.field]`

It instead should be:

`filter[relationship][field]`

If you use this format, then Laravel validations (that use the dot notation) can refer to that as `filter.relationship.field`.

**Comment by lindyhopchris** [comment]
Hi!

So the `$allowedFilteringParameters` is a whitelist of what filter parameters are allowed. It only checks the *top-level* keys, so won't check for sub-keys. I suppose this could be added in but really isn't a priority for me to do at the moment considering the number of other things that need doing.

The `queryRules` is to check (using standard Laravel validators) what values have actually been sent, which is different from a white-list.

The data-access points you make are to do with Laravel, not this package. The `get` method on a collection does not use dot notation - it refers to the key of the array that the collection holds. If you want to use dot notation to get a value from the filters, you will have to use `array_get` as you suggest.
