### ISSUE TITLE
How to add where query to read action

### ISSUE THREAD

**Issue by deividaspetraitis** [cloudcreativity/laravel-json-api#285]
Hello,

I have `read` action in my `posts` resource ( `v1/posts/1` ) and I want to add some additional where conditions, for example to make sure that this entity belongs to current user.

Which method I should to implement?

**Comment by lindyhopchris** [comment]
Hi! Depends what you're trying to do. 

Is it to deny/allow the user to read the resource? In which case you should use authorizers.

Is it to send a `404` - i.e. the post does not exist in the API? In which case you should overload the `findQuery` method on the adapter.

Note that if anywhere in your API you return a resource identifier like this:

```json
{
  "type": "posts",
  "id": "1"
}
```

Then it would only be appropriate to send a `404` if posts 1 no longer exists (i.e. has been permanently deleted). If post 1 does exist but the client cannot access it a `401` or `403` would be the appropriate response to `GET /api/v1/posts/1`.

Let me know whether this helps or not, as the answer is a bit dependent on your use case!

**Comment by deividaspetraitis** [comment]
Yep, use case is to deny/allow to read the resource depending on is user owner of it or not. `Authorizers` worked like a charm, thanks!
