### ISSUE TITLE
Question: validation for not present attribute

### ISSUE THREAD

**Issue by deividaspetraitis** [cloudcreativity/laravel-json-api#288]
Hello,

I have custom rule for `not_present` validation which I have used previously for example when updating user since I don't want to allow to update certain fields like `password`.

From current reasearch I know that request data is merged with record data ( see Updating Resources  https://laravel-json-api.readthedocs.io/en/latest/basics/validators/ ) and result is passed to the validation I suppose that is the reason why for example following will not work:

```
    protected function rules($record = null): array
    {
        if (!is_null($record)) {
            return [
                'password'  =>  'not_present',
            ];
        }
    }
```

Is there any way to check for request tada to see what fields it contains and if it contains for example `password` field make validation return an error?

Thanks.

**Comment by jannis-a** [comment]
One way to implement this would be adding the following methods to your validators:

```php
public function create($record, array $document): ValidatorInterface {}
public function update($record, array $document): ValidatorInterface {}
```

From inside those you could check for the password property inside `$document`:

```php
use CloudCreativity\LaravelJsonApi\Document\Error;
use Illuminate\Support\Arr;
use Neomerx\JsonApi\Exceptions\JsonApiException;

if (Arr::has($document, 'data.attributes.password') {
    $error = Error::create([
        'title' => 'Your error title',
        'detail' => 'Your error message.',
        'status' => '402',
    ]);

    throw new JsonApiException($error, 402);
}
```

**Comment by lindyhopchris** [comment]
Realise I haven't documented this, but you can overload the `existingAttributes` method and remove the `password` field from the return value. For example:

```php
protected function existingAttributes($record): iterable
{
    return collect(parent::existingAttributes($record))->forget('password);
}
```

**Comment by lindyhopchris** [comment]
That way the `password` field will only be present if it has been sent by the client, so the `not_present` rules should then work.

**Comment by lindyhopchris** [comment]
Great, glad to hear it! I'm just going to re-open this so that I don't forget to update the docs, as this should be documented.
