### ISSUE TITLE
extending controller not working?

### ISSUE THREAD

**Issue by fibis** [cloudcreativity/laravel-json-api#296]
We tried the feature of extending controllers with rc-2. We have our resource `orders` and extent it with `$api->resource('orders')->controller();`. An Controller is existing under `App\Http\Controllers\OrdersController`, the default path for extending controllers. When we now try to get order resources, we getting the following error:

`ReflectionException: Class App\Http\Controllers\\OrdersController does not exist in file /shared/httpd/eventbuddy/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 767`

It seams that the double slash back wrong is or is there an other fault?

**Comment by lindyhopchris** [comment]
Hmmm... yes it shouldn't have the double slash. It's interesting though that I've got this in production apps and haven't had a problem.

What's the namespace that your API routes are being registered in? The namespace should be `App\Http\Controllers`, not `App\Http\Controllers\` - can you check what you're using?

**Comment by lindyhopchris** [comment]
This is also working in all the tests. So my gut feel is it's something to do with your setup - but totally happy to stand corrected!!

**Comment by fibis** [comment]
I found the error: We had this line of  code in our file for the routing:
``` JsonApi::register('v1', ['namespace' => ''], function (RouteRegistrar $api)```

We removed` 'namespace' => ''` and everything worked perfectly. Thank you very much!
