### ISSUE TITLE
Creating resource with it's relationship

### ISSUE THREAD

**Issue by deividaspetraitis** [cloudcreativity/laravel-json-api#298]
Hello, 

I was wondering is there a way to create a resource and its relation in a single request. For example: I want to create a post with comments in single request:

```
{
  "data": {
    "type": "post",
    "attributes": {
      "title": "<post title>",
      "description": "<post text>"
    },
    "relationships": {
      "comments": {
        "data": [
          {
            "type": "comments",
            "attributes": {
              "text" : "First comment"
            }
          },
          {
            "type": "comments",
            "attributes": {
              "text" : "Second comment"
            }
          }
        ]
      }
    }
  }
}
```

The idea is not to assign `post` to a `comment` but create them. Is this valid approach at all if so how I can achieve using this package?

Thanks.

**Comment by lindyhopchris** [comment]
This is not supported by the JSON API spec at the moment. They are planning on adding operations (probably in version 1.2 of the spec), which will allow you to do multiple operations in a single request. I.e. your request would create the post, then create the comment linked to the newly created post - all in one request.

As this is not in the spec at the moment, this library does not support it.

**Comment by lindyhopchris** [comment]
See https://github.com/json-api/json-api/pull/1254 for more info.
