### ISSUE TITLE
Use authorizer for custom actions

### ISSUE THREAD

**Issue by fibis** [cloudcreativity/laravel-json-api#299]
Is it possible to use an authorizer for custom actions in a extended controller? For example adding the action name to the authorizer.

**Comment by lindyhopchris** [comment]
Yes I believe so, though I haven't tried it yet.

The authorizer method should be called for the equivalent JSON API action. E.g. if your custom action is `GET /posts/1/publish` then the authorizer method for `GET /posts/1` will be called.

You can check what action it is within the authorizer using:

```php
$action = Route::currentRouteAction();
```

As per https://laravel.com/docs/5.7/routing#accessing-the-current-route

Let me know if it works or not...!

**Comment by fibis** [comment]
Thanks for the quick answer! We using resource specific authorizers. I have tested your approach and when I try e.g `GET /posts/1/publish`, the authorizer's constructor isn't even called.

**Comment by lindyhopchris** [comment]
Ah for that to work you'll need to type-hint the correct request class in your controller action, so that it gets resolved from the container. Are you doing that already? Could you share the method from your controller?

**Comment by fibis** [comment]
That was the needed hint! With type-hinting the request class worked everything perfectly. Thank your very much!

**Comment by fibis** [comment]
strangely we getting now a new issue with this. Our Controller looks like this:

```
<?php

namespace App\Http\Controllers\Api;

use CloudCreativity\LaravelJsonApi\Http\Controllers\JsonApiController;
use CloudCreativity\LaravelJsonApi\Http\Requests\FetchResource;
use App\Order;
class OrdersController extends JsonApiController
{

    public function resendEmail(FetchResource $request, Order $order): \Illuminate\Http\Response
    {
        $order->sendEmail();

        return $this->reply()->content($order);
   }
}
```
Now we getting this error: 
`CloudCreativity\LaravelJsonApi\Exceptions\RuntimeException: Expecting resource binding to be substituted. in file /shared/httpd/eventbuddy/vendor/cloudcreativity/laravel-json-api/src/Http/Requests/Concerns/ResourceRequest.php on line 49`

Seams that getting the resource from the url is not possible, but type-hinting of $order worked well.

**Comment by fibis** [comment]
Using `public function resendEmail($resource, Order $order)` without type-hinting the  `$resource`  is given us the following error: ` App\Http\Controllers\Api\OrdersController::resendEmail() must be an instance of App\Order, string given in file`

**Comment by lindyhopchris** [comment]
Are you on `1.0.0-rc.2`. 

The binding substitution is done in the `json-api` middleware. If you use `route:list` does that show up in the middleware for this custom route?

**Comment by fibis** [comment]
I found the error, it was my own stupidity: 

> Note that you must use {record} as the route parameter for the resource id.
