### ISSUE TITLE
Rule Validator needs recursively convert attributes to an array.

### ISSUE THREAD

**Issue by lindyhopchris** [cloudcreativity/laravel-json-api#3]
As reported here:
https://github.com/cloudcreativity/json-api/issues/18

This line:
https://github.com/cloudcreativity/laravel-json-api/blob/master/src/Validator/Attributes/RulesValidator.php#L149

Needs to recursively change the object to an array before passing into the Laravel validator.

**Comment by nickelozz** [comment]
@lindyhopchris hello

I'm using cloudcreativity/laravel-json-api v0.2.1 and I believe I found another bug with the object to array conversion.

For structures that contain an array of objects, these won't get converted into arrays:

```php
// request attributes

"multiple": [
  {
    "val1": "one",
    "val2": "two"
  },
  {
    "val3": "three",
    "val4": "four"
  }
],
"nestedObj": {
  "obj1": {
    "val1": "one",
    "val2": "two"
  },
  "obj2": {
    "val3": "three",
    "val4": "four"
  }
}

// toArray conversion of attributes

"multiple" => [
  {
    "val1": "one",
    "val2": "two"
  },
  {
    "val3": "three",
    "val4": "four"
  }
],
"nestedObj" => [
  "obj1" => [
    "val1" => "one",
    "val2" => "two"
  ],
  "obj2" => [
    "val3" => "three",
    "val4" => "four"
  ]
}
```
This same behavour happens regardless of the nesting level. Please let me know if I can help any further.

**Comment by lindyhopchris** [comment]
Hi @nickelozz 

Sorry for slow reply - been on holiday. Yes, this is definitely a bug. I'll be able to look at it on Monday when I'm back from holiday.

Cheers,
Chris

**Comment by lindyhopchris** [comment]
@nickelozz 

Believe I've now fixed this if you update your `cloudcreativity/json-api` dependency to `v0.3.3`

**Comment by nickelozz** [comment]
@lindyhopchris I've tested and it works now...thanks so much.

Apparently in the upcoming version (5.2) of Laravel a lot of what I've been doing manually will be "laravelized" thanks to the new "Form Array Validation"... oh well it was a learning experience :smiley: 

In case anyone wants to read about it check here: https://laravel-news.com/2015/11/laravel-5-2-a-look-at-whats-coming/
