### ISSUE TITLE
Illuminate\Contracts\Container\BindingResolutionException: Target [CloudCreativity\JsonApi\Contracts\Http\Requests\RequestInterface] is not instantiable.

### ISSUE THREAD

**Issue by mk-conn** [cloudcreativity/laravel-json-api#30]
Could somebody explain me the reason why this *could* happen? I'm trying to integrate laravel-json-api in an existing project (switching from limoncello-collins, since he gave up developing for laravel...) . When I tried the demo-laravel-json-api project I had no problems.

**Comment by lindyhopchris** [comment]
`RequestInterface` is only bound into the container if there is a valid JSON API request. This happens in the `json-api` middleware here:
https://github.com/cloudcreativity/laravel-json-api/blob/master/src/Http/Middleware/BootJsonApi.php#L82

Have you used the `json-api` middleware? It's intended for use in the route group that defines your resources, as per here in the demo app:
https://github.com/cloudcreativity/demo-laravel-json-api/blob/master/app/Http/Kernel.php#L51

**Comment by mk-conn** [comment]
Daaaamn.... Thanx for the middlware hint... I was running my (unit) tests with the withoutmiddlware trait ... ;)
