### ISSUE TITLE
composer could not find package version 1.0.0-rc.2

### ISSUE THREAD

**Issue by karlis-simanovics** [cloudcreativity/laravel-json-api#301]
Greetings!
Going by the documentation for installing the necessary dependencies using Composer:
- composer require --dev cloudcreativity/json-api-testing:1.0.0-rc.2

I am receiving the following error:
- [InvalidArgumentException]
   Could not find package cloudcreativity/json-api-testing in a version matching 1.0.0-rc.2

If i am requiring version 1.0.0-rc.1, then everything works fine.
Thank you.

**Comment by lindyhopchris** [comment]
Ah that's a typo in the docs, it's version `1.0.0-rc.1` for the testing package. Thanks for reporting, I'll fix the docs tomorrow.
