### ISSUE TITLE
sorting by alias 

### ISSUE THREAD

**Issue by fibis** [cloudcreativity/laravel-json-api#303]
To get a speedup in our API we have written custom SQL queries that selecting all needed data with the relations. We also using alias columns for that (`... AS paid`). We also want to sort by these columns.
The problem seems, that every sorting request is prefixed with the table name when nothing other is specified. Is it possible to deactivate this behavior for certain sorting requests?

**Comment by lindyhopchris** [comment]
Hi! Sorry for slow reply.

I think you want to overload this method:
https://github.com/cloudcreativity/laravel-json-api/blob/develop/src/Eloquent/Concerns/SortsModels.php#L118-L123

Let me know if that works.

**Comment by fibis** [comment]
Overloading the method worked fine for use. Thank you very much!

**Comment by fibis** [comment]
For those who are interested:

```
protected function getQualifiedSortColumn($query, $field)
   {
       if($this->getSortColumn($field, $query->getModel())[0] == '.'){
           return substr($this->getSortColumn($field, $query->getModel()), 1);
       } else {
           return parent::getQualifiedSortColumn($query, $field);
       }
   }
```
Alias columns are mapped in `$sortColumns` and starting with a `.`

**Comment by lindyhopchris** [comment]
Brilliant, glad that worked!
