### ISSUE TITLE
Got Access denied error when I tried to access DB in Kernel.php.

### ISSUE THREAD

**Issue by ericgaonz** [cloudcreativity/laravel-json-api#306]
I tried to use the "Task Scheduling", the codes below in the function schedule() of file Kernel.php,
    DB::table('*table name*')->delete();
but I got the error below,
    SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: YES) 

Did anyone meet this before?

**Comment by ericgaonz** [comment]
Fixed, just log in to the container, then the command "php artisan schedule:run" works.
docker exec -it [container_id] bash

**Comment by lindyhopchris** [comment]
Hi! Not sure this issue is in the right repo?
