### ISSUE TITLE
No response on DELETE

### ISSUE THREAD

**Issue by itwebdeveloper** [cloudcreativity/laravel-json-api#308]
Hi,
I'm using "cloudcreativity/laravel-json-api" "version": "v1.0.0-rc.2" and I realized that when sending a delete request against a resource I get no response.

Example request:

`curl -X DELETE   http://api.homestead.test/api/v1/posts/1   -H 'Accept: application/vnd.api+json'   -H 'Authorization: Bearer <PERSONAL TOKEN>' -H 'cache-control: no-cache'`

I get: Line return. i.e.:

```
vagrant@homestead:~/code/demo-laravel-json-api$ curl -X DELETE   http://api.homestead.test/api/v1/posts/1   -H 'Accept: application/vnd.api+json'   -H 'Authorization: Bearer <PERSONAL TOKEN>' -H 'cache-control: no-cache'
vagrant@homestead:~/code/demo-laravel-json-api$
```

This is not happening with the version included in "cloudcreativity/demo-laravel-json-api" i.e. "version": "v1.0.0-beta.5". This version in fact return a "204 No Content" response.

```
vagrant@homestead:~/code/demo-laravel-json-api$ curl -X DELETE   http://demo-laravel-json-api.test/api/v1/posts/1   -H 'Accept: application/vnd.api+json'   -H 'Authorization: Bearer <PERSONAL TOKEN>' -H 'cache-control: no-cache'
HTTP/1.0 204 No Content
Cache-Control: no-cache, private
Date:          Fri, 22 Feb 2019 03:47:02 GMT
```

I checked the method `delete()` in `JsonApiController.php` and looks that is returning the same response in both versions however `reply()` behaviour in `CreateResponses.php` is different between the two versions.
For seeing the difference just try to edit the method from:

```php
    protected function reply()
    {
        return \response()->jsonApi($this->apiName());
    }
```

To:

```php
    protected function reply()
    {
var_dump(\response()->jsonApi($this->apiName())); exit;
        return \response()->jsonApi($this->apiName());
    }
```

Result:
"v1.0.0-beta.5" will print the dump of the Response instance.

"v1.0.0-rc.2" will print a 500 Internal Error.

`
local.ERROR: Uncaught ErrorException: Object of class CloudCreativity\LaravelJsonApi\Http\Responses\Responses could not be converted to string in /home/vagrant/code/demo-laravel-json-api/vendor/cloudcreativity/laravel-json-api/src/Http/Controllers/CreatesResponses.php:50
`

**Comment by lindyhopchris** [comment]
Thanks for reporting. This is to do with the `$api` property on the trait.

**Comment by lindyhopchris** [comment]
Closing this as I've never been able to re-produce it, so can't work out if it is actually a bug.
