### ISSUE TITLE
Laravel 5.8 support

### ISSUE THREAD

**Issue by taai** [cloudcreativity/laravel-json-api#311]
This package forbids me to upgrade Laravel to version 5.8, because this package requires ```5.5.*|5.6.*|5.7.*```. Wouldn't it be easier to just require ```^5.5.0``` so we don't have this issue next time?! 😉

**Comment by X-Coder264** [comment]
Requiring `^5.5` wouldn't be correct as there is no guarantee that the package would work (without adjustments) with for example `5.9` as Laravel doesn't follow semantic versioning (breaking changes are allowed in minor versions).

**Comment by lindyhopchris** [comment]
Hi! I saw that Laravel 5.8 was released as I left work yesterday, so wasn't able to do a release. However, I have got a `laravel-5.8` branch all ready to go, I just need to release it.

Laravel doesn't follow Semver so it's not possible to use `^5.5` - I have to test and release a new version every time Laravel does.

**Comment by lindyhopchris** [comment]
Cannot merge the `laravel-5.8` branch until this issue is fixed:
https://github.com/orchestral/testbench-core/issues/22

**Comment by lindyhopchris** [comment]
Released as `1.0.0`.
