### ISSUE TITLE
Order of records changes when reloading with same sorting

### ISSUE THREAD

**Issue by lucianholt97** [cloudcreativity/laravel-json-api#313]
Having multiple records with the same value in the column that I am ordering by, it occurs that they jump and change their place when I reload the data.

I would suggest, that you implement sorting by id as the second parameter in order to keep the sorting identical on reload. Otherwise, it looks very strange.

**Comment by lindyhopchris** [comment]
Yes good suggestion. To confirm, are you using the `StandardStrategy`, i.e. page-based pagination?

**Comment by lucianholt97** [comment]
Thanks for the quick reply. Yes, I am using page-based pagination.

**Comment by lindyhopchris** [comment]
Just for reference, this is a useful article on this issue:
https://tighten.co/blog/a-cautionary-tale-of-nondeterministic-laravel-pagination

Will be pushing a fix soon.

**Comment by lindyhopchris** [comment]
@lucianholt97 I've pushed a branch called `issue313`. Can you give it a go to check that it solves your problem?

```bash
$ composer require cloudcreativity/laravel-json-api:dev-issue313
```

**Comment by lucianholt97** [comment]
I am sorry for the late response. The branch issue313 works for me 👍

**Comment by lindyhopchris** [comment]
Great thanks for confirming. I'll get it merged into `develop` when I have time and release `1.1.0`.
