### ISSUE TITLE
Deprecated Error class "CloudCreativity\LaravelJsonApi\Document\Error"

### ISSUE THREAD

**Issue by katerss1** [cloudcreativity/laravel-json-api#316]
Is there any fix for the deprecated warning?
If it's a simple answer, please excuse me, im still a junior developer.

**Comment by lindyhopchris** [comment]
Hi! No problem with the question.

You should use the `Neomerx\Document\Error` class instead. We will be removing our custom class in the future.

You can of course continue to use our error class if you want - it's just we'll remove it in `2.0`. So if you can use the neomerx class now, it just saves time having to convert your code in the future.

**Comment by katerss1** [comment]
"Neomerx\Document\Error" doesn't exist for me.
I found "Neomerx\JsonApi\Document\Error".
With Neomerx\JsonApi\Document\Error I cant create an Error, right?
I really need the same Error::create() message functionality (title, detail, status).
Any tips to use the Neomerx package right?

**Comment by lindyhopchris** [comment]
Ah yes sorry, that was a typo. It's `Neomerx\JsonApi\Document\Error`.

You'll need to use `new Error()` and check that class for the constructor arguments.

As I said earlier, you are welcome to continue to use our own class even though it's deprecated - the deprecation message is just there to warn you that when upgrading to 2.0 you'll need to change the code. We're not sure when we'll hit 2.0 so it may not be soon that you have to make that change.
