### ISSUE TITLE
Validating a relationship

### ISSUE THREAD

**Issue by katerss1** [cloudcreativity/laravel-json-api#317]
Hi there me again,

I'm kinda stuck with a **relationship validation problem**.
Is there any way to validate **two foreign keys** of a pivot table?

For example, let's say that you have **subjects** and **users**. 

- A user **can** have multiple subjects and a subject **can** have multiple users. 
- A user **can't** assign himself to a subject twice. 

**But, how do I add a validation that checks if the user isn't already assigned to the same subject?**
_I want it to throw an error if the user is already assigned to the same subject (not a 500 error)._

 By the way, I want a validation on this endpoint: 
> http://localhost:8000/v1/users/1/relationships/subjects

**I really appreciate the help, thank you!**

Sincerly,

**Stefan**

**Comment by lindyhopchris** [comment]
Hi! 

Thanks for the question, but this isn't really a Laravel JSON API question. As we use Laravel's validation feature, you need to work out how you would do it with Laravel's validators - and then once you've done that you can then use it for your JSON API validators.

It sounds like what you need to use is Laravel's `exists` and `unique` rules, that inspect the database:
https://laravel.com/docs/5.8/validation#rule-exists
https://laravel.com/docs/5.8/validation#rule-unique

If you can't do what you need to do with either of those, then you'll need to write your own validation rule. The docs for that are here:
https://laravel.com/docs/5.8/validation#custom-validation-rules

For the relationship endpoints, how the data is passed to your validator is described here:
https://laravel-json-api.readthedocs.io/en/latest/basics/validators/#modify-relationship-validation

I'm going to close this issue as I think the above gives the info you need to tackle the problem, but feel free to re-open if you feel that there's a specific problem validating relationships in this package!
