### ISSUE TITLE
Class api-v1 does not exist

### ISSUE THREAD

**Issue by Nrko** [cloudcreativity/laravel-json-api#32]
Hi, I'm getting this error for some reason while trying to access the index route of a model. 

```
ReflectionException in Container.php line 749:
Class api-v1 does not exist
```

I'm using laravel 5.3 and the routes are set up differently compared to the demo project.

**Comment by lindyhopchris** [comment]
Hi! Bit difficult to diagnose based on what you've put, but I strongly suspect that you've got a middleware referenced as `api-v1`, but as you haven't registered anything on your HTTP Kernel for that name, it's trying to instantiate a class via the container instead.

The demo app use of `api-v1` is a reference to a middleware group defined here:
https://github.com/cloudcreativity/demo-laravel-json-api/blob/master/app/Http/Kernel.php#L50

You can see that the group includes the JSON API middleware which is `json-api:v1`, with the `v1` part of that referencing the `v1` definition in the JSON API config file here:
https://github.com/cloudcreativity/demo-laravel-json-api/blob/master/config/json-api.php#L51

Does that help?

**Comment by Nrko** [comment]
That was it! Thanks a lot! Altho I couldn't find anywhere in the wiki something related to that, during the configuration/installation.

**Comment by lindyhopchris** [comment]
Yeah, I need to write the wiki - haven't had time yet.

**Comment by roberttolton** [comment]
I think I'm having a similar issue, except mine says:
```
ReflectionException in Container.php line 749:
Class api does not exist
```

So it's trying to find `api` somewhere and failing, but I've not got anything defined as just `api`:

/routes/api.php
```
Route::group( [
    'middleware' => [ 'api-v1', 'cors', 'jwt.response_override' ],
    'namespace' => 'Api',
    'prefix' => 'v1',
    'as' => 'api-v1::'
], function () {
    JsonApi::resource( 'posts' );
} );
```

Kernel.php (middleware groups):
```
'api-v1' => [
    'json-api:v1',
    CheckForMaintenanceMode::class,
    'throttle:60,1',
    'bindings',
],
```

json-api.php:
```
'namespaces' => [
    'v1' => [
        'url-prefix' => '/api/v1',
        'supported-ext' => null,
        'paging' => [
            'page' => null,
            'per-page' => null,
        ],
        'paging-meta' => [
            'current-page' => null,
            'per-page' => null,
            'first-item' => null,
            'last-item' => null,
            'total' => null,
            'last-page' => null,
        ],
    ],
],
```

I think that Laravel 5.3, by using the `/routes/api.php` file is trying to automatically apply the now re-named `api` middleware group?

**Comment by lindyhopchris** [comment]
@roberttolton what's in your `RouteServiceProvider`?

**Comment by roberttolton** [comment]
@lindyhopchris Ah, indeed, it's the below:

```
    protected function mapApiRoutes()
    {
        Route::group([
            'middleware' => 'api',
            'namespace' => $this->namespace,
            'prefix' => 'api',
        ], function ($router) {
            require base_path('routes/api.php');
        });
    }
```

**Comment by roberttolton** [comment]
Should I change the `RouteServiceProvider` or leave it the way I have? Just two ways of doing the same I guess, but I wonder what your thoughts are.

**Comment by lindyhopchris** [comment]
Totally up to you. If you only have one api, then probably just do all the JSON API stuff under the `api` middleware group. If you have multiple API definitions, I normally have a middleware group for each.
