### ISSUE TITLE
Update async docs 

### ISSUE THREAD

**Issue by deividaspetraitis** [cloudcreativity/laravel-json-api#320]
Hello,

I was following https://laravel-json-api.readthedocs.io/en/latest/features/async docs and noticed that there is not mentioned how to link `queue-jobs`  with original resource in routes, for example by following docs in the end `GET /podcasts/queue-jobs` will respond with `404` because there is not mentioned that you need to add ( if we presume same `podcasts` resource )  `
    $api->resource('podcasts', [
        'async' => true
    ]);
` in routes file.

I think these details is worth to be mentioned as well as new routes names like `processing` and `processed`. 

Since my english is not very eloquent I'm not contributing by a pull request but with this github issue.

**Comment by lindyhopchris** [comment]
Great spot! Thanks for pointing this out and no worries, I'll take care of updating the docs.
