### ISSUE TITLE
Forcing camelized relationship naming

### ISSUE THREAD

**Issue by JapSeyz** [cloudcreativity/laravel-json-api#321]
Hi,

A bit similar to my previous issue, #315, but it seems when trying to include a resource, the resource-name is being forced camelized here: https://github.com/cloudcreativity/laravel-json-api/blob/develop/src/Eloquent/Concerns/IncludesModels.php#L148 It's even disregarding the name specificed like so:

```php
protected function companyType()
{
    return $this->belongsTo('company_type');
}
```

and calling companyType in the `$query->with()` clause here: https://github.com/cloudcreativity/laravel-json-api/blob/develop/src/Eloquent/Concerns/IncludesModels.php#91

which is an Eloquent model, and not a resource, so it doesn't respond to the resource-naming of the relationship. (Which again is only camelized, because it's being forced in the code the adapters).

If I were to submit a PR to "fix" this, would you accept it?

Cheers

**Comment by lindyhopchris** [comment]
Closing in favour of #315
