### ISSUE TITLE
Trait 'CloudCreativity\JsonApi\Testing\Concerns\HasHttpAssertions' not found

### ISSUE THREAD

**Issue by Snake231088** [cloudcreativity/laravel-json-api#322]
When i launch a test i get this error:
```
Trait 'CloudCreativity\JsonApi\Testing\Concerns\HasHttpAssertions' not found in .../Testing/TestResponse.php on line 35
```

**Comment by lindyhopchris** [comment]
Hi! As per the installation instructions, you'll need to install our testing package:

```bash
$ composer require --dev cloudcreativity/json-api-testing
```

https://laravel-json-api.readthedocs.io/en/latest/installation/

**Comment by lindyhopchris** [comment]
Closing this as I believe the answer above solves your problem. If not, please re-open.
