### ISSUE TITLE
Question: Filter on many to many relationship

### ISSUE THREAD

**Issue by albatarnik** [cloudcreativity/laravel-json-api#324]
Hey, first thanks for the great package. 

I am trying to filter on the pivot table of  a many to many relationship.
So let's say we have tables `articles` , `tags` , `article_tag` 

and I want to filter articles by specific tag and filter article by title
```/api/v1/articles?filter[title]=Hello&filter[tag]=tag_id&include=tags```

I came up with a solution but  I am not sure if it's a good way to do it, I wonder if I can join and filter on the related resource, instead of getting the ids and check using `whereIn`
```
 protected function filter($query, Collection $filters)
    {
        if ($title = $filters->get('title')) {

            $query->where('posts.title', 'like', "{$title}%"); // normal resource filtering , etc...
        }
        if($tag = $filters->get('tag')){
            // this approach works, but I am not sure if there is better way of doing it...
            $articles_ids =  \DB::table('article_tag')->where('tag_id' , $tag)->select('article_id as id)->get()->pluck('id');
            $query->whereIn('articles.id', $articles_ids);

            // tried the join but didn't work, I would imagine using join is more efficient than checking whereIn
            //$query->join('article_tag', 'article.id', '=', 'article_tag.article_id');
            //$query->where('article_tag.tag_id' , '=' , $tag);

        }
    }
```

**Comment by lindyhopchris** [comment]
Hi! Thanks and glad you like the package.

The approach with filters is always to work out how you would do it *without* this package... i.e. how you would just write the database query/queries with Eloquent/Query Builder.

Then it's just a matter of encapsulating that designed query within your filter method.

If you find you can write a query that works outside of JSON API, but doesn't work within JSON API, then I can help to figure out why that might be and make amendments to the package accordingly.

I think you're right that the `whereIn` query will get inefficient, particularly if you end up with lots of articles.

**Comment by albatarnik** [comment]
Thank you, I found a way to customize the query.
