### ISSUE TITLE
Allow registration of catch-all routes on a resource

### ISSUE THREAD

**Issue by lucianholt97** [cloudcreativity/laravel-json-api#327]
I would like to use a 'catch-all' route for actions. The problem is, that queries for relationships are then routed to the action route instead of checking them first.
Would it be possible for you to change the sequence of the routes, so that relationship routes come first?

```
$api
            ->resource('orders', [
                'except' => ['create'],
                'has-one' => ['customer'],
            ])
            ->controller('Api\OrdersController')
            ->routes(function ($order) {
                $order->get('{record}/{action}', 'performAction');
            });
```

**Comment by lindyhopchris** [comment]
I'll have to investigate this, as changing the order of how things are registered feels potentially breaking.

**Comment by lindyhopchris** [comment]
Allocated this to the `2.0` milestone as I'd be very worried about introducing a breaking change if I tried to solve this in the `1.x` series.

**Comment by lindyhopchris** [comment]
Going to close this as it's very old, and I think it's too risky implementing on the this package as I don't want to introduce something potentially breaking at this stage.
