### ISSUE TITLE
Relationship links not working

### ISSUE THREAD

**Issue by Nrko** [cloudcreativity/laravel-json-api#33]
When trying to access the relationship link like so
`/api/v1/answers/1/relationships/question`

I get a 404 status code. 
```
{
  "errors": []
}
```

Is there something I am missing? 

```
GET|HEAD | 
api/v1/answers/{resource_id}/relationships/{relationship_name}   |
api-v1::answers.relationships   |
App\Http\Controllers\Api\AnswersController@readRelationship
```

The route is registered correctly but it is not hitting the readRelationship function.

**Comment by Nrko** [comment]
Forgot to include a $hasOne array in the Request class. 

We really need a wiki here. :)

**Comment by lindyhopchris** [comment]
Yeah, I know. Time is my enemy at the moment but I will get to it!

Glad you managed to work it out in the meantime.
