### ISSUE TITLE
NO ISSUE BUT CONGRATULATIONS!

### ISSUE THREAD

**Issue by Nizari** [cloudcreativity/laravel-json-api#336]
Dear Chris,
Have no other way of doing this, so doing this this way. Have been following this project for months so very happy to see you've reached version 1.0.0! Thank you for all your hard work and dedication :)! Keep up the great work, you give the jsonapi standard hope for all php developers.

**Comment by lindyhopchris** [comment]
Hahaha! Thanks, best issue ever ;-)
