### ISSUE TITLE
Multiple filter values

### ISSUE THREAD

**Issue by Nrko** [cloudcreativity/laravel-json-api#34]
I'm trying to filter my query through multiple filter values like so:

`api/v1/questions?filter[questionType]=questionType1,questionType2`

But apparently this is not supported out of the box. Any guidance on how to achieve this would be appreciated.

**Comment by Nrko** [comment]
Solved it by using this in my Search class:

```
/**
     * @param Builder $builder
     * @param Collection $filters
     */
    protected function filter(Builder $builder, Collection $filters)
    {
        if ($filters->has('questionType')) {
            $questionTypes = explode(",", $filters->get('questionType'));

            $builder->whereIn('questions.question_type', $questionTypes);
        }
    }

    /**
     * @param Collection $filters
     * @return bool
     */
    protected function isSearchOne(Collection $filters)
    {
        return false;
    }
```

**Comment by Nrko** [comment]
Hope these issues help you somehow to build the wiki better.

**Comment by lindyhopchris** [comment]
Yes, I do understand that there needs to be a proper wiki... it's just fitting it in around work deadlines is proving problematic at the moment. I do promise to get to it.

**Comment by Nrko** [comment]
Yeah I do understand that, and by no means I'm trying to put pressure on you. Take your time. I'm just trying to kind of figure it out on my own and if I find a really hard one to figure out then I'll post an issue and eventually a solution, as I also think this might help you remember important parts for the wiki. :)
