### ISSUE TITLE
Updating Relationships in PATCH Request

### ISSUE THREAD

**Issue by lucianholt97** [cloudcreativity/laravel-json-api#340]
I am trying to update relationships within a patch request combined with changed attributes. My request body is:
```
data: {
  type: "users",
  id: "1",
  attributes: {},
  relationships: {
    role: {
      data: {id: "2", type: "roles"}
    }
  }
}
```

According to the schema at https://jsonapi.org/format/#crud-updating-resource-relationships it should look like:
```
"data": {
    "type": "articles",
    "id": "1",
    "relationships": {
      "author": {
        "data": { "type": "people", "id": "1" }
      }
    }
  }
```
Am I doing anything wrong or is this patch method not implemented yet?
Thanks in advance!

**Comment by lindyhopchris** [comment]
No it should work. Your request JSON isn't valid, the keys need to be encapsulated with `"` marks.

If that isn't the problem, you need to let me know what response you're getting - and if it's a `500`, what the stack trace in the error log is.

**Comment by lindyhopchris** [comment]
Oh, you would need to add the `role` relationship to  your adapter... i.e:

```php
protected function role()
{
   return $this->belongsTo();
}
```

**Comment by lucianholt97** [comment]
Adding the role() function to the adapter solved it for me. Thank you for your support!

**Comment by lindyhopchris** [comment]
No problem, glad it worked.
