### ISSUE TITLE
Support for `include` parameter on relationship routes

### ISSUE THREAD

**Issue by k8n** [cloudcreativity/laravel-json-api#346]
According to http://jsonapi.org/format/#fetching-includes:

> Furthermore, related resources can be requested from a relationship endpoint:
> 
> GET /articles/1/relationships/comments?include=comments.author HTTP/1.1
> Accept: application/vnd.api+json
> 
> In this case, the primary data would be a collection of resource identifier objects that represent linkage to comments for an article, while the full comments and comment authors would be returned as included data.
> 

e.g. Calling `/api/v1/matter/1/relationships/contacts?include=address` returns a list of resource stubs, without relations or attributes.

Setting `$includePaths`, `$allowedIncludePaths`, `getIncludePaths()` has no effect. `getRelationships()` seems to be never invoked on the related resource.

Does anyone have an idea how to solve this inclusion problem?

**Comment by lindyhopchris** [comment]
> returns a list of resource stubs, without relations or attributes.

That's correct, `matter/1/relationships/contact` will always return *resource identifiers* - i.e. just the type and id, no attributes or relationships.

If you want the `matter` attributes and/or relationships, use `matter/1/contact`. That does support include paths.

Does that answer the question, or do you want *resource identifiers* with include paths?

**Comment by GIANTCRAB** [comment]
Hi @k8n . If you want your resources to be automatically included without passing the 'include' parameter, you can use `getRelationships()` in your `Schema.php` in the following way:

```php
    public function getIncludePaths()
    {
        return [
            'matter.contacts.address'
        ];
    }
```

I'm assuming that `matter`, `contacts` and `address` are your individual resources/models. Does that help answer your question?

**Comment by k8n** [comment]
Thank you, gentlemen. Those are good pointers.

@lindyhopchris, I was wondering about that route and it’s purpose!

**Comment by Ciaro** [comment]
For people who are missing the include support on relationship routes, there's an open ticket in the parent library @see https://github.com/neomerx/json-api/issues/218

Of what I understood however (by reading some discussions between Chris and neomerx), it will probably take some time before laravel-json-api will switch to v3, as v3 would break quite a bit of our schemas etc.

**Comment by lindyhopchris** [comment]
@Ciaro yeah unfortunately `v3` breaks our entire approach. We'll need to make a decision on whether we hack it to use it, or completely remove the `neomerx/json-api` dependency. Unfortunately both approaches are extremely time consuming, so not sure when we'll be able to move it forward. We'll probably upgrade to `v2` of the neomerx package as an interim step.

**Comment by mathieufrh** [comment]
I am also looking for this feature. Is there some news about it ? In the JSON:API documentation it's a "MAY" feature but it would be useful in some of my projects using laravel-json-api.
