### ISSUE TITLE
Update dependency zendframework/zend-diactoros

### ISSUE THREAD

**Issue by bagoesz21** [cloudcreativity/laravel-json-api#347]
Excuseme, I can't install laravel-json-api coz conflict with` laravel/passport : ^7.2` with dependency `zendframework/zend-diactoros : ~1.0|~2.0`. 
How to solve this problem ?

**Comment by lindyhopchris** [comment]
You've probably already got `v2` of `zend-diactoros` installed already which is causing the conflict.

Try:

```bash
$ composer require cloudcreativity/laravel-json-api:^1.1 laravel/passport:^7.2 zendframework/zend-diactoros:^1.0 --no-update
$ composer up
```

I think that should work for the mo until I release a new version of this package that fixes the `zend-diactoros` constraint in this package (it should be the same as Passport, i.e. `~1.0|~2.0`.

**Comment by naex** [comment]
I had to make recommended steps (to require laravel/passport:^7.2 and zendframework/zend-diactoros:^1.0) and also add http-interop/http-factory-diactoros:^1.0 to handle error with missing factory.
Is it possible to solve the problem with required old library zend-diactoros in the near future? Can I help with it somehow?

**Comment by lindyhopchris** [comment]
Great glad you got it working.

The fix is really simple - I just need to change the `zend-diactoros` dependency in this pacakge so that it's `^1.0|^2.0`... and check that all the tests pass.

Normally I'd take a PR but it's such a small change I'll take care of it this weekend.

**Comment by X-Coder264** [comment]
@lindyhopchris Any chance of tagging a new minor or patch version soon? We need this fix so that we can use this package with Passport (and so that we don't have to use the develop branch version in our composer.json).

**Comment by lindyhopchris** [comment]
Yep, no problem! Was just looking at some of the other bugs, but planning on tagging by COP today (UK time).

**Comment by X-Coder264** [comment]
@lindyhopchris Great. Thank you for the effort and for this great package :+1:

**Comment by lindyhopchris** [comment]
@X-Coder264 just pushed the `v1.2.0` tag.
