### ISSUE TITLE
Route parameter in API URL prefix 

### ISSUE THREAD

**Issue by genyded** [cloudcreativity/laravel-json-api#348]
Our application is tenant based and as such, our root URL has a tenant parameter in it. We have set this in the API config:
```php
...
'url' => [
        'host' => null,
        'namespace' => '/conferences/{tenant}',
        'name' => null,
    ],
...
```
However, the generated URL's in the API resources so not replace this with request()->tenant, they treat it as a literal string:

```
...
links: {
  self: "https://api.epapers.org/conferences/{tenant}/sessions/1",
}
...
```
What class(es)/method(s) might we override to set this value in the resources links? We're digging through source now, but like trying to find a needle in a haystack. BTW - awesome library/project!

**Comment by lindyhopchris** [comment]
Thanks for reporting this. You are right that we totally need to get this working. It's hideously complicated - I don't like that we need that namespace setting but unfortunately that's how the underlying encoder works.

I'll have to think about how we can solve this, but yes - it definitely needs to be solved!!

**Comment by genyded** [comment]
FYI - we've worked around it in an after middleware specific to exact scenario:

```PHP
<?php

namespace App\Http\Middleware;

use Closure;

use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Config;
use App\Models\Conference;

class FixLinks
{
  public function handle($request, Closure $next)
  {
    $response = $next($request);
    $original = $response->getOriginalContent();
    $original = str_replace('/{tenant}', '/'.$request->tenant, $original);
    $response->setContent($original);
    return $response;
  }
}
```
Not ideal, but we know our data with not have that string in it and maybe something like this could be generalized to just target links in the response and replace {param_name} with the request->param_name for the prefix segments. We'd know how many segments the prefix is. If we get time, we may dig further into this and submit a pr.

**Comment by lindyhopchris** [comment]
Yeah as you say, not an ideal solution but glad you've found a temporary fix.

The thing that makes it complicated is it needs to work outside of an HTTP request as well... e.g. encoding payloads for broadcasting. So we need to provide a way for the parameters in the namespace to be set manually, as well as them being set *automatically* for HTTP requests.

Although I'd normally love to receive a PR, I think I need to take a look into this to work out what would be the best way to integrate it. I'm on a break from work over Easter so not quite sure quite when I'll have time to look into it, but hopefully will have an idea by late next week.

**Comment by lindyhopchris** [comment]
@genyded I've pushed a fix to the `issue348` branch. Can you give that branch a go?

```bash
$ composer require cloudcreativity/laravel-json-api:dev-issue348
```

You shouldn't need to make any changes to your code within an HTTP request.

**Comment by genyded** [comment]
Hi,

This seems to address the issue. We disabled our work-around middleware and all links display correctly with the specified route param(s).

**Comment by lindyhopchris** [comment]
Ok well that's good news.

Unfortunately the fix involved changing some method signatures, which means this will have to go into `2.0`. I'm not sure when that will land, as my idea was to work through as many non-breaking issues first.

Are you ok leaving your app tied to that branch for the mo? When would you ideally need a tagged version by?

**Comment by genyded** [comment]
Yes - we're fine for now. Your branch or our work-around will meet our near term needs. We would prefer a tagged version in the next 90-120 days if possible.

**Comment by lindyhopchris** [comment]
@genyded can you switch over to the `2.0` branch? I'm about to tag that as `2.0.0-alpha.1` and then delete the `issue348` branch.

The only different between `v1` and `v2` for `alpha.1` will be:

- I've removed the majority of things that were marked as deprecated (that hopefully won't have too much of an effect on you as most of what was deprecated has been marked as deprecated for ages).
- I've merged in the fix for this issue.

Otherwise I won't make any more substantive changes until `alpha.2` - but it at least gives you a tagged version for the moment.

If you could confirm, that'd be great.

**Comment by genyded** [comment]
Cool! Will try to spend some time on this in the coming week and will let you know.

**Comment by genyded** [comment]
Sorry for the delay. Finally got some time to spend on this and all looks good (we weren't using any deprecated code).

**Comment by lindyhopchris** [comment]
Ah no worries! I'll tag as `2.0.0-alpha.1` in the next day or two.

**Comment by lindyhopchris** [comment]
Just push `2.0.0-alpha.1`
