### ISSUE TITLE
Question: How to handle multipart/form-data

### ISSUE THREAD

**Issue by lucianholt97** [cloudcreativity/laravel-json-api#349]
I am trying to upload an image using the JSON API.
I already added the `ContentNegotiator` resource-specific to the `images` resource.
I followed the docs and added this code in order to accept `multipart/form-data` headers:
```
protected $decoding = [
        'multipart/form-data' => \App\JsonApi\MultipartDecoder::class,
        'multipart/form-data; boundary=*' => \App\JsonApi\MultipartDecoder::class,
    ];
```
At this point I am struggling to find or provide the `MultipartDecoder` class.
Can you explain to me, what I need to do next and how I can retrieve the uploaded file in the controller?

Thank's in advance!

**Comment by lindyhopchris** [comment]
Hi! Yes you'd have to write the `MultipartDecoder` class yourself. Sounds like I need to update the docs to make that a bit clearer and add an example class.

There's an example of what it might sort of be here in the test dummy app:
https://github.com/cloudcreativity/laravel-json-api/blob/develop/tests/dummy/app/JsonApi/FileDecoder.php

**Comment by lucianholt97** [comment]
Thank you for updating the docs.
I also needed to override the data validation function since there was no body with the data object and type attribute in the request.
I switched to uploading the image as base64 encoded string because it‘s much cleaner for me and allows me to pass json data along with the image.
It‘s still good to know that multipart/form-data works, when I need to upload larger files.

**Comment by afrastgeek** [comment]
Hello! I'm sorry for commenting on closed issues.

I looked on file handling on [Avatar resource](https://github.com/cloudcreativity/laravel-json-api/tree/develop/tests/dummy/app/JsonApi/Avatars) in the dummy test. It placed a `create` function on the Adapter, which i try on my case but it never got executed. Shouldn't it be placed on the `AvatarController`?

Below is the error message
```
ERROR: Expecting a resource type. {"exception":"[object] (InvalidArgumentException(code: 0): Expecting a resource type. at ...\\vendor\\cloudcreativity\\laravel-json-api\\src\\Document\\ResourceObject.php:79)
```

**Comment by lindyhopchris** [comment]
Have you also changed the `create` method in your validators class, as per the docs?

**Comment by afrastgeek** [comment]
Oh crap, silly me. That's make it work.
I'm still grasping the concept used in this package

Thank you so much @lindyhopchris

**Comment by lindyhopchris** [comment]
Ah no problem!

**Comment by ijalalfrz** [comment]
Hi @lindyhopchris , i have a question, after following the doc and examle in DummyApp the image upload is working and data saved to database, but the `$document ` param on create method only carry image attribute so i can't validate other attribute. I have also added the validation rule in `rule` method but it's still not working.

```
public function create(array $document): ValidatorInterface
{
        return $this->createValidator(
            $document,
            [
            'logo' => 'required',
            'banner' => 'required',  
            'image' => 'required', 
            'thumb' => 'required', 
            'alt_image' => 'required',
     
            //rest of attribute below is not in $document
            'nama' => 'required',
            'slug' => 'required',
            'excerpt' => 'required',   
            'provinsi' => 'required',    
            'column' => 'required',  
            'position' => 'required',    
            'type_product_id' => 'required',
            'title_page' => 'required',      
            'meta_desc' => 'required',     
            'banner_text' => 'required',   
            'program_id' => 'required'
            ]
        );
}
```
