### ISSUE TITLE
Plan to support has-many-through relationship

### ISSUE THREAD

**Issue by ehdrbs0318** [cloudcreativity/laravel-json-api#351]
In my issue model, issues has related issues relationship such like below
```php
public function issues()
    {
        return $this->hasManyThrough(
            self::class,
            RelatedIssue::class,
            'from_issue_id',
            'id',
            'id',
            'to_issue_id'
        );
    }
```

and issue adapter has json-api relationship
```php
protected function issues(){
        return $this->hasManyThrough('issues');
    }
```

reading related issue(GET issues/{record}/issues, GET issues/{record}/relationships/issues) works fine.
but adding, removing is not working.
this is message
> Modifying a has-many-through Eloquent relation is not supported.

do you have any plans to support has-many-through relationship?

**Comment by lindyhopchris** [comment]
Hi! No plans to support it because the relationship can be created/modified/removed via the intermediary model. I.e. you just represent the *through* model as a resource in your API.

**Comment by ehdrbs0318** [comment]
Hello.
thanks to your comment.
