### ISSUE TITLE
Nested attributes for soft deletes

### ISSUE THREAD

**Issue by JeanLucEsser** [cloudcreativity/laravel-json-api#360]
Hi there,

You've come a long way these last few months, this is impressive work!

I'm using a `status` object as an attribute to hold and manage my `created-at`, `updated-at` and `deleted-at` fields (and *-by as well). It seems like I cannot set the soft delete field accordingly in my adapter:

```
protected $softDeleteField = 'status.deleted-at';
```

As the spec doesn't forbid the use of "nested attributes" or "objects as attributes", I was expecting this to work. Is there a way I could easily fix this? Or am I missing something?

-- Jean-Luc

**Comment by lindyhopchris** [comment]
Ah thanks, glad you like the work!

Makes sense to be able to dot notate this... could you do a PR? I think it'd just be a case of using `Arr::get` somewhere...

**Comment by JeanLucEsser** [comment]
Looks like I can't push my branch to origin, I may doing this the wrong way as this is my first attempt at a PR (gotta start someday right?):

```
Pushing to https://JeanLucEsser@github.com/cloudcreativity/laravel-json-api.git
remote: Permission to cloudcreativity/laravel-json-api.git denied to JeanLucEsser.
fatal: unable to access 'https://JeanLucEsser@github.com/cloudcreativity/laravel-json-api.git/': The requested URL returned error: 403
```

I made the following changes in `SoftDeletesModels` (using Array Helpers has, get and except):

``` php
use Illuminate\Support\Arr;

// ...

    /**
     * @param Model $record
     * @param Collection $attributes
     */
    protected function fillAttributes($record, Collection $attributes)
    {
        $field = $this->getSoftDeleteField($record);
        $attributesArr = $attributes->toArray();

        if (Arr::has($attributesArr, $field)) {
            $this->fillSoftDelete($record, $field, Arr::get($attributesArr, $field));
        }

        $record->fill(
            $this->deserializeAttributes(Arr::except($attributesArr, $field), $record)
        );
    }

 // ...

```

**Comment by lindyhopchris** [comment]
Ah ok, so you need to fork the repo and push the change to your fork.

Then when viewing the fork on Github it'll have links for creating a PR to request merging your changes back into this repo.
https://help.github.com/en/articles/creating-a-pull-request

**Comment by JeanLucEsser** [comment]
So obvious I feel so bad...
As it's not really a bug but more of an enhancement I made the PR on develop.
Is that ok?

**Comment by lindyhopchris** [comment]
Spot on - PR should be on develop for exactly that reason! Just taking a look at the PR now

**Comment by lindyhopchris** [comment]
Closed via #361 

Will be in next release - `v1.2.0`

**Comment by JeanLucEsser** [comment]
Thanx!

Should you prefer this approach, I'm using `mapWithKeys` to test for array, call `fillSoftDelete`, and remove the properties from attributes accordingly:

```
    /**
     * @param Model $record
     * @param Collection $attributes
     */
    protected function fillAttributes($record, Collection $attributes)
    {
        $attributes = $attributes->mapWithKeys(function ($item, $key) use ($record) {
            $field = $this->getSoftDeleteField($record);

            if ($key === strtok($field, '.')) {
                if (is_array($item) && Arr::has($item, $k = strtok(null))) {
                    $this->fillSoftDelete($record, $field, Arr::get($item, $k));
                    return [$key => Arr::except($item, $k)];
                } else {
                    $this->fillSoftDelete($record, $field, $item);
                    return [];
                }
            }

            return [$key => $item];
        });

        $record->fill(
            $this->deserializeAttributes($attributes, $record)
        );
    }
```

I can do another PR, your call.

**Comment by lindyhopchris** [comment]
Ah thanks for the suggestion but think it's ok to stick with the version I merged... it was just the perfectionist in me trying to avoid an extra variable assignment! but all good!

thanks for suggesting this feature - it's a good one to add in!
