### ISSUE TITLE
Laravel 5.4 support ?

### ISSUE THREAD

**Issue by mspiderv** [cloudcreativity/laravel-json-api#37]

**Comment by asantiago** [comment]
No.... I tried yesterday.... 5.3.9 maximun.

**Comment by lindyhopchris** [comment]
Hi! Yes, I need to add it in. Because Laravel does not follow semver, I've tied this package to specific versions so that if a new version comes out I can check it's working with the new version first.

I might be able to look at this today.

**Comment by jstoone** [comment]
@lindyhopchris I'm working on a pull request right this moment, so if you hang on for an hour or two then we can take a look at it together when reviewing. :)

**Comment by lindyhopchris** [comment]
@jstoone  Ah, sorry, just pushed some changes to `develop` - hadn't seen your message.

Here's what I had - happy to take a PR for anything else I might have missed as I've only tested this in the demo app:
https://github.com/cloudcreativity/laravel-json-api/commit/23e4fbcb2016b3dd70f0074cf97a00e44852b9c9

For info, you have to use the BrowserKit test case for the testing to still work.

**Comment by lindyhopchris** [comment]
It'd be nice if the changes also worked in <5.4 which I think these might

I'm starting to get a bit fed-up with Laravel's approach to versions - the breaking changes mean it's really difficult to support older versions. I'm thinking after 5.4 I might have to switch this package to having a new version each time there's a new Laravel version, which would mean that to use the latest version of this package you'd always have to be on the latest version of Laravel. Any thoughts?

What does worry me is that the next Laravel is dropping support for PHP 5.6, which is a right pain as I've got applications that are going to be on PHP 5.6 probably until 5.6 is end of life.

**Comment by jstoone** [comment]
Yea, it's unfortunate that it doesn't follow SemVer, but other packages that are coupled with laravel increment their major version for each new Laravel major version. In this way once the package looses backwards compatibility  you can add a note to the readme.

This adds cleaner code to each release branch, but it also might add some redundancy when it comes to maintaining and applying feature to older versions. But it has to be a conscious choice. Whether we should maintain older versions with new features.

**Comment by lindyhopchris** [comment]
all good points!

let me know when you've had a chance to try the `develop` branch in L5.4, because if it's working then I can tag it and update the readme

**Comment by jstoone** [comment]
@lindyhopchris I've just started upgrading our API, I'll keep you posted!

**Comment by lindyhopchris** [comment]
@jstoone i think this is good to merge, unless you've hit any showstoppers?

**Comment by jstoone** [comment]
@lindyhopchris yea, sorry for my slow feedback, figured out we had a lot of dependencies that needed to be upgraded/replaced which included our entire oauth system, which I'm porting to Passport. But I've had no problems with `laravel-json-api`, that was pretty straight forward. :)

So yea, I'd agree it's ready for a merge.

**Comment by furqanaziz** [comment]
We are eagerly waiting for this state of art package for Laravel 5.4.

**Comment by asantiago** [comment]
I have finished making a fork with the few functionality that I use adapting it for my cases, there was too much changes to upgrade without continuity garanty... Thank you very much for the package but I think it has not enough support....

**Comment by mspiderv** [comment]
So, will this package support 5.4 or not ??

**Comment by lindyhopchris** [comment]
@mspiderv yes, it will be updated. the work is done on the develop branch, I need to merge and tag it. I'm away this weekend so will do that on Monday morning.

Apologies for the delay, it's entirely down to other work priorities rather than not wanting to support this package.

@asantiago the package is supported and we have plans for improving it. Like any company though with commercial work deadlines, the time we can spend on it is obviously dependent on those deadlines. 

It's great that people are using this package. We welcome contributions and will happily accept PRs. Supporting an open source project via contributions is the best way to support its growth and help it mature.

**Comment by lindyhopchris** [comment]
Version 0.6 released, with a very minor upgrade required (see the `UPGRADE.md` file).

To update:

```bash
$ composer require cloudcreativity/laravel-json-api:^0.6 --update-with-dependencies
```
