### ISSUE TITLE
Multiple API's and Accept Header

### ISSUE THREAD

**Issue by danny-allen** [cloudcreativity/laravel-json-api#374]
Hi there, I don’t know if this is a bug, or just a configuration issue on my part… I’m trying to setup multiple API’s on the same Laravel installation. It seems that the `Accept` headers are not checked on either API. I’m not sure if this issue was introduced when I added the second API or happened before - I do recall seeing 406 errors at one point. With the one API, I added the `LaravelJsonApi::defaultApi(‘api1-v1’);` line to the `AppServiceProvider`. Now I’m working on a second API, it’s not clear to me what defaultApi value should be. 

Both API’s have the config values `encoding` and `decoding` set to `application/vnd.api+json`. 

If I make a GET request without the `Accept` header, it makes no difference. The requests returns data with status code of 200. 

I’ve registered the APIs in route files like:

```
// api1.php
JsonApi::register(‘api1-v1')->routes(function (RouteRegistrar $api) {
    // Resources…
});
```
and…

```
// api2.php
JsonApi::register(‘api2-v1')->routes(function (RouteRegistrar $api) {
    // Resources…
});

```

They both use the api middleware and are accessed via separate subdomains with different namespaces (done via RouteServiceProvider).

Any help would be much appreciated! It really is a great package, that saves so much time, so thanks for all the hard work! :)

**Comment by lindyhopchris** [comment]
Hey! Glad you're finding the package useful and thanks for reporting this. To be honest, I don't know immediately whether it's a bug or a set up problem.

The `JsonApi::defaultApi()` is provided as a helper... so that if you don't specify an API (e.g. when using the `make::json-api` commands), it uses that default name. In an HTTP request once you've passed the JSON-API middleware it's ignored because the API name for the HTTP request is known at that point (or at least that's the idea).

When you say that you're not getting a `406` response, is that the case when you do send an `Accept` header with a bad type - e.g. `Accept: text/xml`? I'm wondering whether no Accept header is being interpreted as `*/*`, which of course would pass for JSON API as the client has said give me anything!

So if you could just confirm what exactly it does with both APIs when a non-JSON API `Accept` header is sent, that would help.

**Comment by danny-allen** [comment]
Thanks for the speedy response! So I ran a couple of tests. If I have no headers, as described above, it works. If I set the `Accept` header to `invalidheader`, I get a `500 Internal Service Error` with an exception thrown as an HTML page: `JSON API error` originating from `/var/www/vendor/neomerx/json-api/src/Http/Headers/HeaderParametersParser.php:79` - is this the expected response because its not a valid mime-type?

I have found that if I set the `Accept` header to `text/xml` I do in fact get a `406 Not Acceptable` status code. The non JSON API spec response threw me, but I see the reason [documented here](https://laravel-json-api.readthedocs.io/en/latest/features/media-types/#accept-header).

I've checked the headers at the point at which the controller is hit, and the `accept` key does indeed have a value of `*/*`. So I assume, by what you are saying, that this part is also correct - it's the default value, which means accept anything? I think my confusion was around thinking that this package required the Accept header and had to match one of those configured in the config file, but that doesn't seem to be the case, therefore, I don't think there's a bug - just a lack of understanding on my part!

If you could confirm the above, that would be great. Thanks for your time!

**Comment by lindyhopchris** [comment]
About to run into a meeting, but think the problem might be your Exception handler is missing the `prepareException()` override shown here:
https://laravel-json-api.readthedocs.io/en/latest/installation/

I had to add that to handle this kind of scenario.

**Comment by danny-allen** [comment]
No worries! No rush. I've added that in, and setting a bad `Accept` header like `invalidheader` now gives me a `400 Bad Request` which seems logical. It also provides the error in HTML, is that expected?

**Comment by lindyhopchris** [comment]
Yeah it'd give you it in HTML because that's Laravel's default if you haven't requested JSON. I.e. it's not going to give you a JSON API error if your accept header doesn't allow JSON API.

**Comment by danny-allen** [comment]
Great! I guess it's all resolved then. Thanks very much for the help on this!

**Comment by lindyhopchris** [comment]
No problem!
