### ISSUE TITLE
Pagination: Disabling pages count

### ISSUE THREAD

**Issue by rekrios** [cloudcreativity/laravel-json-api#377]
Hi. Sometimes we need to disable estimation amount of pages for pagination and don't want to change pagination strategy just for this. 
I have extended StandardStrategy class and wrote 
```
public function withoutSimplePagination()
{
   $this->simplePagination = false;

    return $this;
}
```

Maybe there are some other ways for 'StandardStrategy' for my needs ? Or Can you add Set-action for 'simplePagination' param ?

**Comment by lindyhopchris** [comment]
Hi! Not sure I totally understand this... the `StandardStrategy` does not use simple pagination, but you can change it already by calling the `withSimplePagination()` method.

Are you saying you also need a `withoutSimplePagination()` method? If so, I'd happily take a PR to add that in!

**Comment by rekrios** [comment]
Our case: By default we made abstract adapter where for faster responses we enabled simple pagination.

    public function __construct($resource, $paging = null)
    {
        parent::__construct($resource, $paging->withSimplePagination());

But sometimes we need to count real amount of pages, so we were forced to write something like this in the 'filter' method

`$this->paging->withoutSimplePagination();`

P.S. Maybe method name like 'withoutSimplePagination' not very nice, it's as you wish)

**Comment by lindyhopchris** [comment]
Ok great. Maybe `withLengthAwarePagination()`, as that's what Laravel calls it?

Could you submit a PR against the `develop` branch?

**Comment by rekrios** [comment]
"submit a PR" it's make fork from 'development' branch, make changes and create pull request to merge with 'development' branch or what ?

**Comment by lindyhopchris** [comment]
Yes that's right!
https://help.github.com/en/articles/creating-a-pull-request-from-a-fork
