### ISSUE TITLE
Get only the resources related to user

### ISSUE THREAD

**Issue by mdegouw** [cloudcreativity/laravel-json-api#383]
```
users
    id - interger
    name - string
    email - string
    password - string
	
company_user
    user_id - interger
    company_id - interger

companies
    id - integer
    name - string

venues
    id - integer
    company_id - integer
    name - string
```

Users<->Companies  - Many to Many
Company<->Venues - One to Many

I use laravel/passport for auth.

Is there a way to only show the companies that the currently logged in user has access to?
If this is possible is there than a way to go deeper and get the venues that the user has access to?

**Comment by lindyhopchris** [comment]
Hi! You want to use the new global scopes feature that was added in `v1.2.0`:
https://laravel-json-api.readthedocs.io/en/latest/basics/adapters/#scopes

I.e. add a scope to the `companies` JSON API adapter, and the `venues` adapter, that ensures that only companies/venues the user has access to are returned.

In terms of working out what the Eloquent queries are, that's outside the scope of this package... as in the scope can support any queries you need.

If this answers your question, please close the issue!
