### ISSUE TITLE
ResourceNotFoundException

### ISSUE THREAD

**Issue by mdegouw** [cloudcreativity/laravel-json-api#384]
This is a follow up of: #283 

Filtering the data based on the logged in user works great.
```
public function apply(Builder $builder, Model $model)
    {
        if (\Auth::check()) {
            $builder->whereHas('users', function (Builder $query) {
                $query->where('user_id', \Auth::id());
            });
        }
    }
```
But if i go to an endpoint that the user doesn't have access to example: `companies/2`
I get an `CloudCreativity\LaravelJsonApi\Exceptions\ResourceNotFoundException` with the following response: 
```
{
    "message": "Resource companies with id 2 does not exist."
}
```
debug=false

From what i can see the scope gets executed before any hooks, so is there a way to return a valid jsonapi error 403 Unauthorized?

P.S.
This is the exception handler
```
<?php

namespace App\Exceptions;

use Neomerx\JsonApi\Exceptions\JsonApiException;
use CloudCreativity\LaravelJsonApi\Exceptions\HandlesErrors;
use Exception;
use Illuminate\Foundation\Exceptions\Handler as ExceptionHandler;

class Handler extends ExceptionHandler
{
    use HandlesErrors;

    /**
     * A list of the exception types that are not reported.
     *
     * @var array
     */
    protected $dontReport = [
        JsonApiException::class,
    ];

    /**
     * A list of the inputs that are never flashed for validation exceptions.
     *
     * @var array
     */
    protected $dontFlash = [
        'password',
        'password_confirmation',
    ];

    /**
     * Report or log an exception.
     *
     * @param  \Exception  $exception
     * @return void
     */
    public function report(Exception $exception)
    {
        parent::report($exception);
    }

    /**
     * Render an exception into an HTTP response.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \Exception  $exception
     * @return \Illuminate\Http\Response
     */
    public function render($request, Exception $exception)
    {
        if ($this->isJsonApi($request, $exception)) {
            return $this->renderJsonApi($request, $exception);
        }

        return parent::render($request, $exception);
    }

    protected function prepareException(Exception $e)
    {
        if ($e instanceof JsonApiException) {
            return $this->prepareJsonApiException($e);
        }

        return parent::prepareException($e);
    }
}

```
The $this->isJsonApi check returns False.

**Comment by lindyhopchris** [comment]
Yes, this is covered in the docs here:
https://laravel-json-api.readthedocs.io/en/latest/basics/adapters/#scopes

Basically if you use a scope, the filtered-out resources do not exist in the API, so a `404` response is correct. I.e. from the client's perspective, any resources belonging to a different user do not exist, so it never sees them (and gets `404`).

If you want the client to know that they exist but get a `403 Forbidden`, then scopes aren't the right choice... you'd need to use Authorizers (see the Security chapter in the docs) to deny access to them.

**Comment by lindyhopchris** [comment]
Closing this as I believe I've answered the question. Feel free to re-open if you feel you need more info!!
