### ISSUE TITLE
problem with hooks

### ISSUE THREAD

**Issue by ehsan5** [cloudcreativity/laravel-json-api#385]
hello 
my problem is complex but describe in simple
see code in myadapter

 protected function saved(Test $test)
    {
        $test2= new Test2();
        $test2->name = "test";
        $test2->save();
        die("stop please");
    }

why $test2 not saved in database?

**Comment by lindyhopchris** [comment]
Hi! The request is executed within a database transaction, so if you `die` it won't be committed to the database.

Otherwise, you'll need to debug this within your own application - there's far too little in the above for me to debug it for you... sorry!

**Comment by ehsan5** [comment]
thank you for your anser,
just tell me where transaction will done ?so I want run function after data saved

**Comment by fisharebest** [comment]
Transactions are handled by middleware.

**Comment by ehsan5** [comment]
I want run function after all finished and data updated.How I can?

**Comment by lindyhopchris** [comment]
actually in this package transactions are run in the JSON API controller. I'm planning to move them to middleware in the next major version as the controller implementation isn't nice!

But yeah, for the moment take a look at this package's `Http\Controllers\JsonApiController::transaction()` method.

**Comment by lindyhopchris** [comment]
Closing this as I think the question has been answered. Please re-open with more specific info if you are still having problems.
