### ISSUE TITLE
URL host not used

### ISSUE THREAD

**Issue by dleeram** [cloudcreativity/laravel-json-api#387]
Hi,

I'm registering all my API routes to a sub-domain. e.g. `http://api.localhost` and all my non-API routes to the root domain. e.g. `http://localhost`.
Everything works fine, but running tests with the helpers provided fails because it tries to make requests to the wrong URL.

Looking at: https://github.com/cloudcreativity/laravel-json-api/blob/7c2c1a8a746e0dfc50934f495553fd291aa1d4a9/src/Testing/MakesJsonApiRequests.php#L769-L773
Only the namespace it's passed to `prepareUrlForRequest`. It's easy to solve this by just assigning before `baseApiUrl` to the host desired plus namespace, but it's not ideal in case you change the namespace in the configuration later on.

Passing `URL` to string seems to work and I think it's more appropriate because the variable's name. I don't know if this is desired behavior and any help would be very much appreciated. Thanks!

**Comment by lindyhopchris** [comment]
Hi!

Yes this is an edge case that I know doesn't work for those test helpers. You want to use the `getJsonApi()`, `postJsonApi()` etc methods instead - as you can pass the actual URI for those.

I'm likely to deprecate the `do*` test helpers for exactly this reason at some point and just recommend using the more normal `get/post` etc ones instead.

**Comment by dleeram** [comment]
Oh, I see... I'll use those functions then. Thanks for the help!

**Comment by lindyhopchris** [comment]
No problem! Of course let me know if you encounter any other problems.
