### ISSUE TITLE
SoftDelete

### ISSUE THREAD

**Issue by rekrios** [cloudcreativity/laravel-json-api#394]
Hello.
I think you can get error here, isn't it ? https://github.com/cloudcreativity/laravel-json-api/blame/v1.3.0/src/Eloquent/Concerns/SoftDeletesModels.php#L153
Something like 
```Call to undefined method ........::getDeletedAtColumn()```
Maybe you should make checking for trait or something else...
```isset(class_uses($model)[\Illuminate\Database\Eloquent\SoftDeletes::class])```

**Comment by lindyhopchris** [comment]
I don't think that's necessary as use of the `SoftDeletesModels` is completely optional... i.e. you shouldn't be adding it to an adapter for a model that cant be soft deleted.

**Comment by lindyhopchris** [comment]
Just like you only add the Eloquent `SoftDeletes` trait to the models that actually have a soft delete column

**Comment by rekrios** [comment]
Thanks. Forgot it's optional)

**Comment by lindyhopchris** [comment]
No problem!
