### ISSUE TITLE
Returning currently logged in user

### ISSUE THREAD

**Issue by ExpDev07** [cloudcreativity/laravel-json-api#396]
Hey, I am setting up my routes as such:
```php
JsonApi::register('default')->middleware('auth:api')->routes(function (RouteRegistrar $api, $router) {
    // Users resource.
    $api->resource('users')->relationships(function ($relations) {
        $relations->hasOne('player');
    });
});
```

How would I go about easily doing so that if the user hits `GET /api/v1/users?me=true`, it would return the user that sent the request using the api_token? I know Laravel offers request()->user(), but I don't know how to use that with the resource I've defined for users. Would there be a simple approach to this? I read the "Security" section in the documentation, but found only so little that helped me. 

Any help would be appreciated, thanks!

**Comment by lindyhopchris** [comment]
Hi! If you want to support `/api/v1/users?me=1` then in your `users` adapter, overload the `query()` method:

```php
    public function query(EncodingParametersInterface $parameters)
    {
        if (request()->get('me')) {
            return request()->user();
        }

        return parent::query($parameters);
    }
```

**Comment by ExpDev07** [comment]
Fuck, it was THAT easy????? Love your library dude. Only reason I'm using Laravel for my backend :).

**Comment by lindyhopchris** [comment]
hahaha! thanks!

**Comment by o15a3d4l11s2** [comment]
I have a very similar use-case, but instead of `GET /api/v1/users?me=true` I would like to do a `GET /api/v1/users/me`. I already have the `$server->resource('users', UserController::class)` resource configured and it works properly with user id, but I would like to enable also the "magical" `/me`. Any hints?
