### ISSUE TITLE
Question: How to do some action before delete method?

### ISSUE THREAD

**Issue by ijalalfrz** [cloudcreativity/laravel-json-api#398]
Hi , I really appreciate your work for this package and i'm wondering how to do some action before delete method? I have added delete method in adapter but it's still not working, this is what i've tried.

```
    public function delete($record,EncodingParametersInterface $parameters)
    {
        //some action here
        return parent::delete($record, $parameters);
    }
```

**Comment by lindyhopchris** [comment]
Hi!

Have you tried using the `deleting` adapter hook:
https://laravel-json-api.readthedocs.io/en/latest/basics/adapters/#adapter-hooks

**Comment by lindyhopchris** [comment]
Closing this as the answer above should be sufficient. Please re-open with additional information if not.
