### ISSUE TITLE
Adapter  Error

### ISSUE THREAD

**Issue by amgueye** [cloudcreativity/laravel-json-api#399]
I registered a user resource in my json-api-default.php

    'resources' => [
        'users' => \App\Repositories\UserRepository::class,
    ]

I also have the following configuration for namespace and by-resource

    'namespace' => 'App\Api',
    'by-resource' => true,

I created an adapter and a schema for users resources which are located in App\Api\Users

When I try the following request /api/users/1 I get the error below 

[2019-08-16 10:49:58] local.ERROR: Class [App\Api\Users\Adapter] is not a resource adapter. {"exception":"[object] (CloudCreativity\\LaravelJsonApi\\Exceptions\\RuntimeException(code: 0): Class [App\\Api\\Users\\Adapter] is not a resource adapter. at [project-folder]/vendor/cloudcreativity/laravel-json-api/src/Container.php:378)
[stacktrace]

Do you know why I am getting this error ?

The error come from the Class cloudcreativity/laravel-json-api/src/Container.php:378

    /**
     * @param $className
     * @return ResourceAdapterInterface
     */
    protected function createAdapterFromClassName($className)
    {
        $adapter = $this->create($className);
        if (!$adapter instanceof ResourceAdapterInterface) {
            throw new RuntimeException("Class [$className] is not a resource adapter.");
        }
        return $adapter;
    }

**Comment by amgueye** [comment]
I found the problem. I was wrong in the namespace in users adapter.

**Comment by lindyhopchris** [comment]
No problem, glad you found the solution!
