### ISSUE TITLE
Class 'CloudCreativity\JsonApi\Integration\EnvironmentService' not found

### ISSUE THREAD

**Issue by nickelozz** [cloudcreativity/laravel-json-api#4]
Hey there @lindyhopchris it's been a while,

I've been using this package for a few weeks now but from time to time...when performing some changes on my L5 app I get an error like this in my log:

```
[2015-11-27 12:08:12] local.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class 'CloudCreativity\JsonApi\Integration\EnvironmentService' not found' in /opt/admysis/panel-webserver/webserver/vendor/cloudcreativity/laravel-json-api/src/Integration/LaravelEnvironment.php:32
Stack trace:
#0 {main}  
```

I already know it's not your package's fault but rather something I did wrong that broke the app (e.g. wrong namespaces most of the times)....but instead of getting the corresponding error information I only get that 1 error and I'm left uncertain as for what it was that went wrong really. I've checked inside the file ```CloudCreativity\JsonApi\Integration\LaravelEnvironment``` and this is what I found:

```php
<?php

namespace CloudCreativity\JsonApi\Integration;

use CloudCreativity\JsonApi\Integration\EnvironmentService as BaseService;

// ...

class LaravelEnvironment extends BaseService
{

// ...
```

Now, personally I have no clue how that gets resolved since I couldn't find such a class ```EnvironmentService``` but I wonder if there is any way to avoid getting that error message instead of the corresponding error that caused my app to break. Any thoughts on that?

**Comment by lindyhopchris** [comment]
Hi @nickelozz 

You're right that this isn't an issue with this package but I have some ideas that might help you out.

Composer takes care of the auto-loading of classes. The missing class you've got there is from the `cloudcreativity/json-api` package (which is my framework agnostic package on which the `laravel-json-api` package builds). You should find it in the following location within your application:

`vendor/cloudcreativity/json-api/src/Integration/EnvironmentService.php`

If your Laravel app is occasionally loosing classes, it might be something to do with the optimisation that Laravel runs. Maybe try running the following:

``` bash
php artisan clear-compiled
php artisan optimize
```
That might solve it. Those commands should run automatically after a composer install/update if you have the following in your `composer.json`:

``` json
"scripts": {
        "post-install-cmd": [
            "php artisan clear-compiled",
            "php artisan optimize"
        ],
        "post-update-cmd": [
            "php artisan clear-compiled",
            "php artisan optimize"
        ]
    }
```

That is normally included in the composer.json if you've used a standard Laravel starting application.

Not sure whether any of that will solve your problem but it's my best first guess!

**Comment by nickelozz** [comment]
Hey @lindyhopchris thanks for the pointers!

Sorry for not writing sooner but I've been very occupied with work lately.

I managed to fix that particular issue I was having by deleting the vendor folder and then using ```composer update --no-scripts```.

I have no clue what was causing that error since I hadn't touched the vendor folder or the ```composer.json``` file which by the way does have the "scripts" section you mentioned.

I haven't had any further occurrence of it so far so I'm closing this issue now but if I happen to stumble upon it in the future I'll post a comment on here.

Thank you so much!
