### ISSUE TITLE
Include eloquent model on included

### ISSUE THREAD

**Issue by tylergets** [cloudcreativity/laravel-json-api#40]
Hey guys, ive been struggling with these for an hour or so now. I have my searcher returning my "Tracks" model, with its tag IDs included. It's not including the tag data, such as its name, in the response. Is this possible?

This is all I am doing:
```
    return [
            'tags' => [
                self::DATA         => $resource->tags,
            ]
        ];
```

**Comment by dmitry-php** [comment]
Hi @tylergets !
Sure it's possible. You just need to use include GET parameter and add allowedIncludePaths property to your Request class

**Comment by dmitry-php** [comment]
So it will be something like http://yourhost.com/api/v1/tracks?included=tags

**Comment by lindyhopchris** [comment]
Hey @tylergets 

As @dmitry-php says, in your request object for `tracks` add `$allowedIncludePaths = ['tags']`. Then in the request from the client you need to include an `?include=tags` as per the JSON API spec here:
http://jsonapi.org/format/#fetching-includes

If you want to set default include paths that are used if the client does not specify any, then implement the following method on your `tracks` Schema:
https://github.com/neomerx/json-api/blob/master/src/Schema/SchemaProvider.php#L227

E.g. to always include `tags` if the client doesn't specify any include paths via the query param:

```php
public function getIncludePaths()
{
    return ['tags'];
}
```

**Comment by tylergets** [comment]
Thanks guy, this got me through my initial problem. Now question for you @lindyhopchris, setting the getIncludePaths method works when its the main resource, is it possible to include the tags models when hitting for example, a "Playlist" endpoint that returns the tracks?

**Comment by jstoone** [comment]
@tylergets yes, let's say you're querying `GET /api/v1/playlists/1/tracks?include=tags`, you should add `tags` to your `playlists` resource, just as you did on your `tracks` resource.

Hope it helps!

**Comment by lindyhopchris** [comment]
@tylergets the include path is always relative to the main resource(s). So for playlists, the include path would be `tracks.tags`

**Comment by lindyhopchris** [comment]
Closing this as it's quite old now and I think the questions were answered. Feel free to open a new issue if needed.
