### ISSUE TITLE
Authorizer always returns the User as record

### ISSUE THREAD

**Issue by katerss1** [cloudcreativity/laravel-json-api#403]
Hi Chris,

I have created a resource named **Matches**.
When I do a **GET** REQUEST to the endpoint 

> /v1/matches

 I want to authorize somehting based on the the given Match.

**Authorizer**

```
public function index($type, $request)
{
  $this->can('view', $type, $request);
}
```

**MatchPolicy**

```
public function view($record, $request)
{
  eval(\Psy\sh()); //debugger
}
```
When I check the `$record` inside the view I always get an User back instead of a Match.
Can you help me get the Match model back?

Thx for your time :)

**Comment by lindyhopchris** [comment]
Hi!

On the policy, Laravel always passes the current signed in user as the first function argument. So the match will be the second argument, the request the third.

Hope that helps!

**Comment by katerss1** [comment]
```
public function view($record, $match, $request)
{
  eval(\Psy\sh()); //debugger
}
```
So something like this?

**Comment by lindyhopchris** [comment]
So should be `$this->can('view', $record);`

Then your policy will receive the `view(User $user, Match $match)`.

The request is provided to the authorizer in case you need to make any decisions about which Laravel policy method to call, not to pass it to the policy (as that's not standard Laravel practice).

**Comment by katerss1** [comment]
```
   public function index($record, $request)
    {
        $this->can('view', $record);
    }
```

```
    public function view(User $user, Match $match)
    {
        eval(\Psy\sh());
    }
```

--------
Tried this but doesn't seem to work. 

I get this error:

` Too few arguments to function App\Policies\MatchPolicy::view(), 1 passed in`

**Comment by katerss1** [comment]
Still having the same issue, any idea?

**Comment by lindyhopchris** [comment]
Hang on, you're doing this for the `index`?? that's for reading all matches, not a specific match. Reading a specific match is the `read()` method on the authorizer.
