### ISSUE TITLE
Security: allowed attributes

### ISSUE THREAD

**Issue by rekrios** [cloudcreativity/laravel-json-api#405]
Hi again) I want to make sure of something...
So, right now, if someone uses the same Model and will extend "protected $fillable ... " with some additional params, then anyone can update this params from jsonapi without validation ?
If so, then my possible solutions:
1) create folder like jsonapiModels and place there extended models with overrided "protected $fillable ... " just for jsonapi
2) maybe add "allowed attributes" in the jsonapi library
Asking coz we can use the same models for other purpose and want to make sure of this question.

**Comment by lindyhopchris** [comment]
The Eloquent adapter has properties on it for setting what JSON API fields are fillable, and which aren't. Does that not work in this case?
https://laravel-json-api.readthedocs.io/en/latest/basics/adapters/#mass-assignment

**Comment by rekrios** [comment]
> The Eloquent adapter has properties on it for setting what JSON API fields are fillable, and which aren't. Does that not work in this case?
> https://laravel-json-api.readthedocs.io/en/latest/basics/adapters/#mass-assignment

oh thanks, was searching for them in the wrong place
