### ISSUE TITLE
Missing hasOneThrough relationship in adapter

### ISSUE THREAD

**Issue by katerss1** [cloudcreativity/laravel-json-api#415]
Is there a hasOneThrough relationship already?
https://laravel-json-api.readthedocs.io/en/latest/basics/adapters/

**Comment by lindyhopchris** [comment]
It's not mentioned in the docs as I don't think it existed in Eloquent when I wrote them.

It might work with the JSON API `hasOne` relationship... can you give that a go? If it doesn't work I'll need to add it.

**Comment by franco9700** [comment]
i had the same problem. I need the hasOneThrough but i don't know how to specify it on the adapter

**Comment by lindyhopchris** [comment]
can someone do a PR? that would help!

also, have you tried using a JSON API `hasOne` relationship? Does it work?

**Comment by lindyhopchris** [comment]
Anyone want to give this a go on the `feature/has-one-through` branch before I merge?

Note that the relationship has to be read-only: like has-one-through, the intermediary resource should be created/modified/deleted to change the relationship.

**Comment by lindyhopchris** [comment]
@jstoone thanks!

**Comment by lindyhopchris** [comment]
Released as `1.5.0`
