### ISSUE TITLE
Validate related resource: belongs to user

### ISSUE THREAD

**Issue by rekrios** [cloudcreativity/laravel-json-api#417]
Hello ;)
Please show me the right way... How to check that related resource belongs to the currently authorized user on create(POST) query ?
I tried something like this
```
    protected function rules($record = null): array
    {
        return [
            'someRelationship.user.id' => 'in:' . Auth::user()->id,
        ];
    }
```
But it didn't work

**Comment by rekrios** [comment]
I can find a way only like this...
```
  protected function rules($record = null): array
    {
        return [
            'someRelationship' => function($entityName, $params, $fail) {
                if (SomeModel::find($params['id'])->user->is(Auth::user())) {
                    $fail('should_belong_to_user');
                }
            },
        ];
    }
```

**Comment by lindyhopchris** [comment]
So this is no different from how you would write it for any other Laravel validator. 

If your JSON API relationship field is `author` then:

```php
    protected function rules($record = null): array
    {
        return [
            'author.id' => 'in:' . Auth::id(),
        ];
    }
```

**Comment by lindyhopchris** [comment]
You should probably consider your API design though. If the relationship can only ever be set to the current signed in user, it probably doesn't make sense to use the value submitted by the client. In these scenarios I'd set the relationship as not fillable on the adapter, and use the adapter `creating/updating` hooks to set the user relationship using `Auth::user()`.

**Comment by rekrios** [comment]
Client can send different id's of resource in relationship. Some are belongs to current user, some - not.
It's like Posts from few different users where u can attach something only to your posts

**Comment by rekrios** [comment]
Seems like we have only what was send by client in that relationship and we can't move through chain of relationships. 

Ideas: maybe we should load somehow related models in advance and then we can move through them coz we have only client's request for this rules.

**Comment by lindyhopchris** [comment]
Ah ok, sorry misunderstood.

Just use an `exists` rule to validate `someRelationship.id`, using the exists rule to ensure it exists with the current user's id.

**Comment by lindyhopchris** [comment]
@rekrios closing this as I think the `exists` rule solves your question. If it doesn't can you re-open with more details? Thanks.

**Comment by rekrios** [comment]
@lindyhopchris thx,ok
