### ISSUE TITLE
Translate some Exceptions into a JSON:API error response

### ISSUE THREAD

**Issue by tembra** [cloudcreativity/laravel-json-api#420]
Hello @lindyhopchris 

How would you translate a Laravel `QueryException` into a JSON:API error response?

I know that we must use `Exceptions\Handler.php` for this, but how would you code this?

Currently the API is just responding with a 500 Internal Server Error. I would like to translate some SQL errors like `[23503] violates foreign key constraint` to let the user known what to do instead of simple get an internal server error.

I know that I can simple create a new Error object an return it JSON:API encoded. However do you have/use `json_api()->response()->exception($e);` and I want to know if I can make some use of it for my use case.

Thank you.

**Comment by lindyhopchris** [comment]
So I'd question why you're letting invalid data hit the database... the convention here would be to use validation rules to reject the data *before* it is attempted to be inserted. I.e. for foreign key constraints, your validation should pick up on this and reject the request at the validation point - then you can use validation messages to provide the correct information to the client.

A `500 Internal Server Error` is the correct response for a `QueryException`.

Can you not use rules e.g. `exists` for your scenario?

**Comment by tembra** [comment]
@jstoone I'm not talking about tests. It's about to deliver a message for the consumers of API. But I got your point. Thx.

@lindyhopchris Understood and totally agree with you. I was thinking to use exception handler to translate this type of error because we may have a lot of resource where the front end must first delete the related resources before delete the main resource. However the best way to lead with this is to follow the convention you told: use rules to reject the request before it's process. BTW I can not use validation rules because it's on `DELETE` endpoint.

Finally I was right to post the question here to get your and the community's opinion on how to handle this case 😄 

Thanks once.

PS: We use these foreign keys as `restrict` mode on purpose in our database.

**Comment by lindyhopchris** [comment]
Actually this package does support delete validation, here's the link to it in the docs:
https://laravel-json-api.readthedocs.io/en/latest/basics/validators/#delete-resource-validation

Going to close this issue as I don't think there's anything for me to change in the package, but let me know if you disagree!
