### ISSUE TITLE
[Question] Batch endpoint

### ISSUE THREAD

**Issue by umbert-cobiro** [cloudcreativity/laravel-json-api#423]
So, I've been trying to read on the JsonApi standard about it or around the internet but I cannot find any information about it. Is there any way to implement batch endpoints? I will have a few endpoint that might receive thousands of requests and the elements will always be related is there any way to follow the standar for this, or we shall just implement a custom endpoint, etc?

Thanks.

**Comment by rekrios** [comment]
Hi.
Are you referring about this ? https://github.com/json-api/json-api/issues/795
If yes, there are no bulk operations in the v1.0 specification

**Comment by lindyhopchris** [comment]
Yes that's correct, there's no support for bulk operations currently in the spec. You'd need to implement something yourself for the time being. When it gets added to the spec, I'll get it added to this package.
