### ISSUE TITLE
doSearch should assert that values of queryParams are strings

### ISSUE THREAD

**Issue by jelhan** [cloudcreativity/laravel-json-api#427]
Assuming one has a filter that is validated to be a `boolean` using `true` or `false` is not supported.

Assuming we have the filter defined like this in our adapter for a `post` resource:

```php
    protected $allowedFilteringParameters = [
        'archived',
    ];

    protected function queryRules(): array
    {
        return [
            'filter.archived' => 'boolean',
        ];
    }
```

`GET /posts?filter[archived]=true` rejects with `The filter.archived field must be true or false.`. Please note that `GET /posts?filter[archived]=1` works. It's the same for `false` and `0`. This seems to be an issue with casting query params.

This is especially tricky cause `doSearch()` test helper does not take casting issues into account. Therefore `this->doSearch([ 'filter' => [ 'archived' => true ] ])` works which cause false-positive tests. One may argue that developer should be aware to only use strings as arguments for query params but even these library doesn't follow such a rule in it's own test suite: https://github.com/cloudcreativity/laravel-json-api/blob/91dcd5fbd0bb36f66448c6568894bcc247a603bc/tests/lib/Integration/FilterTest.php#L121

**Comment by lindyhopchris** [comment]
This isn't a problem with this package, this is to do with Laravel's validation rules combined with the fact that query parameters are always strings via HTTP.

E.g. using `true` and `false` in Javascript for query params, these will get sent as strings over HTTP and then when PHP deserializes them, `'false'` is a string which equates to `true` in PHP.

Laravel's boolean validator looks for values that equate to true/false in PHP... i.e. does not support sending the words `false` and `true` as strings.

If you want to use `true/false` as HTTP query params that are sent as strings, you'd have to write your own rule object:
https://laravel.com/docs/6.x/validation#using-rule-objects

**Comment by jelhan** [comment]
Thanks for your quick response. Make sense. Got confused by the implicit conversion done here: https://github.com/cloudcreativity/laravel-json-api/blob/91dcd5fbd0bb36f66448c6568894bcc247a603bc/src/Testing/MakesJsonApiRequests.php#L100

May I suggest that we add an assertion that values of query params used in testings are strings?

**Comment by lindyhopchris** [comment]
I've got an idea of how to improve the test helpers for 2.0. Can look at checking they are all strings at that point (or at least convert them to strings... might be a bit inefficient but can definitely look at it).

**Comment by jelhan** [comment]
Updated the title accordingly.

**Comment by lindyhopchris** [comment]
This is now on the 2.0 branch.
