### ISSUE TITLE
Question:  getFillable() -- Creating vs updating

### ISSUE THREAD

**Issue by cunhar** [cloudcreativity/laravel-json-api#428]
I'm looking to allow a user to create a resource (pants) and set the attribute (number of legs) but then now allowing that user to use patch to change the number of legs attribute.

Is overriding the getFillable() method the right approach?  Im having trouble determining what type of request it is in that scope.

Thanks again for your help.

**Comment by lindyhopchris** [comment]
Yes we use overloading of `getFillable()` with a check on `$model->exists` to work out whether altering certain attributes is allowed.

**Comment by cunhar** [comment]
ok thanks!
