### ISSUE TITLE
Why do only some API resource routes receive names?

### ISSUE THREAD

**Issue by SirLamer** [cloudcreativity/laravel-json-api#43]
Referencing the wiki here...
https://github.com/cloudcreativity/laravel-json-api/wiki/Routing#route-names

Is there a reason why the other created resource routes don't receive a name? It seems to me that they might as well.

**Comment by lindyhopchris** [comment]
Do you mean add names for the different methods? At the moment the list of names matches the list or URLs that are registered.

**Comment by SirLamer** [comment]
Yes but there are all of the other method types on those URLs which don't receive names.

https://github.com/cloudcreativity/laravel-json-api/wiki/Routing#urls-and-controller-methods

**Comment by lindyhopchris** [comment]
I suppose I just added the ones that are needed to generate the JSON API `LinkInterface` classes. But you are right, there should probably be names for all of the different options.

**Comment by SirLamer** [comment]
For what it's worth, here is a package which would be a compliment to this package for client-side management of named routes if all API routes had proper names. Right now it cannot be used properly with this package if named routes is intended.
https://github.com/aaronlord/laroute

**Comment by lindyhopchris** [comment]
Yep, I've added the route names for all the routes to the registrar refactor that I've done on the `feature/issue53` branch. It's not ready to use yet though as it's linked to some other refactoring that needs to be done.

**Comment by lindyhopchris** [comment]
The new routing now has names for all routes. This has been merged into `develop` and will be released in v0.8.
