### ISSUE TITLE
Resource id validation

### ISSUE THREAD

**Issue by deividaspetraitis** [cloudcreativity/laravel-json-api#436]
Hello, 

Consider following url: `/authors/1-abcd`

Is there any way to validate resource id ( `1-abcd` ) by adding validation rules in `Validation` classes?
I was looking at source code and possible options how to achieve it however with no luck.

Thank you

**Comment by lindyhopchris** [comment]
Yes, just add a rule for the `id` to the array of rules that are returned from your `Validators` class.

**Comment by lindyhopchris** [comment]
Or if you mean validating the id in the URL, then use id constraints: https://laravel-json-api.readthedocs.io/en/latest/basics/routing/#id-constraints

**Comment by deividaspetraitis** [comment]
Thank you @lindyhopchris for help, somehow I missed that in documentation.
