### ISSUE TITLE
Url pattern findMany()

### ISSUE THREAD

**Issue by probststefan** [cloudcreativity/laravel-json-api#448]
How an url must be structured to access multiple resources simultaneously (findMany).

I'm trying something like this (/api/v1/articles/552,43,12) on an non-eloquent adapter and expecting the findMany method to be called.

**Comment by lindyhopchris** [comment]
on an Eloquent adapter you can do use: `/api/v1/articles?filter[id]=552,43,12`

On a non-Eloquent adapter you would need to implement the filter yourself.

The `findMany()` method on the adapter interface is called when looking up multiple resources to modify a has-many relationship... i.e. it's not a method that's used for a URL.
