### ISSUE TITLE
No JSON response when throwing JsonApiException

### ISSUE THREAD

**Issue by bitfactory-sander-lissenburg** [cloudcreativity/laravel-json-api#451]
Hi,

First of all, great library, great documentation. But I'm experiencing a problem when throwing a JsonApiException.

To simplify the problem I've managed to produce the problem with following code (I've removed the constructor and other default functions/properties from this example).

```php
class Adapter extends AbstractAdapter
{
    .... removed code

    protected function filter($query, Collection $filters)
    {
         throw new JsonApiException(
                [],
                422
         );
    }
}
```

I still get an 500 error with a html response and the following error.

```
Neomerx\JsonApi\Exceptions\JsonApiException: JSON API error in file /home/vagrant/projects/foobar/app/JsonApi/Foobar/Adapter.php on line 64
...... etc.
```

Is there something I'm missing?

**Comment by lindyhopchris** [comment]
Hi and thanks!

Have you followed the installation instructions on how to modify your exception handler?
https://laravel-json-api.readthedocs.io/en/latest/installation/#exception-handling

**Comment by bitfactory-sander-lissenburg** [comment]
Yep, that was it! Thank you very much!
