### ISSUE TITLE
Bug/Question: Content negotiator doesn't work with namespace.

### ISSUE THREAD

**Issue by myfbone** [cloudcreativity/laravel-json-api#455]
Hello!
I currently have such structure of my project:
```
app/Http/Controllers/JsonApi/
  - MyCustomController
app/JsonApi/
  - ModelName/
      - Validator
      - Schema
      - ContentNegotiator
```
If my controller is in controllers namespace (basically without namespace) it's working great. But if I follow documentation, change it's namespace to JsonApi (as you can see above) and add withNamespace('JsonApi') to my api, ContentNegotiator stops working somehow. And either I don't clearly understand how it works or it's a bug. Can you help me out here?

**Comment by myfbone** [comment]
Oopps. My bad. Problem was is that I set wrong namespace in json-api config file.
The right way to do:
```
'namespace' => 'App\JsonApi',
```
Wrong way to do:
```
'namespace' => 'JsonApi',
```

**Comment by lindyhopchris** [comment]
No problem, glad you managed to get it working!
