### ISSUE TITLE
Creating a new resource from a relationship

### ISSUE THREAD

**Issue by crabmusket** [cloudcreativity/laravel-json-api#456]
I've been trying to do the same thing as [this user](https://discuss.jsonapi.org/t/how-should-i-create-a-resource-as-a-relationship/299) allowing an entire new resource to be created by POSTing to a relationship link. E.g. if `posts` has a to-many relationship `comments`, then creating a new comment on a post could be done by:

```
POST /posts/1234/comments

{
  "data": {
    "type": "comments",
    "attributes": {
        "content": "hello world"
    }
}
```

This will create a new comment which is associated with post `1234` according to the usual relationship. The OP in the linked thread believes this is valid because, per the spec,

> A resource can be created by sending a POST request to a URL that represents a collection of resources.

This is similar to #302, but note that in that case, they were attempting the equivalent of `POST /posts/1234/relationships/comments`. Indeed, the JSON:API spec wouldn't allow posting a new resource to a relationship that way, but seems ambiguous on whether `POST /posts/1234/comments` should be allowed.

See more discussion on the issue here: https://github.com/json-api/json-api/issues/1158

I've tried to implement this using this library by adding a custom route, like so:

```php
    $api->resource('posts')
        ->routes(function($api) {
            $api->post('{record}/comments', 'createComment');
        })
```

In the controller, my method looks like this:

```php
    public function createComment(CreateResource $request, $record)
    {
        dd($request);
    }
```

But when I actually make a request to the endpoint, I get this error:

```json
{
  "errors": [{
    "status": "409",
    "title": "Not Supported",
    "detail": "Resource type comments is not supported by this endpoint.",
    "source": {
      "pointer": "/data/type"
    }
  }]
}
```

Is there a way for me to achieve this? Some way to allow the appropriate resource type past the validator?

If this isn't easily possible, I'll fall back to using `POST /comments` with a relationship to the post. I just prefer this way of designing the API; it's more HATEOAS-like. I'm also dealing with a polymorphic type (e.g., comments can be attached to `posts` or to `videos`), so this seemed like a better idea.

EDIT: by the way, thanks for all the hard work on this package! I'm really loving it so far - it's made creating fleshed-out APIs super fast.

**Comment by crabmusket** [comment]
I have managed to work around this in a pretty gnarly way using the following controller method:

```php
    public function createComment(StoreInterface $store, CreateCommentRequest $request, $opportunity)
    {
        $record = $this->transaction(function() use($store, $request, $article) {
            $comment = $this->doCreate($store, $request);
            $date = now();
            $article->comments()->attach($comment); // not sure about this
            return $comment;
        });

        if ($this->isResponse($record)) {
            return $record;
        }

        return $this->reply()->created($record);
    }
```

And the following request class:

```php
use CloudCreativity\LaravelJsonApi\Http\Requests\CreateResource;

class CreateCommentRequest extends CreateResource
{
    // had to override this to avoid 409
    public function getResourceType()
    {
        return 'comments';
    }
}
```

The direct use of `attach` in the controller I'm not sure about yet... I wonder if I should be using `StoreInterface::addToRelationship`, but I couldn't work out the right parameters to provide it.

**Comment by lindyhopchris** [comment]
@crabmusket sorry for taking so long to reply.

yes, you'd need to wire this yourself as it is not officially in the spec. I'd add it to this package if it got added to the spec, but don't want to deviate from the spec.

Yeah, don't use the store interface to do it because the store is there only to do official spec things, so wouldn't be appropriate in this case!

I'm going to close this issue as there's nothing for me to do at this stage. As I say, if this did get added to the spec I'd get it added to this package.
