### ISSUE TITLE
Method for pagination on related resource?

### ISSUE THREAD

**Issue by SirLamer** [cloudcreativity/laravel-json-api#46]
Per the subject, I can't figure how to do this. I would like to force pagination, however even user-requested pagination is not respected. Am I mistaken?

For example, given this resource...
```http://demo.dev/api/v1/countries```

... and this relationship URL...
```http://demo.dev/api/v1/countries/CA/cities?page%5Bnumber%5D=1&page%5Bsize%5D=15```

...pagination is not performed. I additionally wish to force pagination but see no method.

Might I suggest that pagination be determined on the Schema instead of the Search class? Then the pagination rules for the given asset are applied on relationships, including when the top-level ID data is included within 'relationships'.

Similarly, a global setting for pagination rules would be swell.

**Comment by lindyhopchris** [comment]
Pagination of related resources is not currently supported but is something we're planning on supporting in a future version. It requires some refactoring of how `Search` classes work. There's a detailed list of things that need to be supported here:

https://github.com/cloudcreativity/laravel-json-api/issues/35

**Comment by SirLamer** [comment]
Okay, thanks.
