### ISSUE TITLE
Use JOIN instead of multiple SELECTs to include resources

### ISSUE THREAD

**Issue by half2me** [cloudcreativity/laravel-json-api#466]
I hit my endpoint requesting some resources to be included. I would expect to have SQL JOINs to include those resources, but instead I'm getting a lot of queries, which doesn't scale very well, and also makes it impossible for me to filter based on a related resource.
Here is a screenshot of an example request I send, and the queries it ends up generating.
![image](https://user-images.githubusercontent.com/6759894/71668234-fe4fb100-2d5f-11ea-8815-09dda7cb13f1.png)

Details of my adapters and validators are in [this issue](https://github.com/cloudcreativity/laravel-json-api/issues/461)

In the documentation I read that it uses eager loading by default, so I don't understand why its doing it like this. Am I missing something?

**Comment by half2me** [comment]
@lindyhopchris could this be anything similar to the previous issue I had? (Linked above)

**Comment by lindyhopchris** [comment]
We're using Laravel Eloquent eager loading to include related resources, so not actually writing the SQL statements ourselves.

**Comment by half2me** [comment]
So I'm right in assuming these should be JOINs by default?

**Comment by lindyhopchris** [comment]
I'm not sure off the top of my head how they do it... you'll need to dig into the Laravel code to find out.

**Comment by half2me** [comment]
@lindyhopchris I realized after searching awhile that this is the way Laravel pulls in included relations. I'm coming from a cakePHP background, where JOINs where the default, hence my confusion.

**Comment by lindyhopchris** [comment]
No problem! Glad you found the answers you were looking for.
