### ISSUE TITLE
How to get headers and/or bearer token in controller?

### ISSUE THREAD

**Issue by ap1969** [cloudcreativity/laravel-json-api#467]
Hi all,
I'm really struggling with this one. I'm looking to extract the bearer token in my controller, but I can't find a way to get to the headers from the index function in the controller, defined as :

public function index(StoreInterface $store, FetchResources $request)

Can anyone point me in the right direction, please?

Regards,
Andy

**Comment by ap1969** [comment]
Ah, typical. Five minutes after posting this I find the answer. Including here for future reference:

In the controller: 
```
public function __construct()
    {
        $this->middleware(function ($request, $next) {
          $this->token = $request->bearerToken();
          return $next($request);
        });
    }
```

**Comment by lindyhopchris** [comment]
Glad you got it sorted! A simpler way is just to use the `request()` helper:
https://laravel.com/docs/6.x/helpers#method-request
