### ISSUE TITLE
The Model path in the adapter is not filled correctly.

### ISSUE THREAD

**Issue by Mina-R-Meshriky** [cloudcreativity/laravel-json-api#469]
When creating a resource using `php artisan make:json-api:resource posts`, and my posts Model is in `App\Models\Post`.

the generated adapter will contain the following in the constructor:
```php
public function __construct(StandardStrategy $paging)
    {
        parent::__construct(new \App\Post(), $paging);
    }
```
I think that the path of the models should be configurable from the `json-api-default.php` config file

**Comment by lindyhopchris** [comment]
Good suggestion! Have added to the to-do list. If you or anyone else wants this quicker, I'd take a PR adding this.

**Comment by Mina-R-Meshriky** [comment]
well it is going to be my first PR ever! but I am excited to give it a shot.

**Comment by lindyhopchris** [comment]
PR is #479
