### ISSUE TITLE
Resource generation doesn't map model correctly

### ISSUE THREAD

**Issue by dingo-d** [cloudcreativity/laravel-json-api#478]
I'm using spatie laravel permissions package, which creates 2 models I wanted to expose in my API.
I added those in my config (`json-api-v1.php`)

```php
use Spatie\Permission\Models\Permission;
use Spatie\Permission\Models\Role;

return [
    'resources' => [
        'users' => User::class,
        'roles' => Role::class,
        'permissions' => Permission::class,
    ],
];
```

I'm using eloquent models so I expected that when I do a 

```bash
php artisan make:json-api:resource Permissions
```

that the adapter constructor will have

```php
    /**
     * Adapter constructor.
     *
     * @param StandardStrategy $paging
     */
    public function __construct(StandardStrategy $paging)
    {
        parent::__construct(new Spatie\Permission\Models\Permission(), $paging);
    }
```

Instead, I have

```php
    /**
     * Adapter constructor.
     *
     * @param StandardStrategy $paging
     */
    public function __construct(StandardStrategy $paging)
    {
        parent::__construct(new \App\Permission(), $paging);
    }
```

Is this a bug or am I missing something?

Also, it looks like it didn't pick up on those models when I generated the resource. Should I create separate models for Roles and Permissions which extend the spatie ones in my app?

**Comment by lindyhopchris** [comment]
It's not a bug - the generators can't work out whether the model is in a different namespace to your application, so they default to assuming that the model is in your application.

The developer just needs to amend the class names once the file is generated. There's no need to extend the Spatie ones into your own app - just type-hint them correctly in the generated file.

**Comment by dingo-d** [comment]
Makes sense. Kinda thought that it's magically done, as most of the things that just seem to work 😄 

Awesome library btw!
