### ISSUE TITLE
Question: How to 'react' to an action when API call is made?

### ISSUE THREAD

**Issue by dingo-d** [cloudcreativity/laravel-json-api#480]
I'm trying to notify both the user being created and users with certain roles (roles are created using spatie/laravel-permissions package), when new user is created.

I have created a route and the 'registration' works (basically creating a user - POST call to `api/v1/users`). 

How do I react to this action? I saw the `created` method in your post controller in the demo, but when I tried to add this to my user controller, nothing happened.

**Comment by lindyhopchris** [comment]
Yes the `created` method on the controller is the way to do that.

Once you had made the controller, did you update the routing to tell it to use the controller rather than the package's generic one?
https://laravel-json-api.readthedocs.io/en/latest/basics/controllers/#extended-controller

**Comment by dingo-d** [comment]
Oh, so it has to be explicitly mentioned. I'll add that and test it out 🙂 Thanks

**Comment by dingo-d** [comment]
Seems to do the trick! Thanks!
