### ISSUE TITLE
Testing custom routes fails

### ISSUE THREAD

**Issue by dingo-d** [cloudcreativity/laravel-json-api#481]
I have a custom login route for token (Passport) generation purposes

```php
JsonApi::register('v1')->routes(static function (Api $api) {
    /**
     * Custom route that uses SessionController
     *
     * Used for 'log in' purposes (bearer token generation), and
     * 'log out' purposes (revoking bearer token).
     */
    $api->post('login', [SessionController::class, 'login'])->name('login')->middleware('content-type');
    // ...
```

The middleware just ensures that proper content-type header is added to the request

```php
<?php

namespace App\Http\Middleware;

use Closure;

class ApiContentType
{
    private const CONTENT_TYPE = 'application/vnd.api+json';

    /**
     * Handle an incoming request.
     *
     * Modify API request to include correct response content type header.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \Closure  $next
     * @return mixed
     */
    public function handle($request, Closure $next)
    {
        $response = $next($request);

        return $response->header('Content-Type', self::CONTENT_TYPE);
    }
}
```

When I test this route in the Postman, everything is ok.

```
POST /api/v1/login
Content-Type: application/vnd.api+json
Accept: application/vnd.api+json
{
    "email": "user@email.com",
    "password": "randomstring",
    "remember_me": "true"
}
```

I get 

```
{
    "type": "session",
    "attributes": {
        "access_token": "longrandomsring",
        "token_type": "Bearer",
        "expires_at": "2020-02-10 11:56:27"
    }
}
```

Which is great.

Now I created a test

```php
<?php

namespace Tests\Feature\Api;

use Carbon\Carbon;
use Laravel\Passport\Passport;
use Tests\UsersTestCase;
use App\User;

class LoginTest extends UsersTestCase
{
    /**
     * @var string
     */
    protected $loginRoute = '/api/v1/login';

    /**
     * @return void
     */
    public function setUp(): void
    {
        parent::setUp();

        $this->artisan('passport:install');
    }

    public function testApprovedUserCanLogIn()
    {
        // Set up user.
        $password = 'superSecre4PW0.!';

        $user = factory(User::class)->create([
            'approved_at' => Carbon::now()->format('Y-m-d H:i:s'),
            'password' => bcrypt($password),
        ]);

        $user->assignRole('admin');

        $data = [
            'email' => $user->email,
            'password' => $password,
            'remember_me' => true,
        ];

        Passport::actingAs($user);

        $response = $this->withHeaders([
            'Accept' => 'application/vnd.api+json',
            'Content-Type' => 'application/vnd.api+json',
        ])->json('POST', $this->loginRoute, $data);

        $response
            ->assertStatus(200)
            ->assertJsonStructure([
                "type",
                "attributes" => [
                    "access_token",
                    "token_type",
                    "expires_at",
                ]
            ]);
    }
}
```

and my `UsersTestCase` looks like

```php
<?php

namespace Tests;

use Spatie\Permission\Models\Role;
use Spatie\Permission\PermissionRegistrar;
use Spatie\Permission\Models\Permission;

abstract class UsersTestCase extends TestCase
{
    public function setUp(): void
    {
        // Include all the normal setUp operations.
        parent::setUp();

        // Re-register all the roles and permissions
        $this->app->make(PermissionRegistrar::class)->registerPermissions();

        // Create permissions.
        Permission::create(['name' => 'list users']);
        Permission::create(['name' => 'create users']);
        Permission::create(['name' => 'edit users']);
        Permission::create(['name' => 'delete users']);
        Permission::create(['name' => 'list roles']);
        Permission::create(['name' => 'create roles']);
        Permission::create(['name' => 'edit roles']);
        Permission::create(['name' => 'delete roles']);
        Permission::create(['name' => 'view dashboard']);

        // Create roles.
        Role::create(['name' => 'admin']);
        Role::create(['name' => 'management']);
        Role::create(['name' => 'staff']);
        Role::create(['name' => 'support']);
        Role::create(['name' => 'guest']);
    }
}
```

Just so that everything is ok with Passport.

The test fails, and when I dump the `$response` I get

<details><summary>Click to expand</summary>
<code><pre>
{#2537
  +"message": "The requested resource is capable of generating only content not acceptable according to the Accept headers sent in the request."
  +"exception": "Symfony\Component\HttpKernel\Exception\HttpException"
  +"file": "/Users/infinum-denis/my-test-api/vendor/cloudcreativity/laravel-json-api/src/Http/ContentNegotiator.php"
  +"line": 213
  +"trace": array:45 [
    0 => {#2409
      +"file": "/Users/infinum-denis/my-test-api/vendor/cloudcreativity/laravel-json-api/src/Http/ContentNegotiator.php"
      +"line": 183
      +"function": "notAcceptable"
      +"class": "CloudCreativity\LaravelJsonApi\Http\ContentNegotiator"
      +"type": "->"
    }
    1 => {#2260
      +"file": "/Users/infinum-denis/my-test-api/vendor/cloudcreativity/laravel-json-api/src/Http/ContentNegotiator.php"
      +"line": 118
      +"function": "checkAcceptTypes"
      +"class": "CloudCreativity\LaravelJsonApi\Http\ContentNegotiator"
      +"type": "->"
    }
    2 => {#2685
      +"file": "/Users/infinum-denis/my-test-api/vendor/cloudcreativity/laravel-json-api/src/Http/Middleware/NegotiateContent.php"
      +"line": 128
      +"function": "encoding"
      +"class": "CloudCreativity\LaravelJsonApi\Http\ContentNegotiator"
      +"type": "->"
    }
    3 => {#2538
      +"file": "/Users/infinum-denis/my-test-api/vendor/cloudcreativity/laravel-json-api/src/Http/Middleware/NegotiateContent.php"
      +"line": 92
      +"function": "matchEncoding"
      +"class": "CloudCreativity\LaravelJsonApi\Http\Middleware\NegotiateContent"
      +"type": "->"
    }
    4 => {#1697
      +"file": "/Users/infinum-denis/my-test-api/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php"
      +"line": 171
      +"function": "handle"
      +"class": "CloudCreativity\LaravelJsonApi\Http\Middleware\NegotiateContent"
      +"type": "->"
    }
    5 => {#2259
      +"file": "/Users/infinum-denis/my-test-api/vendor/cloudcreativity/laravel-json-api/src/Http/Middleware/BootJsonApi.php"
      +"line": 78
      +"function": "Illuminate\Pipeline\{closure}"
      +"class": "Illuminate\Pipeline\Pipeline"
      +"type": "->"
    }
    6 => {#2684
      +"file": "/Users/infinum-denis/my-test-api/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php"
      +"line": 171
      +"function": "handle"
      +"class": "CloudCreativity\LaravelJsonApi\Http\Middleware\BootJsonApi"
      +"type": "->"
    }
    7 => {#2418
      +"file": "/Users/infinum-denis/my-test-api/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php"
      +"line": 41
      +"function": "Illuminate\Pipeline\{closure}"
      +"class": "Illuminate\Pipeline\Pipeline"
      +"type": "->"
    }
    8 => {#2540
      +"file": "/Users/infinum-denis/my-test-api/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php"
      +"line": 171
      +"function": "handle"
      +"class": "Illuminate\Routing\Middleware\SubstituteBindings"
      +"type": "->"
    }
    9 => {#2410
      +"file": "/Users/infinum-denis/my-test-api/vendor/laravel/framework/src/Illuminate/Routing/Middleware/ThrottleRequests.php"
      +"line": 59
      +"function": "Illuminate\Pipeline\{closure}"
      +"class": "Illuminate\Pipeline\Pipeline"
      +"type": "->"
    }
    10 => {#2263
      +"file": "/Users/infinum-denis/my-test-api/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php"
      +"line": 171
      +"function": "handle"
      +"class": "Illuminate\Routing\Middleware\ThrottleRequests"
      +"type": "->"
    }
    11 => {#2411
      +"file": "/Users/infinum-denis/my-test-api/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php"
      +"line": 105
      +"function": "Illuminate\Pipeline\{closure}"
      +"class": "Illuminate\Pipeline\Pipeline"
      +"type": "->"
    }
    12 => {#2687
      +"file": "/Users/infinum-denis/my-test-api/vendor/laravel/framework/src/Illuminate/Routing/Router.php"
      +"line": 683
      +"function": "then"
      +"class": "Illuminate\Pipeline\Pipeline"
      +"type": "->"
    }
    13 => {#2273
      +"file": "/Users/infinum-denis/my-test-api/vendor/laravel/framework/src/Illuminate/Routing/Router.php"
      +"line": 658
      +"function": "runRouteWithinStack"
      +"class": "Illuminate\Routing\Router"
      +"type": "->"
    }
    14 => {#2696
      +"file": "/Users/infinum-denis/my-test-api/vendor/laravel/framework/src/Illuminate/Routing/Router.php"
      +"line": 624
      +"function": "runRoute"
      +"class": "Illuminate\Routing\Router"
      +"type": "->"
    }
    15 => {#2419
      +"file": "/Users/infinum-denis/my-test-api/vendor/laravel/framework/src/Illuminate/Routing/Router.php"
      +"line": 613
      +"function": "dispatchToRoute"
      +"class": "Illuminate\Routing\Router"
      +"type": "->"
    }
    16 => {#2701
      +"file": "/Users/infinum-denis/my-test-api/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php"
      +"line": 170
      +"function": "dispatch"
      +"class": "Illuminate\Routing\Router"
      +"type": "->"
    }
    17 => {#2279
      +"file": "/Users/infinum-denis/my-test-api/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php"
      +"line": 130
      +"function": "Illuminate\Foundation\Http\{closure}"
      +"class": "Illuminate\Foundation\Http\Kernel"
      +"type": "->"
    }
    18 => {#2426
      +"file": "/Users/infinum-denis/my-test-api/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php"
      +"line": 21
      +"function": "Illuminate\Pipeline\{closure}"
      +"class": "Illuminate\Pipeline\Pipeline"
      +"type": "->"
    }
    19 => {#2703
      +"file": "/Users/infinum-denis/my-test-api/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php"
      +"line": 171
      +"function": "handle"
      +"class": "Illuminate\Foundation\Http\Middleware\TransformsRequest"
      +"type": "->"
    }
    20 => {#2557
      +"file": "/Users/infinum-denis/my-test-api/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php"
      +"line": 21
      +"function": "Illuminate\Pipeline\{closure}"
      +"class": "Illuminate\Pipeline\Pipeline"
      +"type": "->"
    }
    21 => {#2427
      +"file": "/Users/infinum-denis/my-test-api/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php"
      +"line": 171
      +"function": "handle"
      +"class": "Illuminate\Foundation\Http\Middleware\TransformsRequest"
      +"type": "->"
    }
    22 => {#2281
      +"file": "/Users/infinum-denis/my-test-api/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php"
      +"line": 27
      +"function": "Illuminate\Pipeline\{closure}"
      +"class": "Illuminate\Pipeline\Pipeline"
      +"type": "->"
    }
    23 => {#2704
      +"file": "/Users/infinum-denis/my-test-api/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php"
      +"line": 171
      +"function": "handle"
      +"class": "Illuminate\Foundation\Http\Middleware\ValidatePostSize"
      +"type": "->"
    }
    24 => {#2558
      +"file": "/Users/infinum-denis/my-test-api/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php"
      +"line": 63
      +"function": "Illuminate\Pipeline\{closure}"
      +"class": "Illuminate\Pipeline\Pipeline"
      +"type": "->"
    }
    25 => {#2428
      +"file": "/Users/infinum-denis/my-test-api/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php"
      +"line": 171
      +"function": "handle"
      +"class": "Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode"
      +"type": "->"
    }
    26 => {#2282
      +"file": "/Users/infinum-denis/my-test-api/vendor/fideloper/proxy/src/TrustProxies.php"
      +"line": 57
      +"function": "Illuminate\Pipeline\{closure}"
      +"class": "Illuminate\Pipeline\Pipeline"
      +"type": "->"
    }
    27 => {#2705
      +"file": "/Users/infinum-denis/my-test-api/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php"
      +"line": 171
      +"function": "handle"
      +"class": "Fideloper\Proxy\TrustProxies"
      +"type": "->"
    }
    28 => {#2559
      +"file": "/Users/infinum-denis/my-test-api/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php"
      +"line": 105
      +"function": "Illuminate\Pipeline\{closure}"
      +"class": "Illuminate\Pipeline\Pipeline"
      +"type": "->"
    }
    29 => {#2429
      +"file": "/Users/infinum-denis/my-test-api/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php"
      +"line": 145
      +"function": "then"
      +"class": "Illuminate\Pipeline\Pipeline"
      +"type": "->"
    }
    30 => {#2283
      +"file": "/Users/infinum-denis/my-test-api/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php"
      +"line": 110
      +"function": "sendRequestThroughRouter"
      +"class": "Illuminate\Foundation\Http\Kernel"
      +"type": "->"
    }
    31 => {#2706
      +"file": "/Users/infinum-denis/my-test-api/vendor/laravel/framework/src/Illuminate/Foundation/Testing/Concerns/MakesHttpRequests.php"
      +"line": 434
      +"function": "handle"
      +"class": "Illuminate\Foundation\Http\Kernel"
      +"type": "->"
    }
    32 => {#2560
      +"file": "/Users/infinum-denis/my-test-api/vendor/laravel/framework/src/Illuminate/Foundation/Testing/Concerns/MakesHttpRequests.php"
      +"line": 406
      +"function": "call"
      +"class": "Illuminate\Foundation\Testing\TestCase"
      +"type": "->"
    }
    33 => {#2430
      +"file": "/Users/infinum-denis/my-test-api/tests/Feature/Api/LoginTest.php"
      +"line": 50
      +"function": "json"
      +"class": "Illuminate\Foundation\Testing\TestCase"
      +"type": "->"
    }
    34 => {#2284
      +"file": "/Users/infinum-denis/my-test-api/vendor/phpunit/phpunit/src/Framework/TestCase.php"
      +"line": 1408
      +"function": "testApprovedUserCanLogIn"
      +"class": "Tests\Feature\Api\LoginTest"
      +"type": "->"
    }
    35 => {#2707
      +"file": "/Users/infinum-denis/my-test-api/vendor/phpunit/phpunit/src/Framework/TestCase.php"
      +"line": 1028
      +"function": "runTest"
      +"class": "PHPUnit\Framework\TestCase"
      +"type": "->"
    }
    36 => {#2561
      +"file": "/Users/infinum-denis/my-test-api/vendor/phpunit/phpunit/src/Framework/TestResult.php"
      +"line": 691
      +"function": "runBare"
      +"class": "PHPUnit\Framework\TestCase"
      +"type": "->"
    }
    37 => {#2431
      +"file": "/Users/infinum-denis/my-test-api/vendor/phpunit/phpunit/src/Framework/TestCase.php"
      +"line": 756
      +"function": "run"
      +"class": "PHPUnit\Framework\TestResult"
      +"type": "->"
    }
    38 => {#2285
      +"file": "/Users/infinum-denis/my-test-api/vendor/phpunit/phpunit/src/Framework/TestSuite.php"
      +"line": 597
      +"function": "run"
      +"class": "PHPUnit\Framework\TestCase"
      +"type": "->"
    }
    39 => {#2708
      +"file": "/Users/infinum-denis/my-test-api/vendor/phpunit/phpunit/src/Framework/TestSuite.php"
      +"line": 597
      +"function": "run"
      +"class": "PHPUnit\Framework\TestSuite"
      +"type": "->"
    }
    40 => {#2562
      +"file": "/Users/infinum-denis/my-test-api/vendor/phpunit/phpunit/src/Framework/TestSuite.php"
      +"line": 597
      +"function": "run"
      +"class": "PHPUnit\Framework\TestSuite"
      +"type": "->"
    }
    41 => {#2432
      +"file": "/Users/infinum-denis/my-test-api/vendor/phpunit/phpunit/src/TextUI/TestRunner.php"
      +"line": 621
      +"function": "run"
      +"class": "PHPUnit\Framework\TestSuite"
      +"type": "->"
    }
    42 => {#2286
      +"file": "/Users/infinum-denis/my-test-api/vendor/phpunit/phpunit/src/TextUI/Command.php"
      +"line": 200
      +"function": "doRun"
      +"class": "PHPUnit\TextUI\TestRunner"
      +"type": "->"
    }
    43 => {#2709
      +"file": "/Users/infinum-denis/my-test-api/vendor/phpunit/phpunit/src/TextUI/Command.php"
      +"line": 159
      +"function": "run"
      +"class": "PHPUnit\TextUI\Command"
      +"type": "->"
    }
    44 => {#2563
      +"file": "/Users/infinum-denis/my-test-api/vendor/phpunit/phpunit/phpunit"
      +"line": 61
      +"function": "main"
      +"class": "PHPUnit\TextUI\Command"
      +"type": "::"
    }
  ]
}
</pre></code>
</details>

I looked at the tests in the demo, but those are all related to models in the DB, and I'm testing a custom endpoint created in the `SessionController`.

I've added necessary headers, as described in the docs, not sure why this fails.

**Comment by dingo-d** [comment]
Ok, could be something odd with headers. I dumped the headers and got

```bash
array:5 [
  "cache-control" => array:1 [
    0 => "no-cache, private"
  ]
  "date" => array:1 [
    0 => "Mon, 03 Feb 2020 14:50:36 GMT"
  ]
  "content-type" => array:1 [
    0 => "application/json"
  ]
  "x-ratelimit-limit" => array:1 [
    0 => 60
  ]
  "x-ratelimit-remaining" => array:1 [
    0 => 58
  ]
]
```

Seems like the content-type and accept headers weren't passed in the test.

**Comment by lindyhopchris** [comment]
So I haven't looked through this in detail, because I don't really have the time right now to look through this! It's pretty difficult debugging someone else's application when you don't have the application code to hand!

My main thought though was I'm not sure why you need that `Content-Type` middleware - this package already deals with the Content-Type during the content negotiation. Typically for the standard JSON API media type you don't need to set up anything, but if you want a detailed explanation see this chapter of the docs: https://laravel-json-api.readthedocs.io/en/latest/features/media-types/

The first exception you said you got saying:

> The requested resource is capable of generating only content not acceptable according to the Accept headers sent in the request.

Is from this package's content negotiation. Same with the one that said:

> The request entity has a media type which the server or resource does not support.

So I'd check firstly that the **request** has the correct headers on it, and that you haven't changed anything in the content negotiation settings for your API. The fact that you've decided to add that middleware makes me think that maybe there's something off with your setup?

**Comment by dingo-d** [comment]
Thanks for pointing me in the right direction, I appreciate it 🙂 

I added this middleware because I wanted to enforce the proper header, but looking at it now, I'm not sure this was the right direction.

I have a SPA attached to this project, and when I do `axios.post` I get the same issue as when I test it, so not really sure why it works with Postman.

But this means that I must have defined the custom route in the wrong way somehow (even though I did follow the docs).

I really appreciate you helping me out.

**Comment by dingo-d** [comment]
I'm not 100% sure, but it seems like `json()` method in tests forces `application/json` content type - which is why I'm getting unsupported media type error :S

**Comment by lindyhopchris** [comment]
Yeah that might be the case. The JSON API trait does add some helper methods e.g. `postJsonApi` that you might want to use instead?

**Comment by dingo-d** [comment]
This seems to do the trick.
The validation is triggered and I can see the test entering in the test method, but it failed on `if(!Auth::attempt(['email' => request('email'), 'password' => request('password')])){` part of my code with

> [2020-02-08 15:23:14] testing.ERROR: Method Illuminate\Auth\RequestGuard::attempt does not exist. {"userId":1,"exception":"[object] (BadMethodCallException(code: 0): Method Illuminate\\Auth\\RequestGuard::attempt does not exist. at /Users/infinum-denis/my-test-api/vendor/laravel/framework/src/Illuminate/Support/Traits/Macroable.php:103)
[stacktrace]

From [googling this error](https://github.com/tymondesigns/jwt-auth/issues/1498#issuecomment-521829241) it seems to be because the `Auth::attempt()` is only available to routes using `web` guard, and I'm using it when accessing the `api` guard. So the solution is to add

```php
Auth::guard('web')->attempt([...])
```

which makes the test pass successfully.

Thank you so much for helping out, and thanks for the useful helper for testing routes!
