### ISSUE TITLE
Inserting Polymorphic Data

### ISSUE THREAD

**Issue by seankndy** [cloudcreativity/laravel-json-api#483]
What is the proper route and payload to insert polymorphic data?  For example, if I have a Note model called 'notes' in laravel-json-api and that can be linked to a number of other models (using Eloquent's morphs), then would I have to POST to /api/v1/notes to create the note and for attributes would the client have to pass in the "notable_id" (id of related model) and "notable_type" (class name of related model) as attributes in order to create the note record?  Or is it possible to configure laravel-json-api to be able to POST to say /api/v1/accounts/12345/relationships/notes and have it automatically fill notable_id and notable_type so that client doesn't have to know that implementation detail?

For example posting this to /api/v1/notes:

{
  "data": {
    "type": "notes",
    "attributes": {
      "note": "Testing note."
    },
    "relationships": {
      "accounts": {
        "data": { "type": "accounts", "id": "102202b0-4d20-4bd0-969d-98044a91bfed" }
      }
    }
  }
}

Results in an exception due to the insert attempt didn't have notable_type field/column filled.  I'm assuming I either have a relationship misconfigured or this type of morph relationship isn't supported and the client must pass the notable_type?

Thanks.

**Comment by seankndy** [comment]
Disregard.  For anyone else that had this question, you need a belongsTo() relationship in your Adapter that reflects your actual model's morphTo().  You then use that method name as your relationship name in the API request.

**Comment by lindyhopchris** [comment]
Glad you got this sorted, sorry for not replying earlier!
