### ISSUE TITLE
Many to Many Polymorphic

### ISSUE THREAD

**Issue by seankndy** [cloudcreativity/laravel-json-api#484]
How do you insert many-to-many polymorphic data such as with 'tags' as mentioned in the documentation?  It states to create a taggables() method within the Adapter and define the hasmany relationships there, but POSTing this to /api/v1/tags:

{
	"data": {
		"type": "tags",
		"attributes": {
			"tag": "test",
			"description": "Denotes this is for testing."
		},
		"relationships": {
			"taggables": {
				"data": { "type": "users", "id": "102202b0-4d20-4bd0-969d-98044a91bfed" }
			}
		}
	}
}

...results in CloudCreativity\LaravelJsonApi\Object\ResourceIdentifier::fromArray() must be of the type array, string given, called in vendor/cloudcreativity/laravel-json-api/src/Object/ResourceIdentifierCollection.php

I also tried taggables.users which actually 'succeeds' and adds a row to the 'tags' table, but not the association to the User object within the 'taggables' table.

**Comment by seankndy** [comment]
Must I first create the tag without relationships, then add the relationship to the users model afterward?

**Comment by lindyhopchris** [comment]
Hi Sean - sorry for taking a while to reply, was a very hectic work week so didn't get a chance to look at open source stuff.

For this kind of scenario via JSON API you'd want to create the tag first (i.e. have a tags resource). Then if say both a `posts` and `videos` resource could be tagged, you'd have a `tags` relationship on both - and add the created tag resource to that relationship.

Hope I've explained that ok, let me know if not!

**Comment by lindyhopchris** [comment]
Closing as the question was answered and no further activity.
