### ISSUE TITLE
Return resource with trashed relationships

### ISSUE THREAD

**Issue by SEUH** [cloudcreativity/laravel-json-api#487]
Hello,

ich would like to return all of the relationships of a resource (with trashed ones). I can't figure out if it is possible out of the box.

For example:
There is a BookShelf and there are Books. Now, if you request (read) a BookShelf then it should return all of its Books (with trashed ones).
But if you list all Books (index) the trashed ones should be hidden like it normally is.

At the moment if i request a BookShelf, only the non trashed Books are returned in its relationship.

Can somone give me a hint or has done this himself?

**Comment by lindyhopchris** [comment]
Hi! I'd normally deal with this on the model:

```php
class BookShelf extends Model
{
  public function books()
  {
    return $this->hasMany(Book::class)->withTrashed();
  }
}
```

That will then mean they do appear in the API via the books relationship.

That's always fitted our use-cases - does it also work for you?

**Comment by lindyhopchris** [comment]
If it doesn't work in your use-case, I'd be happy to add a `withTrashed()` method to the JSON API relationship classes.

**Comment by SEUH** [comment]
After a long time i reread your answer and i was just simply stupid. It totally worked for me. Sorry for me being braindead.

Thank you!

**Comment by lindyhopchris** [comment]
Great, glad it worked!
