### ISSUE TITLE
AbstractAdapter::newQuery() not used for included relations

### ISSUE THREAD

**Issue by seankndy** [cloudcreativity/laravel-json-api#490]
I've overrode AbstractAdapter::newQuery() in one of my model adapters so that I can add a withCount() to the Builder.

This particular model has children relation which are of the same type as itself.  When I "include" the children via include paths:  /foo/<id>?include=children the children are included fine, however the children do not have the withCount() applied that I am doing in newQuery().  Any input on how to properly get this done?

**Comment by lindyhopchris** [comment]
Yeah that's only used for when querying the resource directly, not via relationships.

The two key lines that would need changing are these ones:
https://github.com/cloudcreativity/laravel-json-api/blob/67330ebf62add241b71d1119f604cf9dbca32a6d/src/Eloquent/AbstractAdapter.php#L142
https://github.com/cloudcreativity/laravel-json-api/blob/67330ebf62add241b71d1119f604cf9dbca32a6d/src/Eloquent/AbstractAdapter.php#L164

If we added a `newRelationQuery` method that receives the relation, that would give you a method to overload.

It's easy for a PR - any chance you'd be interested in doing one? If not I might be able to add it in the next few days as it's not a huge amount of work.

**Comment by seankndy** [comment]
queryToMany() is never called when executing the 'included' request.

**Comment by lindyhopchris** [comment]
Adapters only do the querying of the database... they don't do the encoding. The value that is included is the value you return in your schema for the `data` member of the relationship. So you'd need to add the count to the value you're returning in the schema.

**Comment by lindyhopchris** [comment]
FYI if you're trying to alter *every* query for a model, your best bet is to use a global scope, that's applied to the model class in middleware (so that it only applies for the API routes you want to use it on).
