### ISSUE TITLE
Mix record types in query result

### ISSUE THREAD

**Issue by jose-zapata** [cloudcreativity/laravel-json-api#492]
Hello!

In my DB I have a table (Entries) that hosts both news and articles. I'd like to have an endpoint that, when queried, gives me something like this:

```
HTTP/1.1 200 OK
Content-Type: application/vnd.api+json

{
  "links": {
    "self": "http://example.com/entries"
  },
  "data": [{
    "type": "news",
    "id": "1",
    "attributes": {
      "title": "New Story"
    }
  }, {
    "type": "articles",
    "id": "2",
    "attributes": {
      "title": "New Article"
    }
  }]
}
```
...and so on.

Articles and News would have their own endpoints as well. Is such a thing possible?

**Comment by lindyhopchris** [comment]
Yes, you'd probably want to write your own controller that uses the reply helpers from the package to convert the response to the JSON API format.

Add this trait to your controller, then you can chain off `$this->reply()`:
https://github.com/cloudcreativity/laravel-json-api/blob/develop/src/Http/Controllers/CreatesResponses.php

**Comment by jose-zapata** [comment]
I've been trying but so far I haven't gotten anywhere close to solving the problem, and the documentation doesn't help much, unfortunately. Could you please give me an example, or point me in the right direction?

Thanks.

**Comment by lindyhopchris** [comment]
Ok, happy to help.

First question - if they are in the same table, why do you need to have them as different named resources?

A super simple implementation would be to have an `entries` resource, with a `category` attribute that can either be `news` or `articles`. If you then had a `category` filter, you could get all the news articles using:

`GET /api/entries?filter[category]=news`

Does this not work for your use case? If you definitely do need them as separately resource types, then the simplest implementation would to have an `Entry` Eloquent model, then in your `news` and `articles` adapters, use scopes to ensure only the correct models are returned. [Scopes are fully documented](https://laravel-json-api.readthedocs.io/en/latest/basics/adapters/#scopes)

If neither of these solutions work for you, then you'll need to provide a lot more information about your implementation for me to work out a solution!

**Comment by jose-zapata** [comment]
Thanks for your reply, Christopher! I need them as separate resources (`articles` and `news`) because conceptually, they are. However, they're similar enough that I need only one table for the database structure for both of them.

The category filter does indeed work, and it was my first approach, but after seeing some examples in https://jsonapi.org/, on how an `author` and a `user` can be both of the `people` type, it occurred to me that a more elegant approach would be to do the same for both articles and stories. Now, I could have them as completely separated resources as well, but they share tags (a specific tag can be used in both `news` and `articles`), so I thought it could be useful to have a "supertype" of sorts called `entries` that could list both the `articles` and `news`, each with their type.

I've implemented the `articles` and `news` resources as you suggested, using scopes, and it works just fine. The problem I have is implementing the `entries` "supertype", so it won't return a list of `entries` type resources, but a mixture of `articles` and `news` resources, each with their respective types.

Thanks again!

**Comment by lindyhopchris** [comment]
Ah right that makes sense. Good the separate ones work.

For a combined endpoint I need to think about that. What URLs are you planning to implement that returns this super-resource? How do you plan to paginate over them, or do you not need pagination?

**Comment by jose-zapata** [comment]
For the super-resource, I'm planning to implement the `index` and maybe the `read` routes, although this last one isn't really needed. The rest of the routes (creation, update and deletion) would be "delegated" to the respective resources, either articles or news.

Thanks!

**Comment by lindyhopchris** [comment]
Ok for the super-resource, you'll need to implement a custom adapter. See here:
https://laravel-json-api.readthedocs.io/en/latest/basics/adapters/#custom-adapters

This is going to be a lot easier in the refactored version I'm working on, but for the moment the custom adapter is the way to go.

**Comment by lindyhopchris** [comment]
@jose-zapata I'm going to close this issue due to lack of activity. If you need anything else, just ask!
