### ISSUE TITLE
Many to Many relationship with attribute

### ISSUE THREAD

**Issue by hnc01** [cloudcreativity/laravel-json-api#500]
We have a Restaurant resource that can belongs to many countries (i.e. a branch in every country) and a country can have many branches. So, the tables are built as follows:

```
restaurants:
id
name
```

```
countries:
id
name
```

```
restaurant_country:
id
country_id
restaurant_id
branch_name
```

In the Restaurants resource we mention that Restaurants has Many Countries through the pivot table restaurant_country, and in the Countries resource we mention that Countries has Many Restaurants through the pivot table restaurant_country:

In Countries Adapter:
```
protected function restaurants() {
     return $this->hasMany();
}
```

In Restaurants Adapter:
```
protected function countries() {
     return $this->hasMany();
}
```
In all the documentations, it only shows the below example of how to update a Relationship:
```
{
  "data": [
    {
      "type": "tags",
      "id": "1"
    },
    {
      "type": "tags",
      "id": "6"
    }
  ]
}
```

However, with each relationship object, we need to send the `branch_name`. How do we include that in the post request to `/api/v1/restaurants/{restaurant_id}/relationships/countries` ?

**Comment by lindyhopchris** [comment]
Hi!

According to the spec, relationships only contain *resource identifiers* - these do not therefore have attributes.

For this scenario, you will need to create an intermediary resource e.g. `restaurant-countries`, i.e. each resource representing the pivot model. Then you'll be able to create a new one, e.g.:

```json
{
  "data": {
    "type": "restaurant-countries",
    "attributes": {
      "branch-name": "My Branch",
    },
    "relationships": {
      "restaurant": {
        "data": {
          "type": "restaurant",
          "id": "123",
        },
      },
      "country": {
        "data": {
          "type": "country",
          "id": "456",
        },
      },
    },
  },
}
```

**Comment by hnc01** [comment]
Hello @lindyhopchris 

Thank you so much! It's clear now.
