### ISSUE TITLE
Package zendframework/zend-diactoros is abandoned, you should avoid using it.

### ISSUE THREAD

**Issue by nelson6e65** [cloudcreativity/laravel-json-api#501]
Package **zendframework/zend-diactoros** is abandoned, you should avoid using it. Use **laminas/laminas-diactoros** instead.

> Laminas and its subprojects are an open source continuation of Zend Framework and its subprojects, and are the official fork of the project now that it has been archived and abandoned. 
> https://docs.laminas.dev/migration/

**Comment by lindyhopchris** [comment]
Hi! This was fixed on the `2.0.0-beta.1` release. 

I'll fix it for `1.x` versions too, I'm also planning on doing a `2.0.0-rc.1` relatively soon. I've got big changes in the pipeline but I'll save those for `3.0`.

**Comment by nelson6e65** [comment]
Thanks.

**Comment by lindyhopchris** [comment]
This isn't fixable for `1.x` versions, so I'm closing the issue. The solution is to upgrade to `2.x` versions of this package. I've released `2.0.0-beta.2` today.
