### ISSUE TITLE
morphMany Relationships Eloquent to JSON API

### ISSUE THREAD

**Issue by linckosz** [cloudcreativity/laravel-json-api#505]
In the documentation ( https://laravel-json-api.readthedocs.io/en/latest/basics/adapters/ ), in the chapter "Relationships", the mapping from Eloquent to JSON API seems wrong.
Current:
morphMany => hasMany
Proposal:
morphMany => morphMany

Also, the chapter "Morph-Many" says "morphMany => morphMany".
But the chapter "Has-Many" is saying "morphMany => hasMany".

In my project, I am using the mapping "morphMany => morphMany" (in getRelated method)  and it works fine this way.

Regards,

Bruno

**Comment by lindyhopchris** [comment]
Thanks for reporting, I'll check this out.
