### ISSUE TITLE
Support for "sandbox" mode?

### ISSUE THREAD

**Issue by adamthehutt** [cloudcreativity/laravel-json-api#510]
Is there any existing or planned support for "sandbox" or "test" modes? This is something we need to provide, and while I imagine we could figure it out on our end, this library is so comprehensive it would be great to see it included as a core option. 

Presumably a sandbox mode would need to:

- Provide read access to real data but only simulate any writes or deletes 
- Change the drivers/configuration for the mailer, queue, cache, etc. to prevent pollution
- Swap out test keys for things like transaction processing engines or other 3rd-party resources
- Other things that I'm probably missing

It may be that the changes necessary to enter "sandbox" mode are too application-specific to support in a generic way, but I know our API isn't the only one that needs this.

**Comment by lindyhopchris** [comment]
Hi! Personally I feel this is far too application specific. An ideal implementation of this would be via middleware, that detects something in the request to know to switch to a sandbox mode. However this logic would need to be very application specific. For example, where in the middleware stack does the switch to sandbox mode need to be applied? What on the request will indicate sandbox mode - e.g. header, access token, etc? What drivers need to be swapped out for sandbox mode? What other configuration needs to be swapped out? Should database writes still occur e.g. if the sandbox mode involves a different database being used? What else about the application needs to be modified? How might runtime code detect sandbox mode is active in case there are code paths that need to change? Etc etc.

Ultimately I think this is just too application specific. The other thing to factor in is I'm ideally trying to stick to things that are defined in the `JSON:API` spec, and as there's no spec defined way of doing sandbox mode, I'd be reluctant to implement something.

Personally I think generic ways of handling sandbox mode would be really useful - but I actually think they'd be better supported by a seperate open source package that deals with the logic and configuration of sandbox mode.

So thanks for raising the question, but considering I'm extremely limited on time to work on the core JSON:API support, I don't think this is something that I can cater for in this package. Hope that makes sense!
