### ISSUE TITLE
Controller add action return error

### ISSUE THREAD

**Issue by invaders-xx** [cloudcreativity/laravel-json-api#513]
Dear,

First of all, many thanks for this great module!

I have added a function in my controller
public function move(FetchResource $request, $record)

I added a route to this action in api:
$api->resource('records')->controller('RecordsController')->routes(function ($records) {
     $records->post('{record}/move', 'move')->name('move');
});

When I try to post to this route I got the exception message:
Facade\Ignition\Exceptions\ViewException: Method Illuminate\Auth\RequestGuard::logout does not exist. 

It never goes to the action in the controller and I don't know what is this exception.
if you have any inputs, I would appreciate.

Many thanks in advance,

David
PS : I have many other api routes working fine

**Comment by lindyhopchris** [comment]
Hi! Unfortunately this will be something to do with your application set-up, so I can't help you debug it. If you track it down to a definite bug in this package, feel free to re-open the issue and provide more detail about the bug.
