### ISSUE TITLE
Documentation difference based on package version

### ISSUE THREAD

**Issue by rekrios** [cloudcreativity/laravel-json-api#514]
Hi.
Would there be different documentation for 1.* and 2.* versions? Coz now you can search only by 'build' age
P.S. great package ;)

**Comment by lindyhopchris** [comment]
There's almost no difference between 1.x and 2.x. For 2.x I just removed code that was marked as deprecated and made some minor changes to support Laravel 7. So the docs should be fine for both versions.

**Comment by rekrios** [comment]
oh, thanks

**Comment by zlodes** [comment]
@lindyhopchris
Hi, how about ^2.0 stability? When is 2.0.0?

Thanks for the work!
