### ISSUE TITLE
[Ask] `auth:api` middleware display render page not json error format

### ISSUE THREAD

**Issue by PanjiNamjaElf** [cloudcreativity/laravel-json-api#521]
I put `auth:api` middleware after `laravel-json-api` middleware but when i try using postman returned render page not in json error format. I have also put error exception handler and follow all documentation but still not work.

Here my route code:
```
JsonApi::register('v1')->middleware('auth:api')
    ->singularControllers()
    ->routes(function (Api $api) {
        $api->resource('users')->controller();
    });
```

Exception `Handler.php` code:
```
public function render($request, Throwable $e)
{
    if ($this->isJsonApi($request, $e)) {
        return $this->renderJsonApi($request, $e);
    }
}
```

**Comment by lindyhopchris** [comment]
Hi! You need to be sending an `Accept` header with the value `application/vnd.api+json`. Can you confirm that you are sending that in the request?

**Comment by PanjiNamjaElf** [comment]
Wohoo~~ Its work now... 

How if i send using different `Accept` header for example i want use `application/json`
I have add `application/json` on `encoding` and `decoding` config array

But when i try request just return with `Unauthenticated` laravel default response not on JsonApi Error Format

**Comment by lindyhopchris** [comment]
Yes the errors only get rendered to JSON API errors if the `Accept` header is the JSON API media type. Because Laravel already has an error format for `application/json`, Laravel will return that format when the `Accept` header is `application/json`.
