### ISSUE TITLE
[Ask] Request to method POST, PUT & PATCH with empty body document.

### ISSUE THREAD

**Issue by PanjiNamjaElf** [cloudcreativity/laravel-json-api#522]
I want to make request on `POST`, `PUT` and `PATCH` method with empty document but when i try using postman it returned with error message title `Document Required`.

I have create custom route for approve user and using laravel passport token scope so it no need any required document. When i try add json raw on body request i got the result. I want send request with empty body on `POST`, `PUT` or `PATCH` method how to do it?

Here my code:

Route:
```
JsonApi::register('v1')->middleware('auth:api')
    ->singularControllers()
    ->routes(function (Api $api, Route $router) {
        $api->resource('users')->controller()->routes(function ($routes) {
            /** @var Api $routes */
            $routes->patch('{record}/approve', 'approve')->name('approve');
        });
    });
```

Controller:
```
public function __construct()
{
    $this->middleware('scopes:approve-users')->only('approve');
}

public function approve(User $user)
{
    return $this->reply()->content($user);
}
```

Result:
```
{
    "errors": [
        {
            "status": "400",
            "title": "Document Required",
            "detail": "Expecting request to contain a JSON API document."
        }
    ]
}
```

**Comment by lindyhopchris** [comment]
Hi! If you're not following the JSON API specification for a route, you should register the route outside of the `JsonApi::register`. That's because any routes registered inside will expect the specification to be followed.

I.e. register your user approve route in the normal Laravel way.
