### ISSUE TITLE
Custom actions not authorized with resource-specific Authorizer

### ISSUE THREAD

**Issue by colq2** [cloudcreativity/laravel-json-api#524]
I recently noticed, that any custom action in the form of 
```
JsonApi::register('v1')
    ->defaultController('AbstractResourceController')
    ->routes(function (RouteRegistrar $api, $router) {
        $api->resource('orders')->only('read')->routes(function (RouteRegistrar $resource) {
            $resource->get('{record}/resend-mail', 'OrderController@resendMail');
        });
    });
```
is not authorized by the `Authorizer@read` hook which is expected to be invoked.
I am using a resource specific folder structure where my the authorizer is located at `Api\V1\Orders\Authorizer`.
The main read endpoint is authorized like expected.

Am I missing something or is this a security related bug?

**Comment by colq2** [comment]
Found the missing part!


For future references:
The problem was, that I used `Request` as first parameter in the controller method. As described in https://laravel-json-api.readthedocs.io/en/latest/basics/controllers/#custom-actions the type must be `CloudCreativity\LaravelJsonApi\Http\Requests\FetchResource`.

To resolve this I changed

```php
public function resendMail(Request $request, Order $order) {}
```

to 

```php
public function resendMail(FetchResource $request, Order $order) {}
```


**Feature Request:**
I think it would be more convenient if you didn't have to type hint the FetchResource and the first way would work also and call the authorizer methods.

**Comment by lindyhopchris** [comment]
I don't really support custom actions - in the sense that it's impossible for me to know what people are doing with them as they aren't defined in the spec. It's not really a security bug because you can use any of Laravel's normal authorization techniques on a custom action - it doesn't have to go via the authorizer.
