### ISSUE TITLE
Documentation for creating an error is incorrect.

### ISSUE THREAD

**Issue by zero-to-prod** [cloudcreativity/laravel-json-api#526]
The documentation for creating an error https://laravel-json-api.readthedocs.io/en/latest/features/errors/ is incorrect.

The class `CloudCreativity\LaravelJsonApi\Document\Error;` does not exist. It is a folder.

If there is a different way to create an error, please direct me to the right source.

**Comment by lindyhopchris** [comment]
Hi! Thanks for reporting, the FQN should be `CloudCreativity\LaravelJsonApi\Document\Error\Error` and the static method `fromArray` if creating from an array. I've updated the docs.
