### ISSUE TITLE
Customize including relations based on record data?

### ISSUE THREAD

**Issue by glaphire** [cloudcreativity/laravel-json-api#528]
Hi! I've read documentation but didn't understand how to implement my feature.
"Returning Related Resources" works for resources that are mentioned by "include" get parameter, but it's not this.
I have Category model (Category1 and Category2) and few Models (Model1, Model2). I want to show link and data in relation based on Category id, for example:

```
"data":[
{
      "type":"categories",
      "id":"1",
      "attributes":{
         "name":"cat1",
      },
      "relationships":{
         "models1":{
            "links":{
               "related":"http://localhost:8000/api/v1/categories/1/models1"
            }
         }
      },
   },
   {
      "type":"categories",
      "id":"2",
      "attributes":{
         "name":"cat2",
      },
      "relationships":{
         "models2":{
            "links":{
               "related":"http://localhost:8000/api/v1/categories/2/models2"
            }
         }
      },
   }
]
```

Where can I write this kind of filter for including relations?

**Comment by tsterker** [comment]
@glaphire Check out [Returning Related Resources](https://laravel-json-api.readthedocs.io/en/latest/fetching/inclusion/#returning-related-resources).

The `getRelationships` method gets passed the resource and returns an associated array with the keys being the relationship names. You can just use conditional logic and build the relationship array dynamically, e.g.

```php

    public function getRelationships($category, $isPrimary, array $includeRelationships)
    {
        if ($category->id == 1) {
            return [
                'models1' => [self::SHOW_RELATED => true]
            ];
        }
 
       // other logic

      return [];
    }
```

**Comment by lindyhopchris** [comment]
@glaphire yeah, it should be implemented in the `getRelationships` method in the schema. If you're still stuck, maybe sharing your category schema code would help?

**Comment by glaphire** [comment]
@tsterker @lindyhopchris Sorry for late response.
Yes, example from @tsterker works perfectly, thank you very much!
