### ISSUE TITLE
Custom adapter on api routes

### ISSUE THREAD

**Issue by PanjiNamjaElf** [cloudcreativity/laravel-json-api#532]
I have `Loan` and `LoanProduct` model and i want to make the route naming like this.

```
http://example.com/api/loans -> for Loan Model
http://example.com/api/loans/products -> for LoanProduct model
```

and on my `api.php` routes i do it like this

```
use CloudCreativity\LaravelJsonApi\Routing\RouteRegistrar as Api;
use Illuminate\Contracts\Routing\Registrar;

Route::middleware(['auth:api', 'cache.headers:public;max_age=2628000;etag'])->group(function () {
    JsonApi::register('v1')->singularControllers()->routes(function (Api $api, Registrar $router) {
        $api->resource('loans')->controller()->routes(function ($routes) {
            $routes->resource('products')->controller('LoanProductController');
        });
    });
});
```

But when i try to access it via postman on `api/loans/products` i got an error `No adapter for resource type: products`
i have created adapter and schema in `App\JsonApi\Loans` and `App\JsonApi\LoanProducts`

My question is how to custom adapter for resource `Products` to `LoanProducts` without change the route name to `loan-products`. I have read the documention many times about `Adapter` and `Routing` but didn't find the solution.

**Comment by lindyhopchris** [comment]
This kind of nesting of routing isn't supported. The package would expect the resource types to be `loans` and `loan-products`, with `loan-products` not nested under `loans` in the route hierarchy. So it would expect the routes to be:

- `api/loans`
- `api/loan-products`

If you want this supported, I'd accept a PR adding the functionality. Maybe changing the `resource('products')` method to take the resource name and the URL fragment, e.g. `$routes->resource('loan-products', 'products')`.

**Comment by lindyhopchris** [comment]
Closing as question was answered.
