### ISSUE TITLE
[Question] register and login via passport

### ISSUE THREAD

**Issue by cannycookie** [cloudcreativity/laravel-json-api#535]
Hi Guys,

Loving this module, great work.  Super excited to be building with it.

Have seen a few people asking about using passport and have checked the demo app, but you've left user creation and login to the default laravel frontend. 

I initially started this project without your module and have created separate API controllers to create and and login users with passport tokens but would be nice to incorporate these controllers into the JSON-API routes.    Do i just create a custom Auth controller and adapter? And what would go in the config.resources array as Auth does't have a model to reference.

any tips gratefully received.

**Comment by zlodes** [comment]
You can write custom adapter for `tokens` resource and implement `create` method with authentication service call.

**Comment by cannycookie** [comment]
> You can write custom adapter for `tokens` resource and implement `create` method with authentication service call.

So would I need to create a Tokens Model? or can that just be ignored in the config file?

**Comment by zlodes** [comment]
> So would I need to create a Tokens Model? 

You may use `Laravel\Passport\Token` model.

**Comment by lindyhopchris** [comment]
Closing this issue for the mo, as I think the question has been answered.
