### ISSUE TITLE
Add meta to resource collection

### ISSUE THREAD

**Issue by enmy** [cloudcreativity/laravel-json-api#537]
Hi! Great project!

I have quoestions about statistics.
I want to add some statistics to an `orders` collection. I found there is no standard way to do it in the json:api specification. So I thoght in adding it to meta.

- The only way to add meta to a collection is by overriding `CloudCreativity\LaravelJsonApi\Http\Controllers\JsonApiController::index`?

- How do I controll the sparse fieldsets if the request do not need the statistics?

- Should the statistics be added to the `/api/v1/orders` endpoint in the meta or other endpoint in the attributes?

The statistics are about sum total valid and undelivered orders, sum total valid and undelivered orders by delivery region... so they may relate with multiple resources that have no relations with each other, only with orders. Is like: `orders -> status`, `orders -> address`. So status and address are not related but are use for statistics

Thank you for your help

**Comment by lindyhopchris** [comment]
Hey. Yes, to follow the JSON API spec this kind of information would need to be added to the `meta` field.

You are right that you would probably need to overload the `index` method to do that. Unfortunately meta isn't easily supported in the current versions, so overloading is probably what you'll have to do in the meantime.

Sparse feildsets relate to resource fields, so probably aren't the best thing to use to control whether the client wants the statistics or not. You're best bet would be to use some sort of custom query parameter, which is allowed by the spec here (they refer to them as *implementation specific* query parameters):
https://jsonapi.org/format/#query-parameters

I'm going to close this issue as there are already issues open about improving how to add top-level meta.
