### ISSUE TITLE
Error::create 

### ISSUE THREAD

**Issue by geraldokandonga** [cloudcreativity/laravel-json-api#539]
I am facing an error on the following 

Returned Error => local.ERROR: Call to undefined method CloudCreativity\LaravelJsonApi\Document\Error\Error::create()

`return $this->reply()->errors(Error::create([
						'title' => 'Bad Request',
						'detail' => trans($response),
						'status' => '400',
						'meta' => [
							'key' => 'email',
							'pointer' => `'/data/attributes/email'`
						]
					]));`

**Comment by lindyhopchris** [comment]
You need to use `Error::fromArray()`.
