### ISSUE TITLE
[Question] How to create multiple routes via the JsonApi::register

### ISSUE THREAD

**Issue by geraldokandonga** [cloudcreativity/laravel-json-api#540]
Is there a way to create multiple routes like ?

`http://app.example.com/api/v1/admin/users`

I tried different method but i still get the below result

`http://app.example.com/api/v1/users`

**Comment by lindyhopchris** [comment]
Think you'd need to wrap it in a group to set URL prefix. Have you tried that?

**Comment by geraldokandonga** [comment]
Hi @lindyhopchris  Thank you for the response, i tried that the returned as http://app.example.com/api/v1/users/admin, which comes after, while what i wanted to achieve is this http://app.example.com/api/v1/admin/users

I am actually new this to laravel-json-api just started exploring it recently and i might say i am having with it so far but my challenge currently only this on how to have separate URLs for admin etc.

**Comment by geraldokandonga** [comment]
Finally after some trying i managed to get it right

Here is  how did it

`	JsonApi::register('v1', ['namespace' => 'Api\V1\Admin', 'middleware' => 'auth:api'], function (Api $api, $router) {

		Route::group(['prefix' => 'admin'],  function () use ($api) {

                        // URL GOES HERE

		});

	});`

Result:

http://app.example.com/api/v1/admin/users
