### ISSUE TITLE
How to validate post create object with multiple rows?

### ISSUE THREAD

**Issue by cannycookie** [cloudcreativity/laravel-json-api#541]
Hi there, we have a requirement to create multiple records in a single call.  I've created a custom controller but can't get past the object structure validation.  Have been trying various combinations of the data object with / without square brackets.. Has anyone done something like this yet?  Is it possible?

```javascript
{
  "data": {
    "type": "question_answers",
    "attributes":  [
                  {
                        "question_id": "1",
                        "submission_id": "1",
                        "response_text": "Some optional text",
                    },
                     {
                        "question_id": "2",
                        "submission_id": "1",
                        "response_text": "Some other reply",
                    }
          ]
    }
}
```

Thanks for any advice :-)

**Comment by lindyhopchris** [comment]
Hi! That resource isn't compliant with the JSON API spec. The `attributes` member of the resource needs to be an object, not an array.

if you want to do something like the above, nest the array of answers in an attribute called `answers`.
