### ISSUE TITLE
wrong id when primary key is uuid

### ISSUE THREAD

**Issue by anurat** [cloudcreativity/laravel-json-api#542]
I have a model with an id 023e8d62-7894-478f-94f8-f903050a1ed0  
but I got a json with  `id: "2300000000"` instead.  

When the primary key is integer it works fine.
What could go wrong here?

**Comment by lindyhopchris** [comment]
Have you set `keyType` on your model to `string`?

Otherwise you'll need to debug on the model... this is unlikely to be a problem with this package.

**Comment by anurat** [comment]
Thank you so much, I did not know about `keyType` before.
It works immediately!
