### ISSUE TITLE
Which is a case necessary for the relationship fields?

### ISSUE THREAD

**Issue by kaermorchen** [cloudcreativity/laravel-json-api#543]
Hello! First of all, thanks for the awesome package!

Which is a case necessary for the relationship fields? Camel case or snake case? 

I am not sure, but looks like it require a both. Otherwise user's update request don't save `basic_car_id` to database.

```
//App/User
class Car extends Model
{
    ...

    public function cars()
    {
        return $this->hasMany('App\Car');
    }

    public function basic_car()
    {
        return $this->belongsTo('App\Car');
    }

    public function basicCar()
    {
        return $this->belongsTo('App\Car');
    }
}

//User/Adapter
class Adapter extends AbstractAdapter
{
    ...

    protected function cars()
    {
        return $this->hasMany();
    }

    protected function basic_car()
    {
        return $this->belongsTo();
    }

    protected function basicCar()
    {
        return $this->belongsTo();
    }
}
```

**Comment by lindyhopchris** [comment]
Hi! The method name should be `basicCar()`. However, for the request to save it, you'll need to mark the `basic-car` or `basicCar` JSON API field as fillable on your adapter. The case of that will depend on what you're using in you JSON API payload - camel or dash case.

**Comment by lindyhopchris** [comment]
Closing as this question was answered.
