### ISSUE TITLE
Adding sorting by scope

### ISSUE THREAD

**Issue by jersonmr** [cloudcreativity/laravel-json-api#549]
Hi there! I'd like to know if there is a way to get resources sorted by a scope? I know the package allow realize sorting by columns of the model but if I need realize sort by a related resource? Or by countable related resource?

Something like this:
```
public function scopeSortByLikes($query)
    {
        return $query->withCount('likes')
                ->orderBy('likes_count', $direction);
        });
    }
```

Thanks!

**Comment by lindyhopchris** [comment]
Hi!

Good suggestion... I've added something to the adapter so you can implement the `sortByLikes` method on the adapter. An example is now in the sorting chapter of the docs - at the end of the chapter.

This will be in `2.2.0` and `3.0.0` - I'm just sorting out tagging versions at the moment.

**Comment by jersonmr** [comment]
Awesome man! Thanks for answer me and taking my suggestion on count
