### ISSUE TITLE
Question - How to sort by relationship attribute ?

### ISSUE THREAD

**Issue by lilouch** [cloudcreativity/laravel-json-api#554]
Hi,

I try to sort a table based on a specific attributes of its relationship.
Basically, I have a table records and another one called reference. Each reference is associated to a record.
A reference does not have any date_time attribute because it's belongs to a record that has the date_time.

I would like to fetch references and order in desc order by doing somethings like this 
`GET /references?page[number]=1&page[limit]=10&sort=-record.date_time`

However it does not work 
`
Column not found: 1054 Unknown column 'record.date_time' in 'order clause' (SQL: select * from `reference` order by `record`.`date_time` desc, `reference`.`id` asc limit 10 offset 0) `

So far, what I'm understand is the fact that we only search in the reference table.

So, is there a way to sort by the relationship attribute date_time ?

Thank in advance

**Comment by rekrios** [comment]
Can you make this via simple eloquent builder or raw SQL query? As I see this, you need to make join to your base 'reference' and then make sorting

**Comment by lilouch** [comment]
@rekrios yes I can do that but where exactly in the code ?
For example, for filtering, I was able to add query inside the `protected function filter($query, Collection $filters)` but for the sort, I don't know where.

Thank !

**Comment by lindyhopchris** [comment]
@lilouch you can now add `sortBy*` methods to your adapter, as described here:
https://laravel-json-api.readthedocs.io/en/latest/fetching/sorting/#implementing-sorting

Can you implement using this feature? You need to be on version `2.2.0` or `3.0.0` as the feature has recently been added.

**Comment by lilouch** [comment]
Thank a lot @lindyhopchris ! Works like a charm !
