### ISSUE TITLE
resource binding is not substituted when chaining API calls

### ISSUE THREAD

**Issue by robinstraub** [cloudcreativity/laravel-json-api#556]
I am trying to use a package generating api documentation ([scribe](https://github.com/knuckleswtf/scribe)).

I started getting the given runtime error : `Expecting resource binding to be substituted.`. This error is thrown by the `CloudCreativity\LaravelJsonApi\Http\Requests\Concerns\ResourceRequest`.

Basically it happens when API calls are chained. When I register a single route (i.e. `$api->resource('establishments')->controller()->only('read');`) everything works fine, but when I register multiple routes (i.e. `$api->resource('establishments')->controller()->only('index', 'read');`) I get this error.

It works fine when requesting the API from an external source as I only fetch one or the other endpoint, but as Scribe chains API calls to every available route the error occurs.

I tried to debug this on my own but I lack knowledge on both laravel-json-api internals and how Scribe performs requests to fully understand where does the issue come from. Do you have any idea what is happening ?

Here is an example stack trace:
```
{
    "message": "Expecting resource binding to be substituted.",
    "exception": "CloudCreativity\\LaravelJsonApi\\Exceptions\\RuntimeException",
    "file": "\/Users\/robinstraub\/Documents\/Binch\/chr\/api\/vendor\/cloudcreativity\/laravel-json-api\/src\/Http\/Requests\/Concerns\/ResourceRequest.php",
    "line": 49,
    "trace": [
        {
            "file": "\/Users\/robinstraub\/Documents\/Binch\/chr\/api\/vendor\/cloudcreativity\/laravel-json-api\/src\/Http\/Controllers\/JsonApiController.php",
            "line": 404,
            "function": "getRecord",
            "class": "CloudCreativity\\LaravelJsonApi\\Http\\Requests\\FetchResource",
            "type": "->"
        },
        {
            "file": "\/Users\/robinstraub\/Documents\/Binch\/chr\/api\/vendor\/cloudcreativity\/laravel-json-api\/src\/Http\/Controllers\/JsonApiController.php",
            "line": 111,
            "function": "doRead",
            "class": "CloudCreativity\\LaravelJsonApi\\Http\\Controllers\\JsonApiController",
            "type": "->"
        },
        {
            "file": "\/Users\/robinstraub\/Documents\/Binch\/chr\/api\/app\/Http\/Controllers\/Api\/V1\/EstablishmentsController.php",
            "line": 44,
            "function": "read",
            "class": "CloudCreativity\\LaravelJsonApi\\Http\\Controllers\\JsonApiController",
            "type": "->"
        },
       [...]
    ]
}
```

**Comment by lindyhopchris** [comment]
Apologies but I don't fully understand what is going on here. The routing you mention as the problem does work - we have that setup in multiple production applications.

When you do this:

```
$api->resource('establishments')->controller()->only('index', 'read');
```

Two routes should be registered. Do they appear as defined routes when you use the `route:list` Artisan command?

**Comment by robinstraub** [comment]
Hi, I experienced this issue again while writing tests. I setup a code sample to replicate the issue, hopefully it can help you understand what is going on. 

I created a new issue as I didn't realise the tests problems I was running into came from the same cause, here is a link : [https://github.com/cloudcreativity/laravel-json-api/issues/575](https://github.com/cloudcreativity/laravel-json-api/issues/575)

**Comment by lindyhopchris** [comment]
@robinstraub When you do this:

```php
$api->resource('establishments')->controller()->only('index', 'read');
```

The code is registering 2 routes. Do you see those two routes when you use the `route:list` Artisan command?

As for Scribe... if it is running multiple tests or whatever it does against a single Laravel application, then that is invalid. As explained on the other issue, in reality each HTTP request would receive a brand new instance of the Laravel application. If you or Scribe are chaining multiple requests against a single instance of a Laravel application, you will get false positives and other errors - because that does not reflect the reality of what happens in a HTTP request. The fix is for your code to use a new instance of the Laravel application per request and per test.

**Comment by lindyhopchris** [comment]
Having taken an exceptionally quick look at Scribe... I believe it uses your tests to generate the docs? In which case the route cause of the problem will be your tests not reseting the application when testing two (or more) HTTP requests in a single test. 

If that's the case, my strong advice would be to refactor your tests to only submit a single HTTP request per test. Generally this is the approach I'd recommend to any developer - use the *Arrange, Act, Assert* approach to tests https://github.com/testdouble/contributing-tests/wiki/Arrange-Act-Assert I.e. for Laravel tests, arrange sets up the application state (e.g. putting things into the database), act is the single HTTP request, assert tests the expected response and/or application state (e.g. changes in the database). I.e. there's only one HTTP request in that test.

If you really must keep multiple HTTP requests in a single test, then make sure the application is reset *between* requests using the `resetApplication` test.

**Comment by robinstraub** [comment]
ok thank you, Scribes calls internally the specified endpoints to generate the documentation and uses php comments/annotations. I'll look into how I can setup scribe to isolate the calls so that the application state isn't kept between calls.

I'll close the issue as it is something I have to deal with Scribe and this library works as intended, thanks a lot for your support !

**Comment by lindyhopchris** [comment]
No problem! If you get it working with Scribe it might be worth posting a comment on this issue just in case anyone else looks in the future.
