### ISSUE TITLE
Only allow return of the authenticated user.

### ISSUE THREAD

**Issue by tobenski** [cloudcreativity/laravel-json-api#559]
How would i go about only allowing a user do get his own user resource?
i believe it should be something like:

```
if ($request->user == $resource) { 
return resource;
} else {
return Notallowed/unautinticated Execption 
}

```
But i fail to see where i should put this code.

**Comment by tobenski** [comment]
I tried using scopes as suggested on https://github.com/cloudcreativity/laravel-json-api/issues/406#issuecomment-525285345
but i get a "ReflectionException: Class App\Scopes\AuthUserScope does not exist"

app\Scopes\AuthUserScope.php:

```
<?php

namespace App\Scopes;

use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Scope;
use Illuminate\Support\Facades\Auth;

class AuthUserScope implements Scope
{
    /**
     * Apply the scope to a given Eloquent query builder.
     *
     * @param  \Illuminate\Database\Eloquent\Builder  $builder
     * @param  \Illuminate\Database\Eloquent\Model  $model
     * @return void
     */
    public function apply(Builder $builder, Model $model)
    {
        $builder->where($model->is(Auth::user()));
    }
}
```

Adapter.php:
```
use App\Scopes\AuthUserScope as Scope;
....
    public function __construct(StandardStrategy $paging, Scope $scope)
    {
        parent::__construct(new \App\Models\User(), $paging);

        $this->addScopes($scope);
    }
......
```

i cant figure out what im doing wrong...

**Comment by lindyhopchris** [comment]
Yeah doing this as a scope is over kill. If you just want to return the current user for the `users` resource, overload the action method on the controller e.g. index, and return the current user directly:

```php
return $this->reply()->content(Auth::user());
```

**Comment by tobenski** [comment]
That was easy ... Ty
