### ISSUE TITLE
How to prevent the "included" from also outputting "relationships"?

### ISSUE THREAD

**Issue by zorenleolumosbog** [cloudcreativity/laravel-json-api#561]
How to prevent the "included" from also outputting "relationships"?

**Comment by lindyhopchris** [comment]
Hi! Sorry, I don't understand your question. The `include` path is about specifying which relationships to include in the JSON API document.

Could you provide more information as to what you are trying to do?

**Comment by zorenleolumosbog** [comment]
Please refer to the attach photo.

Imagine a scenario where profiles can pick a default profile photo. That means, a single media can be associated with many profiles. If the "included" outputs in its "relationships" all the profiles using a particular media, that list can get very long.

I'd like to minimize the payload of my output. In my example, how do I exclude the "relationships" of the "media" resource?

![image_2020_10_15T01_52_40_109Z](https://user-images.githubusercontent.com/22342082/96071005-e488f000-0ed3-11eb-8b70-b1a3b8c7af39.png)

**Comment by lindyhopchris** [comment]
Can you share the `getRelationships()` methd of your `media` schema?

**Comment by zorenleolumosbog** [comment]
Here please check. Thanks!

public function getRelationships($resource, $isPrimary, array $includeRelationships)
    {
        return [
            'media'            => [
                self::DATA         => function () use ($resource) {
                    return $resource->media;
                },
                self::SHOW_SELF    => true,
                self::SHOW_RELATED => true,
            ],
        ];
    }

**Comment by zorenleolumosbog** [comment]
Here please check. Thanks!
public function getRelationships($resource, $isPrimary, array $includeRelationships)
    {
        return [
            'profiles' => [
                self::DATA         => function () use ($resource) {
                    return $resource->profiles;
                },
                self::SHOW_SELF    => true,
                self::SHOW_RELATED => true,
            ],
        ];
    }

**Comment by zorenleolumosbog** [comment]
Here please check. Thanks!
```
public function getRelationships($resource, $isPrimary, array $includeRelationships)
    {
        return [
            'profiles' => [
                self::DATA         => function () use ($resource) {
                    return $resource->profiles;
                },
                self::SHOW_SELF    => true,
                self::SHOW_RELATED => true,
            ],
        ];
    }
```

**Comment by lindyhopchris** [comment]
Yeah so that's your problem... because you have used the `self::DATA` constant, but not the `self::SHOW_DATA`, showing the data is always `true`. Update it to the following:

```php
public function getRelationships($resource, $isPrimary, array $includeRelationships)
    {
        return [
            'profiles' => [
                self::SHOW_DATA => isset($includeRelationships['profiles']),
                self::DATA         => function () use ($resource) {
                    return $resource->profiles;
                },
                self::SHOW_SELF    => true,
                self::SHOW_RELATED => true,
            ],
        ];
    }
```

That will mean the data is only shown if the client has asked for it to be included via the `include` query parameter.

**Comment by zorenleolumosbog** [comment]
Oh yeah it is working. I think my mistake coz I already tried this before and maybe I just did not double check my output. Thank you for that!
