### ISSUE TITLE
Participating Hacktoberfest

### ISSUE THREAD

**Issue by ben221199** [cloudcreativity/laravel-json-api#564]
I would like to use this repository when participating @Hacktoberfest. However, at the moment the repository is a `Ineligible Repository`. By adding the topic "hacktoberfest" to the repository or the "hacktoberfest-accepted" label to #563, the pull request will be accepted.

> Your PR was submitted to a repository that is not participating in Hacktoberfest. Maintainers of the repository can add the "hacktoberfest" topic to their repository if they wish to participate. Alternatively, an individual PR can be opted-in with a maintainer adding the "hacktoberfest-accepted" label to the PR.

**Comment by lindyhopchris** [comment]
I'm not organised enough (due to time constraints) to mark the whole repository, so have added the label to your PR.
