### ISSUE TITLE
Update polymorphic relationships have no effect

### ISSUE THREAD

**Issue by pharmarin** [cloudcreativity/laravel-json-api#565]
Hello, and thank you for your awesome work. 
I tried to update a polymorphic (one to many or many to many with pivot table) relationship but the relationship do not update in the database. I cannot explain why. I had to add a `update` method to my Adapter which updates the relationship manually. 

Here is the data sent by the client : 
`data: {
  id: "1557", 
  type: "precaution",
  attributes: {
    ...attributes
  },
  relationships: {
    precaution_cible: {
      data: {
        type: "principe-actif", id: "163"
      }
    }
  }
}`

Thank you

**Comment by lindyhopchris** [comment]
Are you using the `$fillable` property on the adapter, and if so, is the relation listed in it?

**Comment by pharmarin** [comment]
My bad, I did not add the relation in my Adapter class. 
Sorry for the inconvenience.
