### ISSUE TITLE
[L8] Throwing an Error from Adapter hook renders as 500 http code

### ISSUE THREAD

**Issue by ProteanCode** [cloudcreativity/laravel-json-api#566]
Laravel Framework 8.11.2
PHP: 7.4 fpm + nginx on top of that
Library version (according to composer.lock): v3.0.1

```
// Created inside the adapter
protected function creating(User $user, ResourceObject $resource): void
{
    $error = Error::fromArray([
        'title'     => 'The language you want to use is not active',
        'status'    => Response::HTTP_UNPROCESSABLE_ENTITY,
    ]);

    throw new JsonApiException($error);
}
```

I have followed installation steps about the exception handler so that's not it

The log content:
```[2020-10-26 01:19:02] local.ERROR: JSON API error {"exception":"[object] (CloudCreativity\\LaravelJsonApi\\Exceptions\\JsonApiException(code: 0): JSON API error at /var/www/html/vendor/cloudcreativity/laravel-json-api/src/Exceptions/JsonApiException.php:51)```

The handler part:
```
public function render($request, Throwable $e)
{
    if ($this->isJsonApi($request, $e)) {
        // It goes there
        return $this->renderJsonApi($request, $e);
    }

    return parent::render($request, $e);
}
```

I expected to see a 422 response, but it became somehow overshadowed by a 500 one

**Comment by lindyhopchris** [comment]
What's your `Accept` header when you're doing the request that results in a `500` response?

**Comment by ProteanCode** [comment]
> What's your `Accept` header when you're doing the request that results in a `500` response?

Both Accent and Content-Type are application/vnd.api+json

**Comment by lindyhopchris** [comment]
I think you'll need to debug this as it's working in the test suite and in the production applications that I'm using this package in.

I'm slightly confused as to what's going on because your log is referring to line 51 of the exception class, but that's the static `make` method, which you're not using in the above code.

Throwing from within the adapter should hit the exception handler. Are you sure from the code that the exception you're throwing is definitely coming to the handler, or whether some other exception is caused somewhere? Can you confirm what's happening when it arrives here in your handler:

```php
    if ($this->isJsonApi($request, $e)) {
        // It goes there
        return $this->renderJsonApi($request, $e);
    }
```

Is `$e` the exception you're expecting? And are you sure no other exception is being thrown within the render?

Sorry, but this is almost impossible for me to debug without access to your application, so I'm reliant on you being able to chase it down!

**Comment by ProteanCode** [comment]
![500](https://user-images.githubusercontent.com/43477801/97244764-d43d1300-17f9-11eb-97d6-03941e7ec234.png)

The object is correct, there is no another exception thrown

**Comment by ProteanCode** [comment]
![500_2](https://user-images.githubusercontent.com/43477801/97245507-80cbc480-17fb-11eb-9bc0-8cb627052d87.png)

This is odd

**Comment by ProteanCode** [comment]
Okay I got this, but this is not what I would expect as the final result.

First, the 500 error is because the method `getErrors` of `vendor/cloudcreativity/laravel-json-api/src/Exceptions/ExceptionParser.php`
Look at its body

```
/**
 * @param \Throwable $e
 * @return ErrorInterface[]
 */
protected function getErrors(\Throwable $e): array
{
    if ($e instanceof IlluminateValidationException) {
        return $this->getValidationError($e);
    }

    if ($e instanceof AuthenticationException) {
        return [$this->translator->authentication()];
    }

    if ($e instanceof AuthorizationException) {
        return [$this->translator->authorization()];
    }

    if ($e instanceof TokenMismatchException) {
        return [$this->translator->tokenMismatch()];
    }

    if ($e instanceof HttpException) {
        return [$this->getHttpError($e)];
    }

    return [$this->getDefaultError()];
}
```

This method does not work with a `CloudCreativity\LaravelJsonApi\Document\Error\Error` object. It returns a default error which is described as

```
/**
 * @return ErrorInterface
 */
protected function getDefaultError(): ErrorInterface
{
    return new Error(
        null,
        null,
        $status = Response::HTTP_INTERNAL_SERVER_ERROR,
        null,
        $this->getDefaultTitle($status)
    );
}
```

Let's go back to how I thrown my exception:

```
$error = Error::fromArray([
    'title'     => 'The language you want to use is not active',
    'status'    => Response::HTTP_UNPROCESSABLE_ENTITY,
]);

throw new JsonApiException($error);
```

The status I requestes is Response::HTTP_UNPROCESSABLE_ENTITY (422), but since `getErrors` do not care about `CloudCreativity\LaravelJsonApi\Document\Error\Error` then it will return a 500 http response anyway.

So... bug or not? I probably can throw the `IlluminateValidationException` or `HttpException`, but this is a workaround

**Comment by ProteanCode** [comment]
I have folowed the https://laravel-json-api.readthedocs.io/en/latest/features/errors/ docs

**Comment by ProteanCode** [comment]
Confirmed that throwing a `Symfony\Component\HttpKernel\Exception\HttpException` works

```
throw new HttpException(Response::HTTP_UNPROCESSABLE_ENTITY, 'The language you want to use is not active');
```

returns in a 422 response:

```
{
  "errors": [
    {
      "status": "422",
      "title": "Unprocessable Entity",
      "detail": "The language you want to use is not active"
    }
  ]
}
```

**Comment by lindyhopchris** [comment]
Ok, right thanks for all that - it really helps. I'll have a dig into this later today.

**Comment by lindyhopchris** [comment]
Thanks for everything... I've been able to reproduce, so looking at a fix now.

**Comment by lindyhopchris** [comment]
@ProteanCode can you try the `develop` branch and confirm the issue is fixed?

```bash
$ composer require "cloudcreativity/laravel-json-api:dev-develop"
```

If it is, I'll do a release with the fix in it.

**Comment by ProteanCode** [comment]
> @ProteanCode can you try the `develop` branch and confirm the issue is fixed?
> 
> ```shell
> $ composer require "cloudcreativity/laravel-json-api:dev-develop"
> ```
> 
> If it is, I'll do a release with the fix in it.

It indeed does work.
Thanks

**Comment by lindyhopchris** [comment]
Release as `3.1.0`
