### ISSUE TITLE
Validating UUID without getting a 500 error code (the Spec validator isNotFound method is called before regex)

### ISSUE THREAD

**Issue by ProteanCode** [cloudcreativity/laravel-json-api#568]
This POST request to store an user gives me a 500 error code.

Notice the language id have invalid **x** as the first character.

UUIDs are generated **on database** level (postgres), not programatically

```
{
	"data": {
		"type": "users",
		"attributes": {
			"name": "Hello Wo2rld",
			"email": "om1qwqwqqw2dd1222e111ga@gmail.com",
			"password": "qwerty123"
		},
		"relationships": {
			"language": {
				"data": [
					{
						"type": "languages",
						"id": "x2e5086ef-55ba-452d-af87-5b47d261ca27"
					}
				]
			}
		}
	}
}
```

The problem is we have a spec validation running there, and it validates whenever a resource exists in database which is fine, but its bold to bet that end user entered the ID in correct format. 

The 500 error is too serious for that

**Comment by lindyhopchris** [comment]
The spec validator just calls the `exists()` method on the adapter. So you can fix this by overloading the `exists` method on the `languages` adapter, i.e. something like:

```php
public function exists(string $resourceId): bool
{
    if (1 === preg_match('/.../', $resourceId)) {
        return parent::exists($resourceId);
    }

    return false;
}
```

**Comment by ProteanCode** [comment]
> The spec validator just calls the `exists()` method on the adapter. So you can fix this by overloading the `exists` method on the `languages` adapter, i.e. something like:
> 
> ```
> public function exists(string $resourceId): bool
> {
>     if (1 === preg_match('/.../', $resourceId)) {
>         return parent::exists($resourceId);
>     }
> 
>     return false;
> }
> ```

Thanks. Working like a charm!
