### ISSUE TITLE
Invalid text representation error when trying give string to integer key

### ISSUE THREAD

**Issue by bbprojectnet** [cloudcreativity/laravel-json-api#574]
Hi,

I have primary key as a integer.

When i try this: `PATCH /api/quizzes/999999999` i get not found response - it's ok.

But, when i try this: `PATCH /api/quizzes/somestring` i get error 500 - "Invalid text representation".

It happend on PostgreSQL database which is very strict and throw error when we try `select * from "quizzes" where "quizzes"."id" = somestring`.

**Comment by lindyhopchris** [comment]
Yeah, you don't want the `somestring` to even hit your database, which is why you should use ID constraints:
https://laravel-json-api.readthedocs.io/en/latest/basics/routing/#id-constraints

**Comment by bbprojectnet** [comment]
Thanks a lot!
