### ISSUE TITLE
chaining requests server-side with a url containing a resource id throws an error

### ISSUE THREAD

**Issue by robinstraub** [cloudcreativity/laravel-json-api#575]
When performing requests in quick succession (for instance testing or performing API calls server-side),I regularly get HTTP 500 errors.

After some debugging, it occurs when I perform a first request on a json-api endpoint. After that, the enxt request calling an endpoint with a specified resource (read, patch, delete) will fail with the given error:
`TypeError : Return value of CloudCreativity\LaravelJsonApi\Http\Requests\UpdateResource::getResourceId() must be of the type string, null returned`

This error occured in tests as well as when using some server-side services , such as scribe, which builds a documentation by calling every endpoint of the API.

Any idea of what can cause this issue ? I made sure the resourceId is specified when calling the resource and the associated model exists in database.

**Comment by robinstraub** [comment]
I created a sample laravel project that demonstrates the issue. It can be found here : [https://github.com/robinstraub/laravel-json-api-issue-575](https://github.com/robinstraub/laravel-json-api-issue-575).

I didn't get exactly the same error as previously mentionned, when disabling error handling (`$this->withoutExceptionHandling()`) I get the following error `CloudCreativity\LaravelJsonApi\Exceptions\RuntimeException : Expecting resource binding to be substituted.`.

**Comment by robinstraub** [comment]
I searched a bit, the issue can be solved by binding the `CloudCreativity\LaravelJsonApi\Routing\Route` class in the `CloudCreativity\LaravelJsonApi\ServiceProvider` (line 234) rather than registering it as a singleton.

My guess is it works fine when calling the API externally (e.g. from a client) as the laravel application is booted for each call and terminated after the request has been processed.

When the API is called internally (such as in tests or when using api inspection third-party services) the Route service instance is kept between calls which leads to various errors.

I would propose a PR to change the singleton registration for a simple binding, however I am not well aware of this library internal behavior. A binding registration could lead to more computation if the service instantiation is a heavy process.

My use case was very specific when it was about integrating another package (Scribe) withe this library so I didn't put much time in finding a workaround, however this issue happening when conducting tests feels like a more common scenario.

**Comment by lindyhopchris** [comment]
The binding is meant to be a singleton - because each HTTP request will receive a new instance of the Laravel application, that's used for that single request then discarded. 

How in your set up is a Laravel application being retained between different HTTP requests? That shouldn't be happening. As can be seen in this file, the app is created, handles the request, then is effectively discarded when the script finishes:
https://github.com/laravel/laravel/blob/8.x/public/index.php

**Comment by lindyhopchris** [comment]
For info, this error should not be encountered during tests. A test should simulate the *real* situation - which means that testing two HTTP requests in a single test is bad practice. If you *must* test two HTTP requests in a single test, you need to reset the application *between* the two requests, to ensure that the second request receives a new instance of the Laravel application (just as it would in two separate HTTP requests). This can be done using the `refreshApplication` method on the test case:
https://github.com/laravel/framework/blob/8.x/src/Illuminate/Foundation/Testing/TestCase.php#L102

**Comment by robinstraub** [comment]
Ok, thank you for the info, it makes sense indeed. I'll update my tests to isolate the http requests.

**Comment by lindyhopchris** [comment]
Great! Glad the answer helped.
