### ISSUE TITLE
Change response depending if user is authenticated

### ISSUE THREAD

**Issue by lineinlinus** [cloudcreativity/laravel-json-api#577]
Is there a way to alter the reponse depending on if a user is authenticated (bearer) or not.

For example

**Company model:**

**No Auth or Auth failed** returns: 
Company:  name 
Relationships: User: name

**Auth success** returns:
Company:  name, uuid 
Relationships: User: name, email

**Comment by ben221199** [comment]
@lindyhopchris I think it also important to change the list based on if a user is authenticated. For example, on the endpoint `/resources/1` (show) I can easily block non-admins for seeing hidden resources (with authorizers), but on the endpoint `/resources` (index) a list with all the resources will be shown, also the hidden ones, for both admin and non-admin.

@lineinlinus What you could do to solve your problem, is the following:
```
	public function getAttributes($resource): array{
		$attributes = [];

		if(auth()->check()){ //Or: Auth::check()
			$attributes = array_merge($attributes,[
				'name'		=> $resource->name,
				'uuid'		=> $resource->uuid,
			]);
		}else{
			$attributes = array_merge($attributes,[
				'name'		=> $resource->name,
				'uuid'		=> $resource->uuid,
			]);
		}

		return $attributes;
	}
```

**Comment by ben221199** [comment]
- Index endpoint (list the resources):
	- Authenticate (only check if valid user): `auth` middleware
	- Authorize (check if user is permitted): authorizer
	- Show specific resources: **HOW???**
	- Show specific attributes/relationships: schema
- Show endpoint (show one resource):
	- Authenticate (only check if valid user): `auth` middleware
	- Authorize (check if user is permitted): authorizer
	- Show specific attributes/relationships: schema
- Create endpoint (create one resource):
	- Authenticate (only check if valid user): `auth` middleware
	- Authorize (check if user is permitted): authorizer
	- Create specific attributes/relationships: validator
- Delete endpoint (delete one resource):
	- Authenticate (only check if valid user): `auth` middleware
	- Authorize (check if user is permitted): authorizer

Maybe the whole authentication/authorization/permission thing should be redesigned.

**Comment by lindyhopchris** [comment]
@lineinlinus you should use `Auth::check()` in your Schema provider if you want to vary the resource attributes/relationships based on whether a user is authenticated or not.

@ben221199 I'd recommend that you use query scopes to scope a model's query based on whether a user is authenticated or not. this will mean that the user can only ever access models via the API based on their authentication status.
https://laravel-json-api.readthedocs.io/en/latest/basics/adapters/#scopes
