### ISSUE TITLE
Question about the \JsonApi::current() method :docs:

### ISSUE THREAD

**Issue by sbalouki** [cloudcreativity/laravel-json-api#578]
Hi,
In v1, the json_api_request() method is said to be soon replaced by a \JsonApi::current() method that I don't seem to find anywhere in the project.
Sadly, the same goes for the request() method, which leaves us with no branches to catch :
`  
        
         * Get the inbound JSON API request.
         *
         * @return JsonApiRequest
         * @deprecated 2.0.0 use `\JsonApi::current()`
         */
        function json_api_request() {
            return app('json-api')->request();
        }
`

Am I missing something here ?

**Comment by lindyhopchris** [comment]
Thanks for raising this. It looks like either the docblock is wrong, or I've forgotten to do something when releasing a new major version. I'll have to dig into this, but at the moment I'm on holiday for Christmas and New Year, so may not be able to look at it until I return to work.

**Comment by lindyhopchris** [comment]
Have checked, the method name on the facade is `JsonApi::currentRoute()`.

That returns an instance of `CloudCreativity\LaravelJsonApi\Routing\Route`:
https://github.com/cloudcreativity/laravel-json-api/blob/develop/src/Routing/Route.php
