### ISSUE TITLE
Problem with meta and sorting data

### ISSUE THREAD

**Issue by lilouch** [cloudcreativity/laravel-json-api#579]
Hi,

I have a method that return an array of specific data in descending order (by date_time). So far so good.
Let's call it "dataShocks". This data would allow me to draw some charts.

Now, I would like to return this array in a meta attribute using laravel json api. 

Basically, I'm doing this:

```
public function getPrimaryMeta($resource)
 {
     ...
  $dataShocks=  $data->getDataShocks();
    return [
            'dataShocks' => $dataShocks,
        ];
}
```

However, when I'm fetching the URL, I get well the dataShock in my meta attribute **but the order is not preserved at all**. I have double check by doing `dd($dataShocks)` just before returning it and it is working. But not when I'm using the URL.

Am I missing something ? What can I do ?

**Comment by lindyhopchris** [comment]
Hi! I'm afraid you'll need to debug this in your own application. We don't do anything that would change the order of the value you return from the `getPrimaryMeta` method, so I can't help explain what would be causing the order to change.
