### ISSUE TITLE
[Question] [Documentation? ] Authorizers for custom actions

### ISSUE THREAD

**Issue by DenisaHalmaghi** [cloudcreativity/laravel-json-api#583]
Hello there!

Is there any way in which I can include my custom  json-api controller actions in a json-api authorizer? We can currenly do this inside an authorizer:
```php
public function create($type, $request)
    {
        $this->authorize('create', $type);
    }
```
Can we also do something like this?

```php
public function myCustomAction($type, $request)
    {
        $this->authorize('something', $type);
    }
```

I don't really like doing controller authrorization, would really like it to have the authorization in one class, such as an Authorizer.

Thank you for your time!

**Comment by osteel** [comment]
If someone ends up on this issue like I just did, it looks like it's been answered [here](https://github.com/cloudcreativity/laravel-json-api/issues/299) already.
