### ISSUE TITLE
How to upload an avatar?

### ISSUE THREAD

**Issue by paolooo** [cloudcreativity/laravel-json-api#584]
My `User` model has avatar column. I want it to update when form has been submitted together with other attributes.

Payload

```
{
    "data": {
        "type": "users",
        "attributes": {
            "name": "sample",
            "email": "other@sample.com",
            "avatar":  _file-data-here_
        }
}
```

Is this possible? 

Thanks

**Comment by ben221199** [comment]
If your `_file-data-here_` is some `data:image/png;base64,<base64data>` string and you also save it like that in the DB, yes, why not?

**Comment by lindyhopchris** [comment]
Yeah, if the `avatar` attribute is something that is valid in JSON, then there's no reason why you couldn't get this working. You can use a *Mutator* on the `users` adapter to decode the value.

**Comment by paolooo** [comment]
Thanks @ben221199 and @lindyhopchris that makes sense.

I forgot that I'm passing this in `application/json` format. I was thinking sending the payload in `multipart/form-data`.

I might be sending in two request. Just like that this guy suggested: 
https://stackoverflow.com/a/38296217/959060

Or, using `multipart/related`, see:
https://stackoverflow.com/a/37394437/959060

**Comment by lindyhopchris** [comment]
If you haven't already seen it, you might want to check out this chapter in the docs. It's about supporting decoding different media types. It's a bit complicated but does work to support other media types such as multipart form data:
https://laravel-json-api.readthedocs.io/en/latest/features/media-types/#decoding

I'm going to close this issue for now - reopen if needed.

**Comment by paolooo** [comment]
Thanks for the help @lindyhopchris 👍 

I've actually added a file decoder already `multipart/form-data` but still got some issue. 

I want to update the user photo via `PATCH  or PUT /api/v1/users/1/photo` but I can't make it work.

My version is similar to the sample below but the URI path is different.
https://github.com/cloudcreativity/laravel-json-api/blob/68427f9d5b3cdb3c3f272d839e96acc3e31c75bd/tests/dummy/tests/Feature/Avatars/CreateTest.php#L52

I'm using a controller to handle this.
`$users->put('{record}/photo', 'handlePhoto');`

Is this possible? Please let me know.

Thanks.

**Comment by lindyhopchris** [comment]
Yeah should be possible if you're using standard Laravel methods to register a `PUT` route. What's the problem?

**Comment by paolooo** [comment]
Yeah! The issue with `PUT` and `PATCH` is it doesn't support well with `multipart/form-data` content type. So, what I did is I used `POST` but I've added a query parameter `?_method=PATCH` to make it to the `*.patch()` route.

https://stackoverflow.com/questions/50691938/patch-and-put-request-does-not-working-with-form-data/50691997

Solution in short:

`POST /api/v1/users/10/photo?_method=PATCH`

instead of

`PATCH /api/v1/users/10/photo`

Thanks anyway @lindyhopchris and @ben221199
