### ISSUE TITLE
French translation

### ISSUE THREAD

**Issue by osteel** [cloudcreativity/laravel-json-api#585]
Hi,

I've just translated this package's `errors.php` and `validation.php` files to French for a project. Would you be interested in a PR for this? I can see there was one [for Dutch](https://github.com/cloudcreativity/laravel-json-api/pull/563) a few months ago, but just wanna make sure you'd actually be interested first.

Cheers,

Yannick

**Comment by lindyhopchris** [comment]
Yes happy to take a PR to add other languages!

**Comment by osteel** [comment]
@lindyhopchris cool, will do when I get a minute
