### ISSUE TITLE
How do i send data in a certain order(Eg ascending)

### ISSUE THREAD

**Issue by pro-cms** [cloudcreativity/laravel-json-api#594]
, example ascending, descending i tried sorting and it doesn't work , Anyone with sample code please share to help me as example

**Comment by lindyhopchris** [comment]
Hi. Sorting does work in this package. When you say "it doesn't work" - what do you actually mean? What problem are you encountering/

**Comment by lindyhopchris** [comment]
Closing this due to lack of information. Feel free to re-open with more specific information if needed.
