### ISSUE TITLE
How to add condition on how data are to be sent over the API

### ISSUE THREAD

**Issue by pro-cms** [cloudcreativity/laravel-json-api#597]
I have two tables, one is a Book table and another is a Book Payment table
in the Book table I just store book info and amount for payment and in the Book Payment table I store ref_id , book_id, user_id, etc

Now I want to send a response depending on whether the user has paid for the book or not if the user paid then it sends 1 in the is_paid part of the response else it displays 0 that I know it is not paid. i am steel  a beginner at this package

Anyone who can explain how to implement this

**Comment by ben221199** [comment]
I think you should looking at scopes: https://laravel-json-api.readthedocs.io/en/latest/fetching/filtering/#filter-scopes

**Comment by lindyhopchris** [comment]
Or this could be a filter? Not entirely sure where you are stuck! Is it in querying the database? Or to do with showing an `is_paid` attribute within the JSON:API resource?

**Comment by pro-cms** [comment]
I want to add is_paid in attribute part of response ,  if the user payment status of the book  is success, is_paid return 1 otherwise 0.

**Comment by pro-cms** [comment]
Thanks so much @lindyhopchris i found my solution from you explanation
