### ISSUE TITLE
Is it possible to sort by an accessor for a resource?

### ISSUE THREAD

**Issue by ericgaonz** [cloudcreativity/laravel-json-api#609]
@here @lindyhopchris

**Comment by lindyhopchris** [comment]
Can you define what you mean by "accessor" for a resource? If you could provide an example of how it would look using Eloquent's database query builder that would help.

**Comment by ericgaonz** [comment]
Just added an accessor into the Model,
```
    public function getOnHandAttribute()
    {
        return $this->stocks()->sum('amount');
    }
```

**Comment by ericgaonz** [comment]
the link you can read,
https://laravel.com/docs/8.x/eloquent-mutators#defining-an-accessor

**Comment by lindyhopchris** [comment]
Ok, yeah wasn't sure what you meant by sorting by it.

I'm going to close this issue for now as I don't think there's anything I need to do.
