### ISSUE TITLE
missing middleware when register custom action

### ISSUE THREAD

**Issue by eduardduta** [cloudcreativity/laravel-json-api#612]
My middleware is present on all default  methods for resource but it's missing when i declare custom action. 

Ex: 
```
Route::name('api.')->middleware(TenantIdentifier::class)->group(function (Router $router) {
    JsonApiRoute::server('api')
        ->resources(function (ResourceRegistrar $server) {
            $server
                ->resource('resource name', PatientController::class)
                ->actions(function (ActionRegistrar $actions) {
                    $actions
                        ->withId()
                        ->get("image", 'image');
                })->middleware(TenantIdentifier::class);
        });
});
```

**Comment by lindyhopchris** [comment]
@eduardduta what package are you using? `cloudcreativity/laravel-json-api` or `laravel-json-api/laravel`?

**Comment by eduardduta** [comment]
I'm using laravel-json-api/laravel

**Comment by lindyhopchris** [comment]
Ok, this issue is in the wrong repository. I'll move it now.

**Comment by lindyhopchris** [comment]
Actually I can't move it to a different organisation. Please can you create the issue in the correct repository here:
https://github.com/laravel-json-api/laravel

**Comment by eduardduta** [comment]
my bad, done, thank you
