### ISSUE TITLE
Pre-release docs

### ISSUE THREAD

**Issue by squigglybob** [cloudcreativity/laravel-json-api#617]
Hi There,

I'm working with a piece of legacy software which is using version 0.12.0 of this package.

Is there anywhere I can find the documentation for this version?

On https://laravel-json-api.readthedocs.io/en/latest it seems I am not looking at examples that relate to this much older version that I am using.

Thanks

**Comment by lindyhopchris** [comment]
You can view the docs folder on the `0.12.0` tag here:
https://github.com/cloudcreativity/laravel-json-api/tree/v0.12.0/docs
