### ISSUE TITLE
Unable to create json api resource with attribute name "type"

### ISSUE THREAD

**Issue by sunnydesign** [cloudcreativity/laravel-json-api#621]
When I create a resource with attribute name "type" and try to send a POST request with payload:

```
{
    "data": {
        "type": "files",
        "attributes": {
            "name": "file.pdf",
            "type": "img_product",
            "mime": "pdf",
            "size": 123456
        }
    }
}
```

I get an error:

```
{
    "jsonapi": {
        "version": "1.0"
    },
    "errors": [
        {
            "detail": "The member attributes cannot have a type field.",
            "source": {
                "pointer": "/data/attributes"
            },
            "status": "400",
            "title": "Non-Compliant JSON:API Document"
        }
    ]
}
```

**Comment by ben221199** [comment]
Yes, following the spec on https://jsonapi.org/ you are not allowed to use a `type` attribute inside your `attributes` object. This, because there is already a `type` element in your resource object.

**Comment by ben221199** [comment]
https://jsonapi.org/format/#document-resource-object-fields
> A resource object’s attributes and its relationships are collectively called its “fields”.
>
> Fields for a resource object MUST share a common namespace with each other and with type and id. In other words, a resource can not have an attribute and relationship with the same name, nor can it have an attribute or relationship named type or id.

**Comment by sunnydesign** [comment]
Thanks, I read it.
