### ISSUE TITLE
Support for multiple operations in a single request

### ISSUE THREAD

**Issue by sunnydesign** [cloudcreativity/laravel-json-api#624]
Hi, guys!
How i can bulk creating, editing and deleting records in a single requst?
May be you have an ideas?

**Comment by lindyhopchris** [comment]
This isn't yet supported by the JSON:API spec, so isn't implemented in this package (as the purpose of the package is to stick to the spec). I believe they will be adding something called *Atomic Operations* which will implement what you are asking for. When that gets tagged (think it will be in JSON:API v1.1) then I'll implement in the new package, which is `laravel-json-api/laravel`.

**Comment by sunnydesign** [comment]
Thanks, I'll wait.
