### ISSUE TITLE
Sparse fieldsets not working with included relationships

### ISSUE THREAD

**Issue by hayespdx** [cloudcreativity/laravel-json-api#629]
Sparse fieldset requests don't seem to be working with included relationships... `/api/v1/images?include=places&fields[places]=name,slug` returns all attributes for places, instead of just `name` and `slug`, as [JSON:API specifies here](https://jsonapi.org/format/#fetching-sparse-fieldsets).

**Comment by lindyhopchris** [comment]
@hayespdx can you confirm which package you are using - the legacy `cloudcreativity/laravel-json-api` package, or the newer `laravel-json-api/laravel` package?

**Comment by hayespdx** [comment]
I'm using the newer one, so this was a mistake! Sorry. I've opened the issue in the right place now, so feel free to close/delete this.

**Comment by lindyhopchris** [comment]
Thanks for opening in the other repo!
