### ISSUE TITLE
Handle HasMany relationship with extra field.

### ISSUE THREAD

**Issue by andrei1820** [cloudcreativity/laravel-json-api#636]
How can I handle hasmany pivot table, for example 2 foreign key id with a string description?

![image](https://user-images.githubusercontent.com/75318743/209606865-68d76187-f33b-4209-9b0a-20f219e1da94.png)

**Comment by ben221199** [comment]
Handle the pivot table as a new object, with 2 belongs-to relations.

**Comment by lindyhopchris** [comment]
Yep that would be the solution. Don't think of it is a pivot, think of it as an intermediary resource. I.e. JSON:API works in resources so you need to represent the pivot table as a resource in your API, with relationships between it and the two related resources on either "side" of the pivot.
