### ISSUE TITLE
Receiving 415 (Unsupported Media Type) error when making DELETE request.

### ISSUE THREAD

**Issue by jp-apps** [cloudcreativity/laravel-json-api#66]
Hello!

So far enjoying the library, it has been super helpful.

I found that when a DELETE request is made with a content-type different from application/vnd.api+json, a 415 Unsupported Media Type error is returned. I understand this should not be. As per the [specification](http://jsonapi.org/format/#content-negotiation-clients):
> Clients MUST send all JSON API data in request documents with the header Content-Type: application/vnd.api+json without any media type parameters.

This requirement that the content-type must be application/vnd.api+json is **only when there is data being sent**. A DELETE request contains no JSON api data, and therefore does not need to have that specific content-type.

I would like to modify this myself, where is this behavior being set? I'm having trouble locating it.

Thank you

Jean

**Comment by lindyhopchris** [comment]
Hi,

Glad you're finding the library useful! You make a really great point. Content negotiation is done in the `BootJsonApi` middleware, using this trait:
https://github.com/cloudcreativity/json-api/blob/master/src/Http/Middleware/NegotiatesContent.php

However, that is using the `neomerx/json-api` package's header checker to check the headers. Looking at their code, that is always checking the `Content-Type` header regardless of whether any HTTP request content has been sent:
https://github.com/neomerx/json-api/blob/master/src/Http/Headers/RestrictiveHeadersChecker.php#L47-L52

I'll create an issue there as I think there implementation isn't spec compliant.

**Comment by lindyhopchris** [comment]
Opened this issue:
https://github.com/neomerx/json-api/issues/178

**Comment by jp-apps** [comment]
Super quick response. It helped a lot. Thank you!

**Comment by lindyhopchris** [comment]
@jp-apps

question for you that will help me out. It's regarding this comment in the other issue:
https://github.com/neomerx/json-api/issues/178#issuecomment-307047190

The `DELETE` request you were sending, did it include a `Content-Length` or `Transfer-Encoding` header?

**Comment by jp-apps** [comment]
The `DELETE` request I am sending does not contain any `Content-Length` or `Transfer-Encoding` header. 

I've been following the issue and looked into that last comment you referenced. The request's `DELETE` method spec does not indicate any restriction on whether it should or should not include a message-body. Therefore, I think one can be included. If there if a message-body, then the server should forward it **unless** there is no `Content-Length` or `Transfer-Encoding` header, in which case it should be ignored. So, I think you can't rely on getParsedBody() returning `null`, you would have to rely on the `Content-Length` or `Transfer-Encoding` headers.

**Comment by lindyhopchris** [comment]
Yeah, that's my thoughts exactly. Not sure how this is going to go though...
