### ISSUE TITLE
Relate Elocuent resource with not Elocuent resource?

### ISSUE THREAD

**Issue by gigo6000** [cloudcreativity/laravel-json-api#68]
I have an Elocuent model with a one-to-many relationship with another non-elocuent Resource and I'm getting this error:

`
Relationship method must return an object of type Illuminate\Database\Eloquent\Relations\Relatio  
`
It seems to me is not possible to do this relationship? Thanks

**Comment by lindyhopchris** [comment]
Hi! This is totally possible to do, you just need to return the related resource manually in the schema. 

Here's a theoretical example. So you have a `posts` resource that had an `author` relationship. But the `author` was not an Eloquent model and was instead loaded via an `AuthorRepository`. Your schema would look like this:

```php
<?php

use CloudCreativity\LaravelJsonApi\Schema\EloquentSchema;
use Neomerx\JsonApi\Contracts\Schema\SchemaFactoryInterface;

class Schema extends EloquentSchema
{

    /**
     * @var AuthorRepository
     */
    private $authorRepository;

    /**
     * Schema constructor.
     *
     * @param SchemaFactoryInterface $factory
     * @param AuthorRepository $authorRepository
     */
    public function __construct(SchemaFactoryInterface $factory, AuthorRepository $authorRepository)
    {
        parent::__construct($factory);
        $this->authorRepository = $authorRepository;
    }

    /**
     * @param Post $resource
     * @param bool $isPrimary
     * @param array $includeRelationships
     * @return array
     */
    public function getRelationships($resource, $isPrimary, array $includeRelationships)
    {
        return [
            'author' => [
                self::DATA => $this->authorRepository->find($resource->author_id),
            ],
        ];
    }
}
```

On your hydrator, you can implement a method for custom logic as to how to hydrate the author relationship:

```php
<?php

use CloudCreativity\LaravelJsonApi\Hydrator\EloquentHydrator;
use CloudCreativity\JsonApi\Contracts\Object\RelationshipInterface;

class Hydrator extends EloquentHydrator
{

    /**
     * @param RelationshipInterface $relationship
     * @param Post $record
     */
    protected function hydrateAuthorRelationship(RelationshipInterface $relationship, Post $record)
    {
        // whatever logic you need here. This will be executed **before** the Post is saved.
    }

    /**
     * @param RelationshipInterface $relationship
     * @param Post $record
     */
    protected function hydrateRelatedAuthor(RelationshipInterface $relationship, Post $record)
    {
        // this will be executed **after** the Post is saved, i.e. as a second step of hydration.
    }
}
```

Note that you should only implement one of `hydrateAuthorRelationship` or `hydrateRelatedAuthor` - if you did both you'd get a double hydration of the author relationship.

If the above doesn't help, then can you put an example of the code that you're having problems with as that means I can give you an answer that is more specific to your use case!

**Comment by gigo6000** [comment]
Awesome! I think it worked fine. I haven't tried the Hydrator change but the relationship is working now. Thanks for your time.
