### ISSUE TITLE
Request: Example of new "encoder" helper method?

### ISSUE THREAD

**Issue by SirLamer** [cloudcreativity/laravel-json-api#71]
It is not clear to me how to use this based on what can be inferred from the code base. Could you please provide a simple example?

In my case, I am trying to access the API in a Laravel Controller envrionment before loading. I would also infer that the interface for the Blade helper method would be similar, though.

**Comment by lindyhopchris** [comment]
When you say "trying to access the API in a Laravel Controller environment before loading"... I'm not sure what that means. Could you provide an example of what you're trying to do?

Basic usage is:

```php
JsonApi::encoder('default')->serializeData($data);
```

Full signature of `encoder` is `encoder($apiName, $host = null, $options = 0, $depth = 512)`

In blade templates:

```
@encode($data)
```

That will use the `default` API. If you need to use a different one:

```
@jsonapi('v1')
@encode($data)
```

Full signature of `@jsonapi` is: `@jsonapi($apiName, $host = null, $options = 0, $depth = 512)`
Full signature of `@encode` is: `@encode($data, $includePaths = null, $fieldSets = null)`

**Comment by lindyhopchris** [comment]
Closing this as I've added documentation for both views and helpers on the `develop` branch (will be included in next release).

**Comment by SirLamer** [comment]
Sorry for not replying... I know I drafted a response but I think I forgot to submit.

Your tips above helped. In particular, arranging it as ```JsonApi::encoder('default')->serializeData($data);``` is what I couldn't figure out.

In case it helps, I have prepared these helper functions for myself.
```php
    /**
     * @param Model|Collection|array $models
     * @param string|array $includes
     * @return mixed
     */
    public static function apiEncoder($models, $includes = []) {
        if (is_string($includes)) {
            $includes = [$includes];
        }

        return JsonApi::encoder('default')->serializeData($models, new EncodingParameters($includes));
    }

    /**
     * @param Model[]|Collection[]|array[] $collection
     * @return array
     */
    public static function apiArrayEncoder($collection) {
        $buffer = [];
        foreach ($collection as $row) {
            if (!is_array($row)) {
                $query = static::apiEncoder($row);
            } else {
                $query = static::apiEncoder($row[0], array_slice($row, 1));
            }
            if (array_key_exists('type', $query['data'])) {
                $query['data'] = [$query['data']];
            }
            $buffer[] = $query;
        }

        return call_user_func_array('array_merge_recursive', $buffer);
    }

    /**
     * @param Collection[]|array[] $collection
     */
    public static function apiSessionData($collection) {
        Session::flash('db', static::apiArrayEncoder($collection));
    }
```

In various controller environments I use this as so:

```php
        Helpers::apiSessionData([
            [$project, 'client-company', 'project-type', 'project-status', 'office', 'tasks'],
            Office::all(),
            [ProjectType::all(), 'default-task-types'],
            ProjectStatus::all(),
            TaskType::all()
        ]);
```

This gets encoded to a JS object included in the header, along with a bunch of other stuff, at this call here:
```html
<script>
    window.__HOISTWAY_STORE__ = {!! json_encode(array_merge(Helpers::sessionData(), [])) !!}
</script>
```

The store object is read in to VueX.

Event broadcasting uses ```Helpers:::apiEncoder()``` to generate the event payload.

**Comment by lindyhopchris** [comment]
These new features will help in the next version:

https://github.com/cloudcreativity/laravel-json-api/blob/develop/docs/features/helpers.md

https://github.com/cloudcreativity/laravel-json-api/blob/develop/docs/features/views.md

**Comment by lindyhopchris** [comment]
On events that broadcast, you can use this:
https://github.com/cloudcreativity/laravel-json-api/blob/develop/src/Broadcasting/BroadcastsData.php

I need to add something to the docs about that
