### ISSUE TITLE
Custom query parameter

### ISSUE THREAD

**Issue by pascal08** [cloudcreativity/laravel-json-api#75]
_I could go into the details of the issue without thanking the owner(s) of this package for sharing this package with the world! Thanks a lot everyone who contributed!_

Here is my issue:
I'm using this package in combination with JWT authentication. Therefore, I need to send a valid authentication token as a request parameter to authenticate the user who is requesting data. However, the `RestrictiveQueryChecker` does not allow any `unrecognized parameters` (as they are called in this package) to be part of the query parameters unless I explicitly set `$allowUnrecognizedParameters = true`. I think this implies that I'm allowing every parameter to be part of the request data which, I guess, defeats the purpose of all other query validations. Is there a way to whitelist only certain query parameters I explicitly allow to be part of the request?

**Comment by lindyhopchris** [comment]
Thanks for the feedback! 

I totally agree with the intent of your issue... we also use JWT and have to also set `allowUnrecognizedParameters` to `true`. The query parsing is done by the underlying `neomerx/json-api` package, and that only allows that setting to be `true` or `false`.

Note that this does not disable parsing or validation of any of the "official" JSON API query paramets. By "unrecognised parameters", what the neomerx package is referring to is ones that are not in the JSON API spec. So even if you set that to true, the official ones such as `filter`, `page` still get processed.

Does that answer the question or were you hoping for something about the implementation to be changed? Just let me know!

**Comment by pascal08** [comment]
I was not aware of the fact the other query validations would still be processed. That is a good thing to hear. 

Do you know if allowing `unrecognized parameters` to be in the request data has security implications?

**Comment by lindyhopchris** [comment]
I don't think it matters because if you get the query parameters from the Laravel request, you'd get them all anyway. It's more a JSON API thing... it's talking about parameters that the encoder won't recognise because they're not in the spec.

Will close this issue for the moment but feel free to ask any more questions!

**Comment by pascal08** [comment]
Great! Thanks for your quick response!
