### ISSUE TITLE
Adding include, filter, sort... on Related Resource

### ISSUE THREAD

**Issue by JeanLucEsser** [cloudcreativity/laravel-json-api#77]
Hi there,

I'm almost done updating my full application to this library, which btw is simply amazing, only to face a last minute issue. Let me explain. Consider a `Post` with many `Comment`s.

Using related resources I can have the following endpoint:
`/api/posts/{post_id}/comments`

Now I would like to implement pagination on this and I know it is on the path to 1.0, that's awesome news. But I also need to be able to include other resources or apply some filters.

But the following doesn't work:
 `/api/posts/{post_id}/comments?include=author&filter[title]=hello`

I would have expected that it would be parsed by the `Comment` Adapter and Validator.
I don't see anything in the spec preventing filtering or inclusion on related resources, unless I missed it.

Sure I could achieve the same result by adding a filter on the comments endpoint:
` /api/comments?include=author&filter[title]=hello&filter[posts-id]={post_id}`

But that's not how my API is documented and isn't the best way of doing it.

Is it something which is on the radar? Maybe on the road to 1.0?

**Comment by lindyhopchris** [comment]
Hi! Really glad you like the package!

Yes, you should totally be able to do this. The reason it isn't working at the moment is because the relationship stuff hasn't been fully implemented - which is why the relationship stuff is the biggest thing on the 1.0 path.

I agree that a request to `posts/1/comments` needs to be passed to the Comments adapter/validators rather than the posts one. I need to work out a way of neatly doing that and then put in the code to do it.

Will definitely be in for 1.0. I've being doing some work on all the non-relationship stuff that's on the 1.0 list, with the idea being that I'll move on to the relationship stuff next.

**Comment by JeanLucEsser** [comment]
I see you're hard at work ;) That's awesome news.
Thanks.

**Comment by JeanLucEsser** [comment]
Oops, closed the issue, didn't know if you wanted to keep it open for reference.
Feel free to reopen ;)

**Comment by lindyhopchris** [comment]
no problem!

**Comment by theTechGuyy** [comment]
before I open a new ticket I was wondering if this also applies to sorting on related attributes on the main resource.
For example: GET /contracts?include=user&sort=user.firstname

Or is this already supported and I just can't seem to figure it out?

**Comment by lindyhopchris** [comment]
@theTechGuyy sorting is supported. 

Set the allowed sort params on your validator class, e.g.:
https://github.com/cloudcreativity/laravel-json-api/blob/master/tests/JsonApi/Posts/Validators.php#L30-L35

And then you'll need to implement how to apply that sorting in your adapter. The Eloquent sorting will automatically apply sort parameters itself, but wouldn't work with `user.firstname` because the sorting happens when querying the database. It does it here:
https://github.com/cloudcreativity/laravel-json-api/blob/master/src/Store/EloquentAdapter.php#L320-L331

So you'd have to overload the methods if you have some other sorting logic?

**Comment by theTechGuyy** [comment]
Ahh thanks so much - and sorry for hijacking the issue..

**Comment by moneal** [comment]
@theTechGuyy I'm not seeing `sortBy` called on my adapter at all. Using 0.11 which looks like it has #96 merged on Laravel 5.5

**Comment by lindyhopchris** [comment]
@moneal I'll take a look at this now

**Comment by lindyhopchris** [comment]
@moneal I've added a test to the `master` branch that definitely checks that the `sortBy` method is being called. Can you describe more about the scenario you have where it is not being called?

**Comment by moneal** [comment]
@lindyhopchris This is what I'm testing with right now.
```php
public function testUserNotesSortDescending()
{
    // $this->markTestSkipped('Sort not currently working');
    $user = factory(User::class)->create();
    /** @var Collection $notes */
    $notes = factory(Note::class, 3)->make()->each(function ($note, $index) use ($user) {
        /** @var Note $note */
        $note->created_at = Carbon::now()->addSeconds($index);
        $note->updated_at = $note->created_at;
        $note->notable()->associate($user);
        $note->save();
    });
    $response = $this->actingAs($user)->doRead($user->id, [
        'include' => 'notes',
        'sort' => '-notes.created_at'
    ]);
    $response->assertSearchOneResponse($user->id);
    $response->assertJson([
        'data' => [
            'relationships' => [
                'notes' => [
                    'data' => [
                        [
                            'type' => 'notes',
                            'id' => $notes[2]->getKey()
                        ],
                        [
                            'type' => 'notes',
                            'id' => $notes[1]->getKey()
                        ],
                        [
                            'type' => 'notes',
                            'id' => $notes[0]->getKey()
                        ]
                    ]
                ]
            ]
        ]
    ]);
}
```

**Comment by lindyhopchris** [comment]
I don't think the sort parameter needs to be `-notes.created_at`, it should just be `-created_at`

**Comment by moneal** [comment]
When using `-created_at` it is not changing the order of the related notes.

**Comment by lindyhopchris** [comment]
Ah, is this a relationship of the users resource? I.e. you're doing a request at `users/1/notes`? If so, you'll have to manually implement applying the sort order in the controller method as I haven't implemented full support for searching relationships yet - it's on the to-do list for 1.0.

**Comment by lindyhopchris** [comment]
Sorting of related resources is now supported on the 1.0 branch.

**Comment by ralrom** [comment]
Sorry but I'm not sure I understood correctly, is it now possible to sort on an included resource or is it still necessary to implement our own sorting logic?

Ex: `/safaris?include=console.owner&sort=-console.owner.updated_at`

**Comment by lindyhopchris** [comment]
This refers to sorting on related paths: i.e. `GET /api/posts/1/comments?sort=-created-at` will sort the comments in the response.

Sorting included resources is not supported. The spec says:

> An endpoint MAY support requests to sort the primary data with a sort query parameter.

Note that it refers to *sort the primary data*: included resources are not the primary data.

**Comment by ProteanCode** [comment]
> Ahh thanks so much - and sorry for hijacking the issue..
> 
> Edit:
> just for anybody googling towards this and wondering on how to achieve the sorting by related columns in a somewhat generic way with overloading the EloquentAdapter.sortBy function. Should
> work with master as soon as #96 is fixed:
> 
> ```
>    /**
>      * @param Builder $query
>      * @param SortParameterInterface $param
>      */
>     protected function sortBy(Builder $query, SortParameterInterface $param)
>     {
>         $column = $this->getQualifiedSortColumn($query, $param->getField());
>         $order = $param->isAscending() ? 'asc' : 'desc';
>         if (!starts_with($column, $query->getModel()->getTable())) {
>             // related sorting
>             $relation = substr($column, 0, strpos($column, '.'));
>             $attribute = substr($column, strlen($relation) + 1);
>             $relation = $query->getModel()->$relation();
>             $relatedTable = $relation->getRelated()->getTable();
>             // Include related table
>             $query->leftJoin(
>                 $relatedTable,
>                 $query->getModel()->getTable().'.'.$relation->getForeignKey(),
>                 '=',
>                 $relatedTable.'.'.$relation->getOwnerKey()
>             );
>             // correct column name to match model table
>             $column = $relatedTable.'.'.$attribute;
>         }
>         $query->orderBy($column, $order);
>     }
> ```

getForeignKey() exists on a model, not relation. Relation uses getForeignKeyName()
