### ISSUE TITLE
error: Paging parameters exist but paging is not supported

### ISSUE THREAD

**Issue by morgandenning** [cloudcreativity/laravel-json-api#79]
Received this error when attempting to send pagination parameters to an endpoint. Is pagination supported, and if so, how do I enable it?

**Comment by lindyhopchris** [comment]
Hi! Inject the standard paging strategy into your adapter constructor. The standard paging strategy is `CloudCreativity\LaravelJsonApi\Pagination\StandardStrategy`

Your constructor should be:

```php
public function __construct(StandardStrategy $strategy)
{
  parent::__construct(new Post(), $strategy);
}
```

Where `Post` is your model class.

If you are using the generatores, e.g. `make:json-api:resource` or `make:json-api:adapter` then this will already be in the generated adapter.

I'll add some docs on pagination now.

**Comment by morgandenning** [comment]
I could not get it to work just by adding it into the constructor, however re-recreating the resource via `make:json-api:resource` worked fine.

Thanks!

**Comment by lindyhopchris** [comment]
Great, glad to hear you got it working. Some docs are now available here:
https://github.com/cloudcreativity/laravel-json-api/blob/develop/docs/features/pagination.md
