### ISSUE TITLE
Schemas loading for relationships

### ISSUE THREAD

**Issue by phaberest** [cloudcreativity/laravel-json-api#8]
Hi @lindyhopchris and thanks in advance for this awesome work!
I'm getting an error when I try to add a relationship in my schema, it seems it can't find the schema for the relationship, even if I've set it in the configuration file.

The error I get is
>InvalidArgumentException in Parser.php line 241:
>Schema is not registered for a resource at path 'addons'.

In `json-api.php` I set the schemas array as follows
```php
/**
 * Schemas
 */
C::SCHEMAS => [
    Schemas::DEFAULTS => [
        'App\Models\Addon'    => 'App\Schemas\AddonSchema',        // The relationship
        'App\Models\Shipment' => 'App\Schemas\ShipmentSchema',
    ],
    // merged with defaults if JSON API middleware uses the 'extra-schemas' name.
    'extra-schemas' => [
        'User' => 'UserSchema',
    ],
],
```
And in the parent model schema I have
```php
public function getRelationships(
    $shipment,
    array $includeList = []
) {
    /** @var Shipment $shipment */
    return [
        'addons'   => [
            self::DATA         => $shipment->addons,
            self::SHOW_SELF    => true,
            self::SHOW_RELATED => true
        ],
        'sender'   => [self::DATA => $shipment->sender],
        'receiver' => [self::DATA => $shipment->receiver],
    ];
}
```

I'm having troubles understanding the docs 100%, maybe I did something wrong. Maybe I'm not including enough from neomerx/json-api...I am jumping from an error to another :pensive:

Thanks for your help

**Comment by samsebastian** [comment]
I had a problem like this, I can't remember if this was what fixed it but it might be not detecting the Addons model properly if empty.

I created a parent "Schema" class to add in a few extra tools like this:

```php
<?php
namespace App\Schemas;

use Neomerx\JsonApi\Schema\SchemaProvider;

use Illuminate\Database\Eloquent\Collection;

abstract
class Schema extends SchemaProvider
{
	public
	function getId($resource)
	{
		return $resource->id;
	}

	protected
	function extractRelation($resource, $relationName, $force = false)
	{

		if (empty($resource->{$relationName}) && $force)
		{
			$resource->load($relationName);
		}

		if (empty($resource->{$relationName}))
		{
			return null;
		}

		if ($resource->{$relationName} instanceof Collection)
		{
			return $resource->{$relationName}->all();
		}

		return $resource->{$relationName};
	}

}
```
And then when I extract the relationship I do it like:

```php
<?php
namespace App\Schemas;

use App\Schemas\Schema;

class `ShipmentSchema` extends Schema
{
...

	public
	function getRelationships($shipment, array $includeRelationships = [])
	{
		return [
			'addons' => [
				self::DATA         => $this->extractRelation($shipment, 'addons')
			],
		];
	}

}
```

**Comment by lindyhopchris** [comment]
@phaberest Sorry for slow reply - I've been on holiday the last two weeks.

The error you're getting is a `neomerx/json-api` error - the most likely cause is that if `$shipment->addons` returns an Eloquent Collection, then the encoder will be trying to lookup a schema for that class, rather than the class of model that is contained within the collection. You need to cast the addons relationship to an array i.e. `$shipment->addons->all()`

Does that fix it?

**Comment by phaberest** [comment]
Thanks to both of you, I have temporarily put it in the parent element `getAttributes()` ad I've added an accessor in the model to return the array as I wanted.

Tried on fly @lindyhopchris solution and it seems to look for the schema :+1: I'll look into it, thanks a lot!
