### ISSUE TITLE
When using sortColumns to map column name differences, column returns null

### ISSUE THREAD

**Issue by morgandenning** [cloudcreativity/laravel-json-api#84]
We have a legacy database that we are mapping new attribute names to. This works great when using Hydrator and Schema attributes mapping, however when we add in sortColumns in the Adapter, so that we can search with the preferred attribute name, the sorted attribute returns a null value.

Here are some examples.

Schema.php
```php
protected $attributes = [
        'UnitName' => 'name',
        'UnitCode' => 'code',
        'status' => 'status'
    ];
```

Hydrator.php
```php
protected $attributes = [
        'id' => 'UnitID',
        'name' => 'UnitName',
        'code' => 'UnitCode'
    ];
```

Adapter.php
```php
protected $sortColumns = [
        'name' => 'UnitName'
    ];
```

**Comment by lindyhopchris** [comment]
Hi. Sorry for not replying earlier. I'm not sure I understand what you means by 'the sorted attribute returns a null value'?

**Comment by morgandenning** [comment]
No worries about the delay! After writing out a much more descriptive explanation and grabbing some response examples, it appears this was just an error on our data, where null values existed that shouldn't have (I should have looked at more than `X` records, I guess).

I'll close this issue.

**Comment by lindyhopchris** [comment]
Great, well glad you got it sorted!
