### ISSUE TITLE
Custom validation rules

### ISSUE THREAD

**Issue by danherd** [cloudcreativity/laravel-json-api#86]
Hi,

_(Using Eloquent models again)_

How would I go about using custom validation rules? I'm currently using the following function in the Validators file of my resource:

```
protected function attributeRules($record = null)
{
  $required = $record ? 'sometimes|required' : 'required';

  return [
    'name' => $required . '|max:191',
    'email' => $required . '|email|max:191|unique:users',
    'password' => $required . '|min:6|confirmed',
  ];
}
```

This works, but only on POST (create). If I wanted to PATCH the resource and submitted the same email address in the data attributes, it would throw an error, because it checks the entire users table for email uniqueness - including the record we are trying to update.

See this section in the Laravel docs (headed **Forcing A Unique Rule To Ignore A Given ID:**) for an example of a custom rule - [https://laravel.com/docs/5.4/validation#rule-unique](https://laravel.com/docs/5.4/validation#rule-unique)

Cheers.

**Comment by lindyhopchris** [comment]
`$record` will be `null` if creating, or the object instance if patching.

So using the Laravel example you can do:

```php
    'email' => [
        $required,
        $record ? Rule::unique('users')->ignore($record->id) : Rule::unique('users'),
    ],
```

**Comment by danherd** [comment]
Magic - thanks!

**Comment by spawnia** [comment]
I just stumbled across this, just wanted to show that this can be written a bit more concise:

````php
'email' => "$required|unique:users,email" . ($record ? ',' . $record->id : ''),
````
