### ISSUE TITLE
RestrictiveQueryChecker (filter, sort, etc)

### ISSUE THREAD

**Issue by samsebastian** [cloudcreativity/laravel-json-api#9]
Hey again,

Just trying to figure out where to pass the rules for the RestrictiveQueryChecker in the underlying neomerx package?

I'm getting an error on `->checkFiltering` etc, but I don't know where in the controller to allow filtering params?

Would be a good update to the docs if it's an easy answer :) :+1:

**Comment by lindyhopchris** [comment]
Override the properties on the controller, e.g.

``` php
protected $allowedFilteringParameters = ['foo', 'bar'];
```

Good point, this needs to be clearer in the docs. I'll leave this issue open so that I remember to do that.

**Comment by samsebastian** [comment]
Also om this topic, I can now see 

`$sort = $this->getParameters()->getSortParameters()` 

but when I try to access them like `$sort[0]->sortField` it throws an error of 

`Cannot access private property Neomerx\JsonApi\Parameters\SortParameter::$sortField`.

Is there a different way we're supposed to access the sort parameters?

**Comment by lindyhopchris** [comment]
https://github.com/neomerx/json-api/blob/master/src/Contracts/Encoder/Parameters/SortParameterInterface.php
