### ISSUE TITLE
How to filter a default Eloquent model

### ISSUE THREAD

**Issue by MarjovanLier** [cloudcreativity/laravel-json-api#93]
How do one filter the default result set an Eloquent model gives over to JSON API?

**Comment by lindyhopchris** [comment]
Hi! Here's an example in the demo app:
https://github.com/cloudcreativity/demo-laravel-json-api/blob/5.4/app/JsonApi/Posts/Adapter.php#L34-L43

I.e. put your filtering logic into the `filter` method on your resource's adapter.

You will also need to allow the filter parameters on your validator, as per this:
https://github.com/cloudcreativity/demo-laravel-json-api/blob/5.4/app/JsonApi/Posts/Validators.php#L40-L44

In those examples, sending a request to with the `filter[title]` query param would then filter the posts resource.

Sorry there's no docs at the moment, but hope the examples help. Do let me know if you have any questions.

**Comment by dennismende** [comment]
Hi,

how would I filter a collection? E.g. I have a model "post" with a hasMany "comments" and I would like to filter for: all posts with comment = 1

Thanks

**Comment by lindyhopchris** [comment]
@dennismende sorry for slow reply, I've been on holiday.

not sure I understand your question as presumably there is only one post that comment 1 can be linked to?

My general tip is work out how you'd write the query using Eloquent - i.e. forget about the JSON API implementation and just work out how you'd query the models. Once you've done that, you just need to drop the query into the adapter `filter` method.

Let me know if you need more help.

**Comment by dennismende** [comment]
Thanks. Everything ok for me. Addon works great. We are very interested in 1.0.
