### ISSUE TITLE
Upgrade to Laravel 5.5

### ISSUE THREAD

**Issue by lindyhopchris** [cloudcreativity/laravel-json-api#95]
Just in case anyone is looking for 5.5 support - I've spotted that it has now been released and will hopefully upgrade this package shortly. Just subscribe to this issue so that you know when the upgrade is done.

**Comment by JeanLucEsser** [comment]
Let me hijack this issue for a moment to ask 2 things:

- do you have an ETA on the path to 1.0? I know as a developper to never ask such questions, it'll ship when it's ready, but as I wish to rely on this package for a project, it would be nice to have an idea in terms of end of month, end of year, or first semester 2018...

- I'm just reading through the release notes for Laravel 5.5 and found out about the new API resources, is it something you are planning to use? Maybe in a future 1.x or even 2.0 version of the package. Or not at all. I like the way the package has been thought out right now, with clear responsibilities. And I guess you are dependent upon Neomerx for such things (Schemas).

Best.

**Comment by lindyhopchris** [comment]
Hi @JeanLucEsser 

No problem hijacking the issue! Both are really good questions.

So I would like to get to 1.0 by the end of the year. It's probably worth explaining that I have a full time job and an internet start-up that I'm developing in my own time. You might have noticed that I go through short periods where I get lots done on this open source project, and then go quiet for a bit - it's basically because my dev time is pretty much all taken up at the moment. When I do get time to spend on the package, it's normally because a feature is needed either by work or my start-up (which both use this package). I do however want to stabilise the package as soon as possible. The only thing holding back 1.0 at the moment is time rather than a desire to sort it out!

In terms of the Laravel 5.5 API resource thing, I have no plans to use that for this package. Although it looks like a useful way of quickly dumping Eloquent data out via an API (particularly to Javascript frontends), it doesn't look useful as a way of supporting the complexity of the JSON API spec - particularly things like include paths, sparse fieldsets, etc. The thing I love about the JSON API spec is that it's incredibly well thought out, so I wouldn't want to sacrifice compatibility with the entirety of the spec just to use a Laravel feature that I think is useful, but is insufficient for complex standards-compliant APIs. And as you say, I am reliant on the Neomerx package for encoding, but I think that dependency is really worthwhile as it handles all parts of the JSON API spec and is highly performant.

So the new Laravel API resources definitely won't be used for v1.0. It will however be worth keeping an eye on what Laravel does with it in the future and maybe converge towards its pattern if that's possible in the future - as I'm trying to do things as much as possible in a Laravel way!

**Comment by JeanLucEsser** [comment]
The work you have done with this package is nothing short of amazing. Really.

The only thing preventing me from going all in for now is my issue #77 but as soon as this is resolved, I'll be using it a lot! I guess this issue will be dealt with towards the end of the path to 1.0.

Anyway, good luck with your start-up (I've been there and still am).

**Comment by lindyhopchris** [comment]
A note on the upgrade to Laravel 5.5 so far....

This seems to all be fine with one exception - the change from PHPUnit 5 to 6 breaks the test helpers in this package. My plan was for v1.0 of this package to support both Laravel 5.4 and 5.5 because we (I'm sure like many other people!) have applications that we cannot upgrade to PHP 7 because of legacy code that is not worthwhile the cost and time of upgrading.

For this package to support both Laravel 5.4 and 5.5, I'm going to split the test helpers out into a separate package that people can then install via composer's `require --dev`. This will allow two versions of the test package to exist, one that installs with PHPUnit 5 and one with PHPUnit 6.

**Comment by lorenzleutgeb** [comment]
Hey! We're also very happy with this library and looking to migrate to 5.5 very soon. Supporting 5.4 and 5.5 with the compromise of tests in a separate package seems quite reasonable. In case you need additional manpower feel free to ping me. :) Rock on!

**Comment by lindyhopchris** [comment]
Support for Laravel 5.5 has been released in `v0.11` - which is also backwards compatible for Laravel 5.4.

It's a really short upgrade step, here's the guide:
http://laravel-json-api.readthedocs.io/en/latest/upgrade/#upgrading-to-011-from-010

If you discover any bugs etc, create a new issue. I won't be using Laravel 5.5 in earnest for some time, so letting me know any issues will be appreciated!
