### ISSUE TITLE
Eloquentadapter.getQualifiedSortColumn wrong str_contains usage?

### ISSUE THREAD

**Issue by theTechGuyy** [cloudcreativity/laravel-json-api#96]
If I'm not completely misunderstanding the works of the `Eloquentadapter.getQualifiedSortColumn` method, it uses the str_contains laravel helper with the wrong order of arguments.

Instead of 
`str_contains('.', $key)`
it should be
`str_contains($key, '.')`

The conditional currently gets always executed if the  key is not equal to '.'

Obviously I could be wrong - if so please enlighten me / close the issue.

Codelink:
https://github.com/cloudcreativity/laravel-json-api/blob/master/src/Store/EloquentAdapter.php#L367
Laravel doc for str_contains:
https://laravel.com/docs/5.4/helpers#method-str-contains

**Comment by lindyhopchris** [comment]
Hey! Yep, from what you've posted that does look the wrong way round. I'll look into it and get back to you but suspect it probably needs a bugfix.

Thanks for reporting.

**Comment by theTechGuyy** [comment]
I can gladly fix it and create a PR.
In general: awesome work so far and my startup is already using the library, if I spot anything that could / needs to be done I can help out as we go.

**Comment by lindyhopchris** [comment]
@theTechGuyy a PR would be great

glad you're finding the package useful and thanks for the offer of help
